import TaoTrudgianYang2025

open Lean

namespace TaoTrudgianYang2025.Audit

private def permittedAxioms : Array Name :=
  #[`propext, `Classical.choice, `Quot.sound]

private def bootstrapDeclarations : Array Name := #[
  `Expdb.automatic_uniformity_of_choicewise_bounded,
  `Expdb.isExponentSumBound_exponentSumGrowthExponent,
  `Expdb.exponentSumGrowthExponent_le_iff_nonAsymptotic,
  `RiemannZeta.GuthMaynard.guthMaynardLargeValues_published_native,
  `RiemannZeta.GuthMaynard.guthMaynardZeroDensity_published_native
]

private def targetTheorems (env : Environment) : Array Name := Id.run do
  let mut names := #[]
  for (name, info) in env.constants.toList do
    if name.getRoot == `TaoTrudgianYang2025 && info.isTheorem &&
        !isPrivateName name then
      names := names.push name
  return names.qsort Name.quickLt

def runBootstrapDependencyAudit : CoreM Unit := do
  let env ← getEnv
  let discovered := targetTheorems env
  let declarations := bootstrapDeclarations ++ discovered
  let mut failures : Nat := 0
  logInfo "=== TAO--TRUDGIAN--YANG BOOTSTRAP AXIOM AUDIT ==="
  logInfo m!"Imported boundary declarations: {bootstrapDeclarations.size}"
  logInfo m!"Discovered nonprivate target theorems: {discovered.size}"
  for name in declarations do
    if !env.contains name then
      failures := failures + 1
      logInfo m!"FAIL [missing declaration] {name}"
    else
      let axioms ← Lean.collectAxioms name
      let forbidden := axioms.filter fun axiomName =>
        !permittedAxioms.contains axiomName
      if forbidden.isEmpty then
        logInfo m!"PASS {name}: {axioms}"
      else
        failures := failures + 1
        logInfo m!"FAIL {name}: forbidden dependencies {forbidden}; all axioms {axioms}"
  if failures == 0 then
    logInfo m!"AUDIT PASS: all {declarations.size} imported and target declarations have permitted dependencies."
  else
    throwError "AUDIT FAIL: {failures} bootstrap dependency failure(s)"

#print axioms Expdb.automatic_uniformity_of_choicewise_bounded
#print axioms Expdb.isExponentSumBound_exponentSumGrowthExponent
#print axioms Expdb.exponentSumGrowthExponent_le_iff_nonAsymptotic
#print axioms RiemannZeta.GuthMaynard.guthMaynardLargeValues_published_native
#print axioms RiemannZeta.GuthMaynard.guthMaynardZeroDensity_published_native
#print axioms TaoTrudgianYang2025.generatedExponentPairCoordinates_count
#print axioms TaoTrudgianYang2025.generatedBourgainDensityPieces_count
#print axioms TaoTrudgianYang2025.generatedEnergyClauses_count
#print axioms TaoTrudgianYang2025.generatedEnergyClauses_denominatorsPositive
#print axioms TaoTrudgianYang2025.bourgainPieceOne_eq_candidateFormula
#print axioms TaoTrudgianYang2025.bourgainPieceEight_eq_candidateFormula
#print axioms TaoTrudgianYang2025.optimizedBourgain_endpoint_agreement
#print axioms TaoTrudgianYang2025.optimizedBourgain_interval_cover
#print axioms TaoTrudgianYang2025.guthMaynard_largeValuePattern_estimate
#print axioms TaoTrudgianYang2025.guthMaynard_largeValueBound
#print axioms TaoTrudgianYang2025.largeValueExponent_le_guthMaynard
#print axioms TaoTrudgianYang2025.zetaLargeValueExponent_le_guthMaynard
#print axioms TaoTrudgianYang2025.two_mul_largeValueExponent_le_largeValueEnergyExponent
#print axioms TaoTrudgianYang2025.largeValueEnergyExponent_le_three_mul_largeValueExponent
#print axioms TaoTrudgianYang2025.two_mul_zetaLargeValueExponent_le_zetaLargeValueEnergyExponent
#print axioms TaoTrudgianYang2025.zetaLargeValueEnergyExponent_le_three_mul_zetaLargeValueExponent
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_le_localMass_mul_cube
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_perturbation_le
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_le_natCeil_mul_unit
#print axioms TaoTrudgianYang2025.four_mul_mixedApproximateAdditiveEnergyOf_le_nine_mul_sum_self
#print axioms TaoTrudgianYang2025.exists_energy_color_classes
#print axioms TaoTrudgianYang2025.zeroAdditiveEnergy_le_perturbed
#print axioms TaoTrudgianYang2025.zeroAdditiveEnergy_le_mul_perturbed_unit
#print axioms TaoTrudgianYang2025.typeIZeroCopy_exists_shifted_detector
#print axioms TaoTrudgianYang2025.typeIZero_exists_shifted_detector
#print axioms TaoTrudgianYang2025.typeIZeroCopy_shifted_unitBin_card
#print axioms TaoTrudgianYang2025.typeIZeroCopy_shifted_unitBin_card_le
#print axioms TaoTrudgianYang2025.typeIZeroAdditiveEnergy_le_shifted_detector_energy
#print axioms TaoTrudgianYang2025.typeIZeroShiftedEnergy_exists_scale_classes
#print axioms TaoTrudgianYang2025.typeIZeroShiftedEnergy_exists_separated_scale_classes
#print axioms TaoTrudgianYang2025.typeIZeroAdditiveEnergy_le_detector_scale_class_energies
#print axioms TaoTrudgianYang2025.typeIZeroAdditiveEnergy_le_separated_detector_scale_class_energies
#print axioms TaoTrudgianYang2025.unitBinRank_lt_card
#print axioms TaoTrudgianYang2025.unitBinRank_injective_on_bin
#print axioms TaoTrudgianYang2025.oneSeparated_on_boundedMultiplicityColor
#print axioms TaoTrudgianYang2025.separatedRefinementColor_base
#print axioms TaoTrudgianYang2025.separatedRefinementColor_oneSeparated
#print axioms TaoTrudgianYang2025.exists_separated_energy_color_classes
#print axioms TaoTrudgianYang2025.unitBinFinset_perturbation_card_le_natCeil
#print axioms TaoTrudgianYang2025.exists_separated_perturbed_energy_classes
#print axioms TaoTrudgianYang2025.injective_of_indexed_oneSeparated
#print axioms TaoTrudgianYang2025.image_isOneSeparated_of_indexed_oneSeparated
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_equiv
#print axioms TaoTrudgianYang2025.finsetAdditiveEnergy_image_eq
#print axioms TaoTrudgianYang2025.typeISeparatedScaleColor_index_mem
#print axioms TaoTrudgianYang2025.detectorPatternNormalization_pos
#print axioms TaoTrudgianYang2025.exists_scaledDetectorLineCoeff_bound
#print axioms TaoTrudgianYang2025.exists_detectorPatternNormalization_bound
#print axioms TaoTrudgianYang2025.exists_detectorPatternNormalization_le_const_mul_rpow
#print axioms TaoTrudgianYang2025.detectorPatternThreshold_lower_of_normalization_le
#print axioms TaoTrudgianYang2025.log_height_le_admissible_scale_rpow
#print axioms TaoTrudgianYang2025.detectorPatternThreshold_lower_admissible
#print axioms TaoTrudgianYang2025.normalizedDetectorPatternCoeff_norm_le_one
#print axioms TaoTrudgianYang2025.normalizedDetectorPattern_sum_eq
#print axioms TaoTrudgianYang2025.indexedDetectorLargeValuePattern_energy_eq
#print axioms TaoTrudgianYang2025.exists_typeIDetectorClassPattern
#print axioms TaoTrudgianYang2025.typeIDetectorClass_energy_eq_zero_or_exists_pattern
#print axioms TaoTrudgianYang2025.weightedCopy_card
#print axioms TaoTrudgianYang2025.weightedCopy_unitBin_card
#print axioms TaoTrudgianYang2025.classicalSlabZeroCopy_card
#print axioms TaoTrudgianYang2025.classicalSlabZeroCopy_shifted_unitBin_card
#print axioms TaoTrudgianYang2025.classicalSlabZeroCopy_shifted_unitBin_card_le
#print axioms TaoTrudgianYang2025.classicalSlabZeroEnergy_le_shifted_unit
#print axioms TaoTrudgianYang2025.extendClassicalSlabShift_apply
#print axioms TaoTrudgianYang2025.classicalZero_exists_shifted_branch_scale
#print axioms TaoTrudgianYang2025.classicalSlab_exists_shifted_branch_scale
#print axioms TaoTrudgianYang2025.classicalSlabZeroEnergy_le_separated_branch_scale_class_energies
#print axioms TaoTrudgianYang2025.classicalTypeI_sourceThreshold_inv
#print axioms TaoTrudgianYang2025.sum_closedDyadicCoeff_eq_dirichletPoly
#print axioms TaoTrudgianYang2025.indexedDirichletLargeValuePattern_energy_eq
#print axioms TaoTrudgianYang2025.norm_normalizedClassicalZetaLongLineCoeff_le_one
#print axioms TaoTrudgianYang2025.dirichletPoly_normalizedClassicalZetaLongLineCoeff
#print axioms TaoTrudgianYang2025.exists_classicalTypeIWeightedClassPattern
#print axioms TaoTrudgianYang2025.exists_large_typeISourceSmoothBlock_of_sharp_large
#print axioms TaoTrudgianYang2025.chosenTypeISourceSmoothBlock_large
#print axioms TaoTrudgianYang2025.dirichletPoly_classicalZetaLongLineCoeff_eq_active_sum
#print axioms TaoTrudgianYang2025.card_classicalTypeI_activeInterval_le
#print axioms TaoTrudgianYang2025.classicalTypeI_scale_activeCard_le
#print axioms TaoTrudgianYang2025.norm_classicalTypeICoefficientOneCoeff_le_one
#print axioms TaoTrudgianYang2025.dirichletPoly_classicalTypeICoefficientOneCoeff_eq_active_sum
#print axioms TaoTrudgianYang2025.indexedClassicalTypeICoefficientOnePattern_energy_eq
#print axioms TaoTrudgianYang2025.perturbedOrdinate_mem_expandedInterval
#print axioms TaoTrudgianYang2025.classicalSlab_expanded_height_in_rpow_window
#print axioms TaoTrudgianYang2025.classicalTypeILogProfile_scale_identity
#print axioms TaoTrudgianYang2025.dirichletPoly_classicalZetaLongLineCoeff_fourierDeweight
#print axioms TaoTrudgianYang2025.classicalTypeIFourierL1_pos
#print axioms TaoTrudgianYang2025.exists_large_coefficientOne_shift_of_classicalTypeI
#print axioms TaoTrudgianYang2025.typeISourceSmoothBlock_fourierDeweight_restricted
#print axioms TaoTrudgianYang2025.typeISourceSmoothBlockFourierL1_pos
#print axioms TaoTrudgianYang2025.integral_norm_fourier_typeILogWeight_le
#print axioms TaoTrudgianYang2025.integral_norm_fourier_schwartz_compl_Icc_le
#print axioms TaoTrudgianYang2025.integral_norm_fourier_schwartz_compl_Icc_le_order
#print axioms TaoTrudgianYang2025.norm_classicalTypeI_fourier_tail_integral_le_order
#print axioms TaoTrudgianYang2025.exists_bounded_coefficientOne_shift_of_classicalTypeI
#print axioms TaoTrudgianYang2025.exists_classicalTypeI_boundedOrdinate_family
#print axioms TaoTrudgianYang2025.classicalTypeIFourierRadius_pos
#print axioms TaoTrudgianYang2025.classicalTypeIFourierRadius_tail_numeric
#print axioms TaoTrudgianYang2025.classicalTypeIFourierRadius_le_rpow_of_base_growth
#print axioms TaoTrudgianYang2025.classicalTypeIFourierRadius_source_base_le
#print axioms TaoTrudgianYang2025.classicalTypeIFourierRadius_sharpCutoff_source_base_le
#print axioms TaoTrudgianYang2025.eventually_one_add_const_mul_log_le_rpow
#print axioms TaoTrudgianYang2025.eventually_classicalTypeIFourier_clog_loss_le_rpow
#print axioms TaoTrudgianYang2025.eventually_classicalTypeIFourierRadius_sharpCutoff_base_le_rpow
#print axioms TaoTrudgianYang2025.eventually_classicalTypeIFourierRadius_sharpCutoff_le_rpow
#print axioms TaoTrudgianYang2025.exists_classicalTypeIFourier_order
#print axioms TaoTrudgianYang2025.exists_order_eventually_classicalTypeIFourierRadius_sharpCutoff_le_rpow
#print axioms TaoTrudgianYang2025.exists_explicitly_bounded_coefficientOne_shift_of_classicalTypeI
#print axioms TaoTrudgianYang2025.exists_classicalTypeI_explicitBoundedOrdinate_family
#print axioms TaoTrudgianYang2025.exists_separated_classicalTypeI_explicitFourier_energy_classes
#print axioms TaoTrudgianYang2025.exists_classicalTypeI_explicitFourier_patterns
#print axioms TaoTrudgianYang2025.IsLargeValueEnergyBound.classicalTypeI_explicitFourier_energy_transfer
#print axioms TaoTrudgianYang2025.classicalTypeI_sharpCutoff_clog_le_const_mul_log
#print axioms TaoTrudgianYang2025.eventually_const_mul_classicalTypeI_clog_le_rpow
#print axioms TaoTrudgianYang2025.classicalTypeI_normalized_sourceThreshold_eq
#print axioms TaoTrudgianYang2025.eventually_classicalTypeI_normalized_sourceThreshold_lower
#print axioms TaoTrudgianYang2025.indexedClassicalTypeIZetaPattern_energy_eq
#print axioms TaoTrudgianYang2025.classicalTypeIHeight_bounds
#print axioms TaoTrudgianYang2025.classicalTypeIHeightColor_mem
#print axioms TaoTrudgianYang2025.IsZetaLargeValueEnergyBound.classicalTypeI_expanded_slab_bound
#print axioms TaoTrudgianYang2025.IsZetaLargeValueEnergyBound.classicalTypeI_fourier_energy_transfer
#print axioms TaoTrudgianYang2025.classicalTypeIFourierEnergyLoss_le
#print axioms TaoTrudgianYang2025.eventually_classicalTypeIFourierEnergyLoss_le_rpow
#print axioms TaoTrudgianYang2025.eventually_classicalTypeI_displacements_fit
#print axioms TaoTrudgianYang2025.IsZetaLargeValueEnergyBound.classicalTypeI_source_energy_bound
#print axioms TaoTrudgianYang2025.eventually_classicalTypeI_sourceScale_lower
#print axioms TaoTrudgianYang2025.IsZetaLargeValueEnergyBound.classicalTypeI_source_class_energy_bound
#print axioms TaoTrudgianYang2025.eventually_classicalTypeI_height_window_of_logb_tendsto
#print axioms TaoTrudgianYang2025.exists_classicalTypeI_scale_subsequence
#print axioms TaoTrudgianYang2025.classicalTypeI_source_large_scale_le_six_mul
#print axioms TaoTrudgianYang2025.exists_classicalTypeI_source_scale_subsequence
#print axioms TaoTrudgianYang2025.norm_typeILogWeight_fourier_tail_integral_le
#print axioms TaoTrudgianYang2025.typeISourceFourierRadius_pos
#print axioms TaoTrudgianYang2025.norm_typeILogWeight_fourier_tail_integral_le_half
#print axioms TaoTrudgianYang2025.exists_large_coefficientOne_shift_of_typeISourceSmoothBlock
#print axioms TaoTrudgianYang2025.exists_bounded_coefficientOne_shift_of_typeISourceSmoothBlock
#print axioms TaoTrudgianYang2025.exists_explicitly_bounded_coefficientOne_shift_of_typeISourceSmoothBlock
#print axioms TaoTrudgianYang2025.typeISourceFourier_uniform_tail_bound
#print axioms TaoTrudgianYang2025.boundedTypeISourceFourierFrequency_mem_and_large
#print axioms TaoTrudgianYang2025.boundedTypeISourceFourierOrdinate_displacement_le
#print axioms TaoTrudgianYang2025.boundedTypeISourceFourierOrdinate_large
#print axioms TaoTrudgianYang2025.explicitBoundedTypeISourceFourierOrdinate_displacement_le
#print axioms TaoTrudgianYang2025.explicitBoundedTypeISourceFourierOrdinate_large
#print axioms TaoTrudgianYang2025.typeISourceSmoothBlock_energy_le_boundedFourierOrdinate_energy
#print axioms TaoTrudgianYang2025.typeISourceSmoothBlock_energy_le_explicitBoundedFourierOrdinate_energy
#print axioms TaoTrudgianYang2025.exists_separated_boundedTypeISourceFourier_energy_classes
#print axioms TaoTrudgianYang2025.exists_separated_explicitTypeISourceFourier_energy_classes
#print axioms TaoTrudgianYang2025.exists_large_coefficientOne_shift_of_chosenTypeISourceSmoothBlock
#print axioms TaoTrudgianYang2025.exists_typeISourceSmoothBlock_energy_classes
#print axioms TaoTrudgianYang2025.exists_classicalTypeISourceSmoothBlock_energy_classes
#print axioms TaoTrudgianYang2025.exists_classicalTypeIIClassPattern
#print axioms TaoTrudgianYang2025.exists_classicalTypeIIClassPattern_native
#print axioms TaoTrudgianYang2025.zeroCopy_local_card_eq_weighted_sum
#print axioms TaoTrudgianYang2025.IsZeroDensityEnergyBound.toZeroDensityBound_half
#print axioms TaoTrudgianYang2025.IsZeroDensityBound.toEnergyBound_four_mul
#print axioms TaoTrudgianYang2025.two_mul_zeroDensityExponent_le_zeroDensityEnergyExponent
#print axioms TaoTrudgianYang2025.zeroDensityEnergyExponent_le_four_mul_zeroDensityExponent
#print axioms TaoTrudgianYang2025.zeroAdditiveEnergy_le_globalCap_mul_cube
#print axioms TaoTrudgianYang2025.globalMultiplicityCap_le_rpow
#print axioms TaoTrudgianYang2025.IsZeroDensityBound.toEnergyBound_three_mul
#print axioms TaoTrudgianYang2025.zeroDensityEnergyExponent_le_three_mul_zeroDensityExponent
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.two_mul_rho_le_rhoStar
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.rhoStar_le_three_mul_rho
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.rho_le_tau
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.rhoStar_le_of_energyBound
#print axioms TaoTrudgianYang2025.InZetaLargeValueEnergyRegion.rhoStar_le_of_energyBound
#print axioms TaoTrudgianYang2025.largeValueEnergyRegionSupremum_le_largeValueEnergyExponent
#print axioms TaoTrudgianYang2025.zetaLargeValueEnergyRegionSupremum_le_zetaLargeValueEnergyExponent
#print axioms TaoTrudgianYang2025.energyRegion_exists_rhoStar_gt_of_not_bound
#print axioms TaoTrudgianYang2025.zetaEnergyRegion_exists_rhoStar_gt_of_not_bound
#print axioms TaoTrudgianYang2025.largeValueEnergyExponent_eq_regionSupremum
#print axioms TaoTrudgianYang2025.zetaLargeValueEnergyExponent_eq_regionSupremum
#print axioms TaoTrudgianYang2025.inLargeValueEnergyRegionAsymptotic_iff
#print axioms TaoTrudgianYang2025.inZetaLargeValueEnergyRegionAsymptotic_iff
#print axioms TaoTrudgianYang2025.isLargeValueEnergyBoundAsymptotic_iff
#print axioms TaoTrudgianYang2025.isZetaLargeValueEnergyBoundAsymptotic_iff
#print axioms TaoTrudgianYang2025.isZeroDensityEnergyBoundAsymptotic_iff

#print axioms TaoTrudgianYang2025.zetaEnergyBound_uniform_near_logScale_interval
#print axioms TaoTrudgianYang2025.zetaEnergyBound_uniform_on_logScale_interval
#print axioms TaoTrudgianYang2025.exists_mem_Icc_abs_sub_le_of_bounds
#print axioms TaoTrudgianYang2025.eventually_classicalTypeI_logScale_near_interval
#print axioms TaoTrudgianYang2025.classicalTypeI_uniform_expanded_slab_bound
#print axioms TaoTrudgianYang2025.classicalTypeI_uniform_fourier_energy_transfer
#print axioms TaoTrudgianYang2025.classicalTypeI_uniform_source_energy_bound
#print axioms TaoTrudgianYang2025.classicalTypeI_uniform_source_class_energy_bound
#print axioms TaoTrudgianYang2025.largeValueEnergyBound_uniform_near_logScale_interval
#print axioms TaoTrudgianYang2025.classicalTypeII_normalized_sourceThreshold_eq
#print axioms TaoTrudgianYang2025.eventually_classicalTypeII_normalized_sourceThreshold_lower
#print axioms TaoTrudgianYang2025.eventually_classicalTypeII_logScale_near_interval
#print axioms TaoTrudgianYang2025.classicalTypeII_sourceScale_upper
#print axioms TaoTrudgianYang2025.classicalTypeII_uniform_source_class_energy_bound
#print axioms TaoTrudgianYang2025.eventually_classicalSlabEnergyLoss_le_const_mul_rpow
#print axioms TaoTrudgianYang2025.classicalSlabZeroEnergy_bound_of_uniform_energy_bounds
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_comp_injective_le
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_comp_equiv
#print axioms TaoTrudgianYang2025.approximateAdditiveEnergyOf_neg
#print axioms TaoTrudgianYang2025.weightedCopyInclusion_injective
#print axioms TaoTrudgianYang2025.weightedCopy_energy_mono
#print axioms TaoTrudgianYang2025.weightedCopy_family_energy_le
#print axioms TaoTrudgianYang2025.zeroCopy_family_energy_le_classicalSlab
#print axioms TaoTrudgianYang2025.zeroCopy_family_energy_le_classicalSlab_of_neg
#print axioms TaoTrudgianYang2025.zeroCopy_family_energy_le_low_height
#print axioms TaoTrudgianYang2025.exists_bounded_dyadic_slab
#print axioms TaoTrudgianYang2025.exists_zeroDyadicColor
#print axioms TaoTrudgianYang2025.zeroAdditiveEnergy_le_dyadicSlabEnergy
#print axioms TaoTrudgianYang2025.eventually_zeroDyadicColor_loss_le_rpow
#print axioms TaoTrudgianYang2025.zeroAdditiveEnergy_bound_of_eventual_slab_bound
#print axioms TaoTrudgianYang2025.isZeroDensityEnergyBound_of_uniform_energy_bounds
#print axioms TaoTrudgianYang2025.isLargeValueEnergyBound_of_exponent_le
#print axioms TaoTrudgianYang2025.isZetaLargeValueEnergyBound_of_exponent_le
#print axioms TaoTrudgianYang2025.singletonLargeValuePattern_energy
#print axioms TaoTrudgianYang2025.IsLargeValueEnergyBound.nonneg
#print axioms TaoTrudgianYang2025.largeValueEnergyExponent_nonneg
#print axioms TaoTrudgianYang2025.zeroEnergyTransferEnvelope_nonneg
#print axioms TaoTrudgianYang2025.zeroDensityEnergyExponent_le_sup_limsup
#print axioms TaoTrudgianYang2025.singletonLargeValuePattern_doubleZetaSum
#print axioms TaoTrudgianYang2025.singleton_mem_largeValueEnergyRegion
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.two_le_s
#print axioms TaoTrudgianYang2025.energyPowering_source_counterexample
#print axioms TaoTrudgianYang2025.cardinalityEnergyPoweringWitnesses_iff
#print axioms TaoTrudgianYang2025.cardinalityEnergyPoweringWitnesses_one
#print axioms TaoTrudgianYang2025.singleton_cardinalityEnergyPoweringWitnesses
#print axioms TaoTrudgianYang2025.exists_energy_preserving_color
#print axioms TaoTrudgianYang2025.CardinalityEnergyPoweringWitnesses.cardinality_bound
#print axioms TaoTrudgianYang2025.CardinalityEnergyPoweringWitnesses.energy_relation
#print axioms TaoTrudgianYang2025.CardinalityEnergyPoweringWitnesses.monotone_constraints
#print axioms TaoTrudgianYang2025.heathBrownEnergyRHS_mono_card
#print axioms TaoTrudgianYang2025.CardinalityEnergyPoweringWitnesses.heathBrown_relation
#print axioms TaoTrudgianYang2025.LargeValuePattern.halfOpen_large
#print axioms TaoTrudgianYang2025.closedSupportPolynomial_eq_halfOpen
#print axioms TaoTrudgianYang2025.LargeValuePattern.ofHalfOpenBlock
#print axioms TaoTrudgianYang2025.exists_energy_preserving_finset_color
#print axioms TaoTrudgianYang2025.exists_normalized_powered_pattern_partition
#print axioms TaoTrudgianYang2025.finsetAdditiveEnergy_mono
#print axioms TaoTrudgianYang2025.NormalizedPoweredSubpattern.card_le
#print axioms TaoTrudgianYang2025.NormalizedPoweredSubpattern.energy_le
#print axioms TaoTrudgianYang2025.NormalizedPoweredSubpattern.real_scale_eq
#print axioms TaoTrudgianYang2025.NormalizedPoweredSubpattern.scale_bounds
#print axioms TaoTrudgianYang2025.NormalizedPoweredSubpattern.log_scale_eq
#print axioms TaoTrudgianYang2025.exists_normalized_powered_subpatterns
#print axioms TaoTrudgianYang2025.tendsto_logb_of_power_sandwich
#print axioms TaoTrudgianYang2025.tendsto_logb_rebase
#print axioms TaoTrudgianYang2025.tendsto_logb_of_const_mul_sandwich
#print axioms TaoTrudgianYang2025.tendsto_logb_sub_one
#print axioms TaoTrudgianYang2025.normalizedPoweredSubpattern_scale_log_limit
#print axioms TaoTrudgianYang2025.NormalizedPoweredSubpattern.log_value_eq
#print axioms TaoTrudgianYang2025.normalizedPoweredSubpattern_value_log_limit
#print axioms TaoTrudgianYang2025.poweringAccuracy_pos
#print axioms TaoTrudgianYang2025.poweringAccuracy_le
#print axioms TaoTrudgianYang2025.poweringAccuracy_tendsto
#print axioms TaoTrudgianYang2025.exists_powering_input_family
#print axioms TaoTrudgianYang2025.PoweringInputFamily.powered_time_value_limits
#print axioms TaoTrudgianYang2025.energyRegion_subsequence_of_log_limits
#print axioms TaoTrudgianYang2025.correctedCardinalityEnergyPowering
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.corrected_powering
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.powered_heathBrown_relation
#print axioms TaoTrudgianYang2025.IsLargeValueEnergyBound.of_powered
#print axioms TaoTrudgianYang2025.largeValueEnergyExponent_le_of_powered_real_bound
#print axioms TaoTrudgianYang2025.exists_power_height_in_Icc
#print axioms TaoTrudgianYang2025.isLargeValueEnergyBound_of_bounded_power_range
#print axioms TaoTrudgianYang2025.isZeroDensityEnergyBound_of_bounded_energy_ranges
#print axioms TaoTrudgianYang2025.finsetAdditiveEnergy_eq_native
#print axioms TaoTrudgianYang2025.LargeValuePattern.reflectedOrdinates_energy
#print axioms TaoTrudgianYang2025.LargeValuePattern.reflectedHalfOpenPolynomial_eq
#print axioms TaoTrudgianYang2025.LargeValuePattern.reflectedHalfOpen_large
#print axioms TaoTrudgianYang2025.heathBrown_largeValuePattern_energy_squared
#print axioms TaoTrudgianYang2025.tendsto_logb_mul
#print axioms TaoTrudgianYang2025.tendsto_logb_pow
#print axioms TaoTrudgianYang2025.tendsto_logb_rpow
#print axioms TaoTrudgianYang2025.tendsto_logb_max
#print axioms TaoTrudgianYang2025.tendsto_logb_add
#print axioms TaoTrudgianYang2025.heathBrownEnergyRHS_max_one
#print axioms TaoTrudgianYang2025.PoweringInputFamily.heathBrown_energy_padded
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.heathBrown_relation
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.heathBrown_relation
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.heathBrown_powered
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.heathBrown_small_height
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.heathBrown_small_height_powered
#print axioms TaoTrudgianYang2025.tendsto_logb_div
#print axioms TaoTrudgianYang2025.tendsto_logb_min
#print axioms TaoTrudgianYang2025.classical_largeValuePattern_estimate
#print axioms TaoTrudgianYang2025.classicalLargeValueExponent_max_one
#print axioms TaoTrudgianYang2025.PoweringInputFamily.classical_cardinality
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.classical_cardinality
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.huxley_cardinality
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.huxley_cardinality_powered
#print axioms TaoTrudgianYang2025.exists_heathBrownEnergyBranch
#print axioms TaoTrudgianYang2025.heathBrownEnergyBranch_mono_card
#print axioms TaoTrudgianYang2025.energyClauseOneGeneralRate_lower_piece
#print axioms TaoTrudgianYang2025.energyClauseOneGeneralRate_upper_piece
#print axioms TaoTrudgianYang2025.energyClauseOneGeneral_branch_bound
#print axioms TaoTrudgianYang2025.energyClauseOneGeneral_power_cover
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.energyClauseOneGeneral_cardinality_cap
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.energyClauseOneGeneral
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.energyClauseOneGeneral_lower_piece
#print axioms TaoTrudgianYang2025.InLargeValueEnergyRegion.energyClauseOneGeneral_upper_piece
#print axioms TaoTrudgianYang2025.energyClauseOneGeneral_uniform_bound
#print axioms TaoTrudgianYang2025.energyClauseOneGeneral_high_height_bound
#print axioms TaoTrudgianYang2025.energyClauseOnePublicRate_pos
#print axioms TaoTrudgianYang2025.energyClauseOneGeneralRate_le_public
#print axioms TaoTrudgianYang2025.energyClauseOneGeneral_public_rate_bound
#print axioms TaoTrudgianYang2025.energyClauseOne_of_zeta_range
#print axioms TaoTrudgianYang2025.energyClauseOneZetaRate_lower_piece
#print axioms TaoTrudgianYang2025.energyClauseOneZetaRate_upper_piece
#print axioms TaoTrudgianYang2025.energyClauseOneZetaRate_slope
#print axioms TaoTrudgianYang2025.energyClauseOneZeta_branch_bound
#print axioms TaoTrudgianYang2025.InCardinalityEnergyRegion.energyClauseOneZeta_cardinality_cap
#print axioms TaoTrudgianYang2025.InZetaLargeValueEnergyRegion.energyClauseOneZeta_of_twelfth_cardinality
#print axioms TaoTrudgianYang2025.energyClauseOneZetaRate_le_public
#print axioms TaoTrudgianYang2025.InZetaLargeValueEnergyRegion.rho_le_of_largeValueBound
#print axioms TaoTrudgianYang2025.energyClauseOneZeta_uniform_bound_of_twelfth
#print axioms TaoTrudgianYang2025.energyClauseOneZeta_public_rate_bound_of_twelfth
#print axioms TaoTrudgianYang2025.energyClauseOne_of_twelfth_and_short_zeta
#print axioms TaoTrudgianYang2025.zetaMomentKernel_pos
#print axioms TaoTrudgianYang2025.continuous_zetaMomentKernel
#print axioms TaoTrudgianYang2025.sum_zetaMomentKernel_le_harmonic
#print axioms TaoTrudgianYang2025.sum_zetaMomentKernel_le_log
#print axioms TaoTrudgianYang2025.twelfth_tangent_bound
#print axioms TaoTrudgianYang2025.integral_zetaMomentKernel
#print axioms TaoTrudgianYang2025.integral_weighted_twelfth
#print axioms TaoTrudgianYang2025.zetaMomentLogLoss_pos
#print axioms TaoTrudgianYang2025.sum_zetaMomentKernel_on_source_window
#print axioms TaoTrudgianYang2025.integral_zetaMomentKernel_source_mass
#print axioms TaoTrudgianYang2025.sum_convolution_twelfth_le_moment
#print axioms TaoTrudgianYang2025.continuous_zetaMomentCriticalNorm
#print axioms TaoTrudgianYang2025.sum_zetaMomentConvolution_twelfth
#print axioms TaoTrudgianYang2025.zetaMomentConvolution_largeValues
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.twelfth_cardinality_of_convolution
#print axioms TaoTrudgianYang2025.zetaMomentLogLoss_le_seven_log
#print axioms TaoTrudgianYang2025.eventually_zetaMomentLogLoss_pow_le_rpow
#print axioms TaoTrudgianYang2025.zetaTwelfthMoment_le_three_dyadic
#print axioms TaoTrudgianYang2025.zetaTwelfthMoment_le_of_dyadic
#print axioms TaoTrudgianYang2025.eventually_zetaMomentLoss_twelfth_of_dyadic
#print axioms TaoTrudgianYang2025.zetaPattern_twelfth_cardinality_of_dyadic_and_convolution

#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_nonneg
#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_le_one
#print axioms TaoTrudgianYang2025.contDiff_zetaIntervalCutoff
#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_eq_one
#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_eq_zero_left
#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_eq_zero_right
#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_nat
#print axioms TaoTrudgianYang2025.support_zetaIntervalCutoff
#print axioms TaoTrudgianYang2025.zetaIntervalCutoffTest
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.polynomial_eq_active_sum
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.active_left_pos
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.polynomial_eq_cutoff_tsum
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.active_nonempty_of_mem_ordinates
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.active_interval_bounds
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_support_in_scale
#print axioms TaoTrudgianYang2025.norm_zetaMellinTerm
#print axioms TaoTrudgianYang2025.integrable_zetaMellinTerm
#print axioms TaoTrudgianYang2025.integral_norm_zetaMellinTerm
#print axioms TaoTrudgianYang2025.summable_integral_norm_zetaMellinTerm
#print axioms TaoTrudgianYang2025.zetaMellinTerm_eq_phase_mul
#print axioms TaoTrudgianYang2025.integral_zetaMellinTerm_eq
#print axioms TaoTrudgianYang2025.smooth_dirichlet_sum_eq_zeta_mellin
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.polynomial_eq_zeta_mellin
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.exists_zeta_mellin_large
#print axioms TaoTrudgianYang2025.differentiable_zetaMellinNumerator
#print axioms TaoTrudgianYang2025.zetaMellinNumerator_at_pole
#print axioms TaoTrudgianYang2025.zetaMellinIntegrand_eq_quotient
#print axioms TaoTrudgianYang2025.zetaMellin_finite_rectangle
#print axioms TaoTrudgianYang2025.norm_zeta_mellin_boundary
#print axioms TaoTrudgianYang2025.integrable_zetaMellin_boundary
#print axioms TaoTrudgianYang2025.exists_zetaMellin_strip_tail_bound
#print axioms TaoTrudgianYang2025.zetaMellin_horizontal_limits
#print axioms TaoTrudgianYang2025.zetaMellin_vertical_shift
#print axioms TaoTrudgianYang2025.zetaMellin_verticalIntegral_eq
#print axioms TaoTrudgianYang2025.smooth_dirichlet_sum_eq_critical_zeta_mellin
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.polynomial_eq_critical_zeta_mellin
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.exists_critical_zeta_mellin_large

#print axioms TaoTrudgianYang2025.zetaIntervalCutoff_eq_transition_sum
#print axioms TaoTrudgianYang2025.iteratedDeriv_smoothTransition_affine
#print axioms TaoTrudgianYang2025.iteratedDeriv_zetaIntervalCutoff
#print axioms TaoTrudgianYang2025.support_iteratedDeriv_smoothTransition
#print axioms TaoTrudgianYang2025.integrable_iteratedDeriv_smoothTransition
#print axioms TaoTrudgianYang2025.zetaCutoffDerivativeMass_nonneg
#print axioms TaoTrudgianYang2025.integrable_iteratedDeriv_zetaIntervalCutoff
#print axioms TaoTrudgianYang2025.integral_norm_iteratedDeriv_zetaIntervalCutoff_le
#print axioms TaoTrudgianYang2025.iteratedDeriv_complex_zetaIntervalCutoff
#print axioms TaoTrudgianYang2025.integral_norm_complex_cutoff_deriv_le
#print axioms TaoTrudgianYang2025.support_iteratedDeriv_subset_original
#print axioms TaoTrudgianYang2025.mellinIteratedDerivativeTest
#print axioms TaoTrudgianYang2025.mellinConvergent_complex_of_test
#print axioms TaoTrudgianYang2025.mellin_derivative_recurrence
#print axioms TaoTrudgianYang2025.mellin_iteratedDeriv_norm
#print axioms TaoTrudgianYang2025.norm_mellin_le_upper_mass
#print axioms TaoTrudgianYang2025.one_add_abs_le_three_mellin_factor
#print axioms TaoTrudgianYang2025.mellin_weighted_norm_le_derivative
#print axioms TaoTrudgianYang2025.zetaCutoffMellinConstant_pos
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_mellin_weighted_bound
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_mellin_bound
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_critical_mellin_kernel
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_mellin_residue_bound
#print axioms TaoTrudgianYang2025.zetaCutoffCriticalIntegrand_eq
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.integrable_cutoff_critical_integrand
#print axioms TaoTrudgianYang2025.zetaMellinSourceWindow_compl_subset
#print axioms TaoTrudgianYang2025.zetaMellin_far_abs
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_critical_integrand_far_bound
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_critical_far_integral
#print axioms TaoTrudgianYang2025.integral_zetaMellinSourceWindow_convolution
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.cutoff_critical_near_integral
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.polynomial_norm_le_convolution_and_errors
#print axioms TaoTrudgianYang2025.zetaPerronError_pos
#print axioms TaoTrudgianYang2025.zetaPerronConstant_pos
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.perron_entry
#print axioms TaoTrudgianYang2025.exists_zetaPerron_uniform_threshold
#print axioms TaoTrudgianYang2025.ZetaLargeValuePattern.twelfth_cardinality_of_perron
#print axioms TaoTrudgianYang2025.zetaTwelfth_largeValueBound_of_dyadic
#print axioms TaoTrudgianYang2025.energyClauseOne_of_dyadic_moment_and_short_zeta

#eval runBootstrapDependencyAudit

end TaoTrudgianYang2025.Audit
