-- This file is generated by Tools/generate_certificates.py.
-- Source: ANTEDB commit 9953003a48f46fe8075ccf9534321f98f656032e.
-- Do not edit by hand.

import TaoTrudgianYang2025.ExponentPair

namespace TaoTrudgianYang2025

/-- The four output points extracted from the frozen paper-time driver. -/
def generatedExponentPairCoordinates : List (ℚ × ℚ) := [
  (89 / 1282, 997 / 1282),
  (652397 / 9713986, 7599781 / 9713986),
  (10769 / 351096, 609317 / 702192),
  (89 / 3478, 15327 / 17390)
]

theorem generatedExponentPairCoordinates_count :
    generatedExponentPairCoordinates.length = 4 := by
  rfl

end TaoTrudgianYang2025
