import PrimeShell.PrimeTerm

namespace PrimeShell

noncomputable section

open Zeta23 Zeta23.PrimeSide

/-- The already-controlled lower prime block.  The cutoff is a physical
prime scale, not a window-profile coordinate. -/
def primeLowDensity (Y : ℝ) : ℝ → ℝ := Zeta23.PX Y

/-- The additive prime shell between the lower cutoff `Y` and the full
cutoff `X`.  This is the source-faithful meaning of a Prime Shell: it is a
piece of the prime density in the bilinear form `Mform`, not a zero in the
strictly positive `WindowProfile`. -/
def primeHighShellDensity (Y X : ℝ) : ℝ → ℝ :=
  Zeta23.PX X - Zeta23.PX Y

theorem primeLowDensity_continuous (Y : ℝ) :
    Continuous (primeLowDensity Y) :=
  PX_continuous Y

theorem primeHighShellDensity_continuous (Y X : ℝ) :
    Continuous (primeHighShellDensity Y X) :=
  (PX_continuous X).sub (PX_continuous Y)

/-- Exact pointwise source entry: the full prime polynomial is the sum of
the lower block and the additive high shell. -/
theorem PX_eq_primeLowDensity_add_primeHighShellDensity (Y X : ℝ) :
    Zeta23.PX X = primeLowDensity Y + primeHighShellDensity Y X := by
  funext τ
  simp [primeLowDensity, primeHighShellDensity]

/-- The four exact bilinear terms generated by the additive shell.  No
support estimate, arithmetic hypothesis, or asymptotic error is hidden in
this definition. -/
structure PrimeShellTraceTerms where
  lowLow : ℝ
  lowHigh : ℝ
  highLow : ℝ
  highHigh : ℝ

def primeShellTraceTerms (Φ : ℝ → ℝ) (T Y X : ℝ) : PrimeShellTraceTerms where
  lowLow := Mform Φ T (primeLowDensity Y) (primeLowDensity Y)
  lowHigh := Mform Φ T (primeLowDensity Y) (primeHighShellDensity Y X)
  highLow := Mform Φ T (primeHighShellDensity Y X) (primeLowDensity Y)
  highHigh := Mform Φ T (primeHighShellDensity Y X) (primeHighShellDensity Y X)

/-- Exact F2 source decomposition.  It exposes low/low, low/high,
high/low and high/high terms while leaving the pinned test-window profile
strictly positive. -/
theorem primePrime_eq_four_additive_shell_terms
    (hΦ : Continuous Φ) (T Y X : ℝ) :
    Mform Φ T (Zeta23.PX X) (Zeta23.PX X) =
      (primeShellTraceTerms Φ T Y X).lowLow +
      (primeShellTraceTerms Φ T Y X).lowHigh +
      (primeShellTraceTerms Φ T Y X).highLow +
      (primeShellTraceTerms Φ T Y X).highHigh := by
  rw [PX_eq_primeLowDensity_add_primeHighShellDensity Y X]
  rw [Mform_add_left hΦ (primeLowDensity_continuous Y)
      (primeHighShellDensity_continuous Y X)
      ((primeLowDensity_continuous Y).add
        (primeHighShellDensity_continuous Y X))]
  rw [Mform_add_right hΦ (primeLowDensity_continuous Y)
      (primeHighShellDensity_continuous Y X)
      (primeLowDensity_continuous Y)]
  rw [Mform_add_right hΦ (primeLowDensity_continuous Y)
      (primeHighShellDensity_continuous Y X)
      (primeHighShellDensity_continuous Y X)]
  simp only [primeShellTraceTerms]
  ring

/-- With an even source kernel the two mixed terms agree, but both remain
separately accessible in `primeShellTraceTerms`. -/
theorem primeShellTraceTerms_lowHigh_eq_highLow
    (hΦeven : ∀ r, Φ (-r) = Φ r) (T Y X : ℝ) :
    (primeShellTraceTerms Φ T Y X).lowHigh =
      (primeShellTraceTerms Φ T Y X).highLow := by
  exact Mform_comm hΦeven _ _

end

end PrimeShell
