import PrimeShell.MRTInterface
import Zeta23.XiPrime.ExplicitFormula.PrimeTermJ
import Zeta23.XiPrime.PrimeSide.Density
import Zeta23.XiPrime.Coeff.MainTerm.Squarefree

namespace PrimeShell

noncomputable section

open Zeta23 Zeta23.PrimeSide Zeta23.XiPrime

/-- The non-von-Mangoldt part of the actual `xiCoeff` sequence.  Keeping
this as `xiCoeff + Λ` matches the released explicit-formula bridge
literally and avoids silently replacing the xi-prime problem by the
root-zeta problem. -/
def xiPrimeCorrectionCoeff (LambdaStar : ℂ) (N : ℕ) : ℂ :=
  xiCoeff LambdaStar N + ((ArithmeticFunction.vonMangoldt N : ℝ) : ℂ)

theorem xiCoeff_eq_negLambda_add_correction
    (LambdaStar : ℂ) (N : ℕ) :
    xiCoeff LambdaStar N =
      -((ArithmeticFunction.vonMangoldt N : ℝ) : ℂ) +
        xiPrimeCorrectionCoeff LambdaStar N := by
  unfold xiPrimeCorrectionCoeff
  ring

theorem xiPrimeCorrectionCoeff_prime
    {p : ℕ} (hp : p.Prime) (LambdaStar : ℂ) :
    xiPrimeCorrectionCoeff LambdaStar p =
      LambdaStar⁻¹ * (Real.log p : ℂ) ^ 2 := by
  unfold xiPrimeCorrectionCoeff
  rw [xiCoeff_prime hp, ArithmeticFunction.vonMangoldt_apply_prime hp]
  ring

/-- The xi-prime correction is genuinely present already on primes; an
MRT theorem for `Λ·Λ` alone therefore does not, by definitional
specialization, prove the exact xi-prime coefficient correlation. -/
theorem xiPrimeCorrectionCoeff_two_ne_zero
    {LambdaStar : ℂ} (hLambdaStar : LambdaStar ≠ 0) :
    xiPrimeCorrectionCoeff LambdaStar 2 ≠ 0 := by
  rw [xiPrimeCorrectionCoeff_prime Nat.prime_two]
  exact mul_ne_zero (inv_ne_zero hLambdaStar) (pow_ne_zero 2 (by
    exact Complex.ofReal_ne_zero.mpr
      (ne_of_gt (Real.log_pos (by norm_num : (1 : ℝ) < 2)))))

/-- Prime-and-pole part of the actual xi-prime density, with the smooth
archimedean density `mu` omitted. -/
def xiPrimeArithmeticDensity (X : ℝ) (LambdaStar : ℂ) (tau : ℝ) : ℝ :=
  PiX X tau + Pc X (xiCoeff LambdaStar) tau

/-- Exact source-entry decomposition of the actual xi-prime arithmetic
density into the pole term, the root-zeta `-Λ` term, and the remaining
xi coefficient term. -/
theorem xiPrimeArithmeticDensity_eq
    (X : ℝ) (LambdaStar : ℂ) (tau : ℝ) :
    xiPrimeArithmeticDensity X LambdaStar tau =
      PX X tau + PiX X tau + Pc X (xiPrimeCorrectionCoeff LambdaStar) tau := by
  unfold xiPrimeArithmeticDensity xiPrimeCorrectionCoeff
  have hnuc := nuc_xiCoeff_eq' X LambdaStar tau
  simp only [nuc, nucW, nuX, one_mul] at hnuc
  linarith

/-- The exact six-term quadratic trace generated by the actual xi-prime
arithmetic density.  In particular, controlling `M[P_X,P_X]` alone is not
a consumer for the xi-prime theorem beyond support one. -/
theorem xiPrimeArithmeticTrace_eq_six_terms
    {Phi : ℝ → ℝ} {T X : ℝ} {LambdaStar : ℂ}
    (hPhi : Continuous Phi) (hPhiEven : ∀ x, Phi (-x) = Phi x)
    (hX : 0 < X) :
    Mform Phi T (xiPrimeArithmeticDensity X LambdaStar)
        (xiPrimeArithmeticDensity X LambdaStar) =
      Mform Phi T (PX X) (PX X) +
      Mform Phi T (Pc X (xiPrimeCorrectionCoeff LambdaStar))
        (Pc X (xiPrimeCorrectionCoeff LambdaStar)) +
      2 * Mform Phi T (PX X)
        (Pc X (xiPrimeCorrectionCoeff LambdaStar)) +
      2 * Mform Phi T (PX X) (PiX X) +
      2 * Mform Phi T (Pc X (xiPrimeCorrectionCoeff LambdaStar)) (PiX X) +
      Mform Phi T (PiX X) (PiX X) := by
  have hdensity : xiPrimeArithmeticDensity X LambdaStar =
      PX X + PiX X + Pc X (xiPrimeCorrectionCoeff LambdaStar) := by
    funext tau
    simpa only [Pi.add_apply] using
      xiPrimeArithmeticDensity_eq X LambdaStar tau
  rw [hdensity]
  exact Mform_trinomial hPhi hPhiEven
    (PX_continuous X) (PiX_continuous hX)
    (Pc_continuous X (xiPrimeCorrectionCoeff LambdaStar))

/-- The released root-zeta density is exactly the specialization of the
general coefficient density at `c=-Λ`. -/
theorem rootPrimeDensity_eq_Pc_negLambda (X tau : ℝ) :
    PX X tau = Pc X (fun N =>
      -((ArithmeticFunction.vonMangoldt N : ℝ) : ℂ)) tau := by
  exact (Pc_neg_vonMangoldt X tau).symm

end

end PrimeShell
