import GafniTao.WooleyInitialConditioning
import Mathlib.Algebra.Polynomial.Eval.Defs

/-!
# Wooley's weighted polynomial-system means

Section 7 of nested efficient congruencing is not closed on a single
monomial phase: translation and dilation produce another `p^c`-spaced
integer-polynomial system.  This file records that actual source class and
the finite-support versions of (3.3)--(3.8) and (3.19)--(3.20).  The earlier
monomial means are recovered definitionally below.
-/

open Finset Polynomial
open scoped BigOperators

namespace GafniTao

noncomputable section

abbrev WooleyPolynomialSystem (k : ℕ) := Fin k → Polynomial ℤ

/-- The monomial system `(t, ..., t^k)`. -/
def wooleyMonomialPolynomialSystem (k : ℕ) : WooleyPolynomialSystem k :=
  fun j => X ^ ((j : ℕ) + 1)

/-- Equation (3.1): each polynomial is its corresponding monomial modulo
the coefficient ideal generated by `p^c`. -/
def WooleyPolynomialSystem.Spaced {k : ℕ}
    (phi : WooleyPolynomialSystem k) (p c : ℕ) : Prop :=
  ∃ psi : WooleyPolynomialSystem k, ∀ j,
    phi j = X ^ ((j : ℕ) + 1) + C ((p : ℤ) ^ c) * psi j

theorem wooleyMonomialPolynomialSystem_spaced
    (k p c : ℕ) :
    (wooleyMonomialPolynomialSystem k).Spaced p c := by
  refine ⟨0, ?_⟩
  intro j
  simp [wooleyMonomialPolynomialSystem]

/-- The exact polynomial phase from (3.3), evaluated on the finite grid
used in (3.5). -/
def wooleyPolynomialGridPhase {k : ℕ}
    (phi : WooleyPolynomialSystem k) (q Q : ℕ) [NeZero q]
    (alpha : Fin k → ZMod q) (n : Fin Q) : ℂ :=
  ZMod.stdAddChar
    (∑ j : Fin k,
      alpha j * (((phi j).eval (((n : ℕ) + 1 : ℕ) : ℤ) : ℤ) : ZMod q))

def wooleyPolynomialWeightedGridSum {Q k : ℕ}
    (phi : WooleyPolynomialSystem k) (q : ℕ) [NeZero q]
    (gamma : Fin Q → ℂ) (alpha : Fin k → ZMod q) : ℂ :=
  ∑ n, gamma n * wooleyPolynomialGridPhase phi q Q alpha n

def wooleyPolynomialWeightedResidueGridSum {Q k qH : ℕ}
    (phi : WooleyPolynomialSystem k) (qB : ℕ) [NeZero qB]
    (gamma : Fin Q → ℂ) (alpha : Fin k → ZMod qB)
    (xi : ZMod qH) : ℂ :=
  ∑ n ∈ wooleyResidueClass Q qH xi,
    gamma n * wooleyPolynomialGridPhase phi qB Q alpha n

def wooleyPolynomialNormalizedGridSum {Q k : ℕ}
    (phi : WooleyPolynomialSystem k) (q : ℕ) [NeZero q]
    (gamma : Fin Q → ℂ) (alpha : Fin k → ZMod q) : ℂ :=
  if wooleyWeightedMassSq gamma = 0 then 0
  else ((Real.sqrt (wooleyWeightedMassSq gamma) : ℂ)⁻¹) *
    wooleyPolynomialWeightedGridSum phi q gamma alpha

def wooleyPolynomialNormalizedResidueGridSum {Q k qH : ℕ}
    (phi : WooleyPolynomialSystem k) (qB : ℕ) [NeZero qB]
    (gamma : Fin Q → ℂ) (alpha : Fin k → ZMod qB)
    (xi : ZMod qH) : ℂ :=
  if wooleyWeightedResidueMassSq gamma xi = 0 then 0
  else ((Real.sqrt (wooleyWeightedResidueMassSq gamma xi) : ℂ)⁻¹) *
    wooleyPolynomialWeightedResidueGridSum phi qB gamma alpha xi

def wooleyPolynomialWeightedGridMean {Q k : ℕ}
    (phi : WooleyPolynomialSystem k) (s q : ℕ) [NeZero q]
    (gamma : Fin Q → ℂ) : ℝ :=
  ((q ^ k : ℕ) : ℝ)⁻¹ *
    ∑ alpha : Fin k → ZMod q,
      ‖wooleyPolynomialNormalizedGridSum phi q gamma alpha‖ ^ (2 * s)

def wooleyPolynomialConditionedGridMean {Q k : ℕ}
    (phi : WooleyPolynomialSystem k) (s qB qH : ℕ)
    [NeZero qB] [NeZero qH] (gamma : Fin Q → ℂ) : ℝ :=
  if wooleyWeightedMassSq gamma = 0 then 0
  else (wooleyWeightedMassSq gamma)⁻¹ *
    ∑ xi : ZMod qH,
      wooleyWeightedResidueMassSq gamma xi *
        (((qB ^ k : ℕ) : ℝ)⁻¹ *
          ∑ alpha : Fin k → ZMod qB,
            ‖wooleyPolynomialNormalizedResidueGridSum
              phi qB gamma alpha xi‖ ^ (2 * s))

/-- The local polynomial-system version of (3.20). -/
def wooleyPolynomialMixedResidueGridMoment {Q k : ℕ}
    (phi : WooleyPolynomialSystem k)
    (s r p B a b : ℕ) [NeZero p] [NeZero (p ^ B)]
    (gamma : Fin Q → ℂ) (xi : ZMod (p ^ a))
    (eta : ZMod (p ^ b)) : ℝ :=
  (((p ^ B) ^ k : ℕ) : ℝ)⁻¹ *
    ∑ alpha : Fin k → ZMod (p ^ B),
      ‖wooleyPolynomialNormalizedResidueGridSum phi
        (p ^ B) gamma alpha xi‖ ^ (2 * wooleyTriangular r) *
      ‖wooleyPolynomialNormalizedResidueGridSum phi
        (p ^ B) gamma alpha eta‖ ^ (2 * (s - wooleyTriangular r))

def wooleyPolynomialMixedGridMean {Q k : ℕ}
    (phi : WooleyPolynomialSystem k)
    (s r p B a b nu : ℕ) [NeZero p] [NeZero (p ^ B)]
    (gamma : Fin Q → ℂ) : ℝ :=
  if wooleyWeightedMassSq gamma = 0 then 0
  else (wooleyWeightedMassSq gamma)⁻¹ ^ 2 *
    ∑ xi : ZMod (p ^ a),
      ∑ eta : ZMod (p ^ b) with wooleyResiduesSeparated nu xi eta,
        wooleyWeightedResidueMassSq gamma xi *
          wooleyWeightedResidueMassSq gamma eta *
            wooleyPolynomialMixedResidueGridMoment
              phi s r p B a b gamma xi eta

theorem wooleyPolynomialGridPhase_monomial
    (q k Q : ℕ) [NeZero q]
    (alpha : Fin k → ZMod q) (n : Fin Q) :
    wooleyPolynomialGridPhase (wooleyMonomialPolynomialSystem k)
        q Q alpha n =
      wooleyMonomialGridPhase q k Q alpha n := by
  unfold wooleyPolynomialGridPhase wooleyMonomialGridPhase
  apply congrArg ZMod.stdAddChar
  apply Finset.sum_congr rfl
  intro j hj
  simp [wooleyMonomialPolynomialSystem]

theorem wooleyPolynomialWeightedGridMean_monomial {Q : ℕ}
    (s k q : ℕ) [NeZero q] (gamma : Fin Q → ℂ) :
    wooleyPolynomialWeightedGridMean
        (wooleyMonomialPolynomialSystem k) s q gamma =
      wooleyWeightedGridMean s k q gamma := by
  unfold wooleyPolynomialWeightedGridMean wooleyWeightedGridMean
    wooleyPolynomialNormalizedGridSum wooleyWeightedNormalizedGridSum
    wooleyPolynomialWeightedGridSum wooleyWeightedGridSum
  simp_rw [wooleyPolynomialGridPhase_monomial]

theorem wooleyPolynomialConditionedGridMean_monomial {Q : ℕ}
    (s k qB qH : ℕ) [NeZero qB] [NeZero qH]
    (gamma : Fin Q → ℂ) :
    wooleyPolynomialConditionedGridMean
        (wooleyMonomialPolynomialSystem k) s qB qH gamma =
      wooleyWeightedConditionedGridMean s k qB qH gamma := by
  unfold wooleyPolynomialConditionedGridMean
    wooleyWeightedConditionedGridMean
    wooleyPolynomialNormalizedResidueGridSum
    wooleyWeightedNormalizedResidueGridSum
    wooleyPolynomialWeightedResidueGridSum
    wooleyWeightedResidueGridSum
  simp_rw [wooleyPolynomialGridPhase_monomial]

theorem wooleyPolynomialMixedGridMean_monomial {Q : ℕ}
    (s k r p B a b nu : ℕ) [NeZero p] [NeZero (p ^ B)]
    (gamma : Fin Q → ℂ) :
    wooleyPolynomialMixedGridMean (wooleyMonomialPolynomialSystem k)
        s r p B a b nu gamma =
      wooleyMixedGridMean s k r p B a b nu gamma := by
  unfold wooleyPolynomialMixedGridMean wooleyMixedGridMean
    wooleyPolynomialMixedResidueGridMoment wooleyMixedResidueGridMoment
    wooleyPolynomialNormalizedResidueGridSum
    wooleyWeightedNormalizedResidueGridSum
    wooleyPolynomialWeightedResidueGridSum
    wooleyWeightedResidueGridSum
  simp_rw [wooleyPolynomialGridPhase_monomial]

#print axioms wooleyMonomialPolynomialSystem_spaced
#print axioms wooleyPolynomialGridPhase_monomial
#print axioms wooleyPolynomialWeightedGridMean_monomial
#print axioms wooleyPolynomialConditionedGridMean_monomial
#print axioms wooleyPolynomialMixedGridMean_monomial

end

end GafniTao
