import Lean.Util.CollectAxioms
import DongWangWangZhang2026.SemanticRegression

open Lean

namespace DongWangWangZhang2026.Audit

private def publicConsumers : Array Name := #[
  ``zetaTerm_mul, ``zetaSum_eq_sum_exp, ``zetaSum_neg, ``norm_zetaSum_le,
  ``norm_normalized_zetaSum_exp_le_one, ``summable_zetaTerm_div_cpow,
  ``tsum_zetaTerm_div_cpow, ``exists_maximizingTwist, ``zetaTerm_sub,
  ``primePhaseDistance_nonneg, ``primePhaseDistance_eq_twisted,
  ``prime_phase_deviation_sq_le, ``prime_phase_deviation_le,
  ``isMultiplicative_phaseMobiusCoeff, ``sum_divisors_phaseMobiusCoeff,
  ``phaseMobiusCoeff_prime_pow, ``norm_phaseMobiusCoeff_prime_pow_le,
  ``phaseMobiusCoeff_twist_convolution, ``zetaSum_eq_mobius_twisted_sum,
  ``norm_phaseMobiusCoeff_prime_pow,
  ``complex_unit_trapezoid_remainder, ``norm_phase_unit_trapezoid_remainder_le,
  ``norm_phase_trapezoid_remainder_le, ``norm_zetaSum_nat_sub_powerMain_le,
  ``norm_zetaSum_sub_powerMain_le, ``norm_zetaSum_sub_powerMain_le_min,
  ``zetaSum_eq_mobius_floor_sum, ``phase_powerMain_transport,
  ``norm_twisted_cell_comparison_le, ``norm_mean_comparison_le_mobius_error,
  ``coefficientLogMul_apply, ``coefficientLogMul_mul,
  ``complexMangoldt_apply, ``sum_divisors_complexMangoldt,
  ``coefficientLogMul_moebius_mul_zeta, ``coefficientLogMul_moebius,
  ``coefficientLogMul_phase, ``coefficientLogMul_phaseMobiusCoeff,
  ``phaseMobiusAbs_apply, ``phaseMobiusAbs_nonneg, ``isMultiplicative_phaseMobiusAbs,
  ``norm_twisted_mangoldt_difference_le, ``phaseMobiusAbs_mul_log_le_convolution,
  ``sum_phaseMobiusAbs_mul_log_le, ``sum_phaseMobiusAbs_le,
  ``phaseMobiusWeight_nonneg, ``phaseMobiusWeight_one, ``phaseMobiusWeight_mul,
  ``hasSum_phaseMobiusWeight_prime_pow, ``sum_phaseMobiusWeight_le_eulerProduct,
  ``phase_prime_factor_error_le, ``sum_phaseMobiusWeight_le_exp_prime,
  ``reciprocal_tail_le_of_mean_bound, ``sum_phaseMobiusWeight_mono,
  ``sum_phaseMobiusWeight_tail_le, ``norm_mean_comparison_le_split,
  ``norm_mean_comparison_le_log_weight, ``norm_mean_comparison_le_prime_error,
  ``norm_normalized_mean_comparison_le,
  ``measurable_zetaSum, ``integrableOn_zetaSum_cpow, ``LSeries_zetaTerm,
  ``integral_zetaSum_cpow, ``integral_zetaSum_exp, ``integrableOn_zetaSum_exp,
  ``integrable_zetaSum_exp, ``integral_zetaSum_exp_univ, ``integrable_dampedZetaSum,
  ``fourier_dampedZetaSum, ``norm_dampedZetaSum_le_one, ``memLp_dampedZetaSum_two,
  ``fourier_toLp_ae_eq, ``memLp_fourier_of_integrable_memLp_two,
  ``integral_norm_sq_fourier_of_integrable_memLp_two,
  ``integral_zeta_quotient_sq_eq_sum_sq, ``integrable_zeta_quotient_sq,
  ``logZetaSum_eq_zero_of_lt_one, ``measurable_logZetaSum, ``norm_logZetaSum_le,
  ``norm_logZetaSum_le_rpow, ``LSeries_logZetaTerm, ``integral_logZetaSum_cpow,
  ``integrableOn_logZetaSum_cpow, ``integral_logZetaSum_exp, ``integrableOn_logZetaSum_exp,
  ``integrable_logZetaSum_exp, ``integral_logZetaSum_exp_univ, ``integrable_dampedLogZetaSum,
  ``fourier_dampedLogZetaSum, ``norm_dampedLogZetaSum_le, ``memLp_dampedLogZetaSum_two,
  ``integral_zeta_deriv_quotient_sq_eq_logSum_sq, ``integrable_zeta_deriv_quotient_sq,
  ``summatory_LSeries_laplace, ``LSeries_quotient_mean_square_le, ``LSeries_twistedMangoldt,
  ``sum_norm_twistedMangoldt_le, ``zeta_logDeriv_quotient_mean_square_le,
  ``zeta_deriv_near_frequency_le, ``exists_maximizingTwist_near_mean_square,
  ``zetaLogBlock_eq_LSeries_terms, ``zetaLogBlock_eq_dirichletTime, ``norm_logPhaseCoeff,
  ``continuous_zetaLogBlock, ``integral_norm_sq_zetaLogBlock_le,
  ``integral_zetaLogBlock_quotient_le, ``integral_zetaLogBlock_positive_shell_le,
  ``integral_zetaLogBlock_negative_shell_le, ``zetaLogBlock_positive_tail,
  ``zetaLogBlock_neg_frequency, ``norm_zetaLogBlock_quotient_neg,
  ``zetaLogBlock_negative_tail, ``zetaLogBlock_far_tail,
  ``sum_lower_power_ratios_le, ``sum_upper_power_ratios_le,
  ``logGaussianKernel_nonneg, ``logGaussianKernel_symm, ``logGaussianKernel_le_power_ratio,
  ``sum_logGaussianKernel_le, ``sum_logGaussianKernel_mul_le,
  ``integral_gaussian_phase, ``integrable_gaussian_phase,
  ``continuous_logFrequencySum, ``norm_logFrequencySum_le,
  ``integrable_gaussian_norm_logFrequencySum, ``integral_gaussian_logFrequencySum,
  ``integral_gaussian_logFrequencySum_le, ``integral_norm_sq_logFrequencySum_le,
  ``logFrequencySum_eq_sum_range, ``summable_logFrequencyTerms, ``tendsto_logFrequencySum,
  ``integral_norm_sq_tsum_logFrequency_le, ``tsum_nat_rpow_neg_le,
  ``log_sq_mul_rpow_le, ``summable_log_sq_mul_rpow, ``tsum_log_sq_mul_rpow_le,
  ``zetaLogCoeff_phase_eq_term, ``zetaLogCoeff_eq_term, ``summable_norm_zetaLogCoeff,
  ``tsum_zetaLogCoeff_phase, ``norm_zetaLogCoeff_sq, ``index_mul_norm_zetaLogCoeff_sq,
  ``summable_norm_zetaLogCoeff_sq, ``summable_index_norm_zetaLogCoeff_sq,
  ``tsum_norm_zetaLogCoeff_sq_le, ``tsum_index_norm_zetaLogCoeff_sq_le,
  ``integral_zeta_deriv_sq_le, ``continuous_shifted_zeta_deriv,
  ``integral_zeta_deriv_sq_shift_le, ``integral_zeta_deriv_quotient_interval_le,
  ``zeta_deriv_positive_far_tail, ``zeta_deriv_negative_far_tail, ``zeta_deriv_far_tail,
  ``poissonLineKernel_nonneg, ``continuous_poissonLineKernel, ``poissonLineKernel_eq_cauchyPDF,
  ``integrable_poissonLineKernel, ``integral_poissonLineKernel,
  ``continuous_poissonExponential, ``integrable_poissonExponential, ``fourier_poissonExponential,
  ``integral_poissonLineKernel_phase, ``integrable_poissonLineKernel_phase,
  ``continuous_tsum_logFrequency, ``norm_tsum_logFrequency_le,
  ``integral_poissonLineKernel_zetaTerm, ``integrable_poissonLineKernel_zetaTerm,
  ``integral_poissonLineKernel_tsum, ``integrable_poissonLineKernel_tsum,
  ``poissonLineKernel_neg, ``integral_poissonLineKernel_far_le,
  ``norm_poissonLine_average_le, ``norm_tsum_logFrequency_rightward_le,
  ``summable_norm_zetaPhaseCoeff, ``norm_zetaPhaseCoeff, ``tsum_norm_zetaPhaseCoeff_le,
  ``zetaPhaseCoeff_phase_eq, ``tsum_zetaPhaseCoeff_phase, ``zetaPhaseCoeff_rightward,
  ``norm_shifted_zeta_rightward_le, ``exists_maximizingTwist_rightward_bound,
  ``poissonLine_zeta, ``exists_maximizingTwist_rightward_near_mean_square,
  ``zeta_deriv_quotient_mean_square_le, ``exists_maximizingTwist_weighted_mean_square,
  ``laplace_zetaSum_dilation, ``laplace_logZetaSum_dilation,
  ``poissonLine_frequency_series, ``zetaPhaseCoeff_modulated_series, ``poissonLine_modulated_zeta,
  ``poissonLine_zeta_difference, ``norm_shifted_zeta_difference_rightward_le,
  ``poissonLine_zeta_dilation_difference,
  ``summable_primeEulerLog, ``log_norm_zeta_eq_prime_logs, ``norm_sub_re_le_log_distance,
  ``norm_primeZetaPower, ``summable_primeZetaPower, ``summable_dampedPrimeDistance,
  ``dampedPrimeDistance_nonneg, ``dampedPrimeDistance_le_log_norm_sub,
  ``norm_zeta_le_exp_neg_dampedPrimeDistance, ``primeZetaPower_re_deficit,
  ``sum_damped_prime_phase_le, ``sum_prime_log_div_le, ``prime_phase_damping_error_le,
  ``primePhaseDistance_le_damped, ``norm_zeta_shift_le_primePhaseDistance,
  ``norm_twistZeta_le_primePhaseDistance, ``tsum_prime_rpow_le_log_norm_zeta,
  ``sum_prime_rpow_le_log_norm_zeta, ``prime_reciprocal_damping_error_le,
  ``sum_prime_reciprocal_le, ``prime_phase_deviation_le_log_bound,
  ``norm_normalized_mean_comparison_le_distance,
  ``sum_prime_log_interval_le, ``sum_nonprime_mangoldt_interval_le,
  ``quarticCell_length_le, ``log_one_add_quartic_le, ``sum_prime_log_quarticCell_le,
  ``sum_mangoldt_quarticCell_le, ``sum_mangoldt_quarticCell_le_uniform,
  ``zetaSum_sub_eq_sum_Ioc, ``norm_zetaSum_sub_le, ``norm_zetaSum_le_of_mem_interval,
  ``intervalIntegrable_zetaSum_reciprocal_norm, ``zetaSum_reciprocal_le_cell_average,
  ``sum_mangoldt_zetaSum_quarticCell_le, ``quarticCell_variation_cost_le,
  ``sum_quarticCells, ``sum_quarticCell_integrals, ``sum_mangoldt_zetaSum_quarticPrefix_le,
  ``exists_quarticCell_cover, ``integral_zetaSum_reciprocal_eq_of_cutoff,
  ``sum_mangoldt_zetaSum_le_integral, ``logZetaSum_eq_log_mul_sub_integral,
  ``norm_log_mul_zetaSum_sub_logZetaSum_le, ``logZetaSum_eq_mangoldt_convolution,
  ``norm_logZetaSum_le_mangoldt_sum, ``norm_zetaSum_mul_log_le_reciprocal_integral,
  ``integral_zetaSum_reciprocal_eq_exp, ``intervalIntegrable_normalized_zetaSum_exp,
  ``norm_normalized_zetaSum_le_log_average,
  ``norm_normalized_zetaSum_exp_le, ``norm_normalized_logZetaSum_exp_le,
  ``normalized_zetaSum_exp_le_logSum, ``intervalIntegrable_normalized_logZetaSum_div,
  ``integral_normalized_zetaSum_exp_le_logSum, ``integral_damping_parameter,
  ``reciprocal_le_damping_parameter, ``integral_damped_logSum_le_sqrt,
  ``integrable_damping_rectangle, ``integral_normalized_logSum_le_damping_average,
  ``norm_shifted_zeta_le_reciprocal, ``continuousOn_meanValueDampingBound,
  ``exists_maximizingTwist_damped_first_moment, ``exists_maximizingTwist_parameter_mean_bound,
  ``meanValueAssemblyConstant_pos, ``meanValueDampingBound_le,
  ``integral_reciprocal_sq, ``integral_min_reciprocal_le,
  ``integral_meanValueDampingBound_le, ``exists_maximizingTwist_mean_value_bound,
  ``ordinaryHalaszConstant_pos, ``exists_maximizingTwist_prime_distance_mean_bound,
  ``primePhaseDistance_le_reciprocal_primes, ``primePhaseDistance_add_one_le_log,
  ``exists_ordinary_mean_error_threshold, ``exists_large_sum_prime_distance_bound,
  ``norm_comparisonFactor_le_reciprocal, ``norm_inverse_comparisonFactor_le,
  ``inverse_comparisonFactor_mul, ``eventually_distance_comparison_error,
  ``exists_large_sum_twist_bounds,
  ``abs_le_sextic_majorant, ``abs_cos_le_three_frequency_majorant,
  ``three_frequency_mean_lt_two_thirds, ``exists_theta_logarithmic_error,
  ``prime_weighted_abel_error, ``hasDerivAt_primeCosineTest,
  ``continuousOn_primeCosineTestDeriv, ``abs_primeCosineTest_le,
  ``abs_primeCosineTestDeriv_le, ``integral_reciprocal_log_power,
  ``prime_cosine_abel_error, ``exists_prime_cosine_integral_error,
  ``integral_primeCosineTest_zero, ``abs_integral_primeCosineTest_le,
  ``exists_prime_absolute_cosine_bound, ``zetaTerm_re_eq_cos,
  ``prime_phase_pair_re_le, ``primePhaseDistance_pair_lower_tail,
  ``exists_primePhaseDistance_pair_lower, ``exists_two_point_zeta_bound,
  ``exists_maximizingTwist_off_frequency_bound,
  ``exists_maximizingTwist_uniform_frequency_bound,
  ``norm_damped_difference_factor_le, ``scaled_frequency_envelope_le,
  ``exists_maximizingTwist_dilation_factor_bound, ``exists_maximizingTwist_dilation_rightward_bound,
  ``dampedLogZetaDifference_eq_actual, ``integrable_dampedLogZetaDifference,
  ``memLp_dampedLogZetaDifference_two, ``fourier_dampedLogZetaDifference,
  ``integral_zeta_deriv_dilation_sq_eq_logDifference_sq, ``integrable_zeta_deriv_dilation_sq,
  ``zeta_deriv_dilation_near_frequency_le, ``zeta_deriv_dilation_mean_square_le,
  ``exists_maximizingTwist_weighted_dilation_mean_square,
  ``SemanticRegression.negativeCutoff, ``SemanticRegression.unitCutoff,
  ``SemanticRegression.zeroIndexExcluded, ``SemanticRegression.bothHeightSigns,
  ``SemanticRegression.spectralShift, ``SemanticRegression.actualMaximizer,
  ``SemanticRegression.actualMobiusConvolution, ``SemanticRegression.primePowerCoefficient,
  ``SemanticRegression.actualPrimeDistance, ``SemanticRegression.powerSumError,
  ``SemanticRegression.twistedMeanReduction, ``SemanticRegression.actualCoefficientMean,
  ``SemanticRegression.actualCoefficientTail, ``SemanticRegression.sourceMeanComparison,
  ``SemanticRegression.actualLaplaceTransform, ``SemanticRegression.actualFourierTransform,
  ``SemanticRegression.actualParseval, ``SemanticRegression.weightedLaplaceTransform,
  ``SemanticRegression.weightedFourierTransform, ``SemanticRegression.weightedParseval,
  ``SemanticRegression.logarithmicDerivativeMeanSquare, ``SemanticRegression.actualMaximizerNearMeanSquare,
  ``SemanticRegression.actualDerivativeBlock, ``SemanticRegression.blockConjugation,
  ``SemanticRegression.shiftedBlockMeanSquare, ``SemanticRegression.actualBlockFarTail,
  ``SemanticRegression.exactGaussianGram, ``SemanticRegression.actualDerivativeSeries,
  ``SemanticRegression.sharpDerivativeCoefficientSums,
  ``SemanticRegression.actualFullDerivativeMeanSquare, ``SemanticRegression.actualFullDerivativeFarTail,
  ``SemanticRegression.poissonFrequencyNormalization, ``SemanticRegression.actualZetaPoisson,
  ``SemanticRegression.actualMaximizerRightward, ``SemanticRegression.actualMaximizerWeightedMeanSquare,
  ``SemanticRegression.actualDilationLaplace, ``SemanticRegression.weightedDilationLaplace,
  ``SemanticRegression.actualDilationPoisson, ``SemanticRegression.differenceMaximumTransport,
  ``SemanticRegression.exactConvergentEulerDistance, ``SemanticRegression.actualSourcePrimeDistanceBound,
  ``SemanticRegression.reciprocalPrimeBound, ``SemanticRegression.sourceMeanComparisonDistance,
  ``SemanticRegression.actualQuarticMangoldtMass, ``SemanticRegression.actualCutoffVariation,
  ``SemanticRegression.actualMangoldtConvolution, ``SemanticRegression.actualPointwiseSmoothing,
  ``SemanticRegression.dampingReconstruction, ``SemanticRegression.actualWeightedCauchy,
  ``SemanticRegression.parameterMinimumEvaluation, ``SemanticRegression.actualMaximizerMeanValue,
  ``SemanticRegression.actualDistanceMeanValue, ``SemanticRegression.crudePrimeDistance,
  ``SemanticRegression.uniformMeanErrorThreshold, ``SemanticRegression.sourceLargeSumPrimeDistance,
  ``SemanticRegression.exactInverseTwistFactor, ``SemanticRegression.sameTwistQuantitativeBounds,
  ``SemanticRegression.actualThetaLogarithmicError, ``SemanticRegression.actualPrimeCosine,
  ``SemanticRegression.actualTwoPointZeta, ``SemanticRegression.sameMaximizerFrequencyBound,
  ``SemanticRegression.actualMaximizerDilationFactor, ``SemanticRegression.actualDilationRightwardBound,
  ``SemanticRegression.weightedDilationParseval, ``SemanticRegression.actualWeightedDilationMeanSquare,
  ``norm_zeta_dilation_le_four_div,
  ``exists_maximizingTwist_weighted_dilation_mean_square_min,
  ``zetaSumDilation_eq_zero_of_lt_one,
  ``measurable_zetaSumDilation,
  ``norm_zetaSumDilation_le,
  ``norm_zetaSum_sub_le_of_mem_interval,
  ``norm_zetaSumDilation_reciprocal_sub_le,
  ``logZetaSumDilation_eq_mangoldt_convolution,
  ``norm_logZetaSumDilation_le_mangoldt_sum,
  ``norm_log_mul_zetaSum_sub_logZetaSum_le_nonneg,
  ``norm_log_mul_zetaSumDilation_sub_logDilation_le,
  ``intervalIntegrable_zetaSumDilation_reciprocal_norm,
  ``zetaSumDilation_reciprocal_le_cell_average,
  ``sum_mangoldt_zetaSumDilation_quarticCell_le,
  ``sum_quarticCell_variation_cost_le,
  ``sum_active_quarticCell_variation_cost_le,
  ``sum_quarticCell_dilation_integrals,
  ``sum_mangoldt_zetaSumDilation_quarticPrefix_le,
  ``integral_zetaSumDilation_reciprocal_eq_of_cutoff,
  ``sum_mangoldt_zetaSumDilation_le_integral,
  ``norm_zetaSumDilation_mul_log_le_reciprocal_integral,
  ``integral_zetaSumDilation_reciprocal_eq_exp,
  ``intervalIntegrable_normalized_zetaSumDilation_exp,
  ``norm_normalized_zetaSumDilation_le_log_average,
  ``zetaSumDilation_exp,
  ``logZetaSumDilation_exp,
  ``norm_exp_dilation_le_log_average,
  ``SemanticRegression.cappedWeightedDilationMeanSquare,
  ``SemanticRegression.actualDilationConvolution,
  ``SemanticRegression.activeDilationFloorCost,
  ``SemanticRegression.actualDilationPointwiseSmoothing,
  ``measurable_logZetaSumDilation,
  ``norm_normalized_logZetaDilation_exp_le,
  ``normalized_zetaDilation_exp_le_logDilation,
  ``intervalIntegrable_normalized_logDilation_div,
  ``integral_normalized_zetaDilation_le_logDilation,
  ``integral_damped_logDilation_le_sqrt,
  ``reciprocal_le_damping_parameter_double,
  ``integrable_dilation_damping_rectangle,
  ``integral_normalized_logDilation_le_damping_average,
  ``continuousOn_dilationDampingBound,
  ``exists_maximizingTwist_dilation_parameter_bound,
  ``dilationDampingBound_le_four_meanValueDampingBound,
  ``integral_dilationDampingBound_le,
  ``min_le_geometric_rpow,
  ``integral_min_reciprocal_le_rpow,
  ``integral_dilationDampingBound_le_rpow,
  ``exists_maximizingTwist_dilation_power_bound,
  ``SemanticRegression.translationScaleLogRemoval,
  ``SemanticRegression.fixedSourceLineReconstruction,
  ``SemanticRegression.uniformSizeParameterEvaluation,
  ``SemanticRegression.actualMaximizerDilationPowerBound,
  ``optimized_dilation_scale_le_third,
  ``log_ratio_loss_le_third,
  ``dilation_logarithmic_loss_le_third,
  ``dilationScaleConstant_ge_one,
  ``dilation_maximum_le_scale,
  ``dilation_power_term_le_third,
  ``dilationLipschitzConstant_ge_four,
  ``dilation_evaluated_bound_le_third,
  ``exists_maximizingTwist_dilation_third_bound,
  ``norm_normalized_dilation_eq,
  ``exists_maximizingTwist_uniform_lipschitz,
  ``exists_large_sum_maximizing_twist,
  ``SemanticRegression.exactThirdExponentAbsorption,
  ``SemanticRegression.exactNormalizedDilation,
  ``SemanticRegression.actualAllRealLipschitz,
  ``SemanticRegression.fullSourceMaximizingTwist,
  ``sum_Icc_rpow_sub_one_le,
  ``norm_zeta_sub_sum_pole_le,
  ``norm_zeta_polynomial_le,
  ``norm_zeta_left_strip_le_cutoff,
  ``norm_zeta_left_strip_le,
  ``SemanticRegression.uniformLeftStripZeta,
  ``SemanticRegression.zeroHeightLeftStrip,
  ``SemanticRegression.closedHalfEndpoint,
  ``SemanticRegression.explicitZetaPoleTruncation,
  ``zetaRemainderKernel_eq,
  ``zetaRemainderKernel_eq_zero,
  ``norm_zetaRemainderKernel_le,
  ``measurable_zetaRemainderKernel,
  ``locallyIntegrableOn_zetaRemainderKernel,
  ``zetaRemainderKernel_isBigO_atTop,
  ``zetaRemainderKernel_isBigO_zero,
  ``mellinConvergent_zetaRemainderKernel,
  ``differentiableAt_zetaRemainderMellin,
  ``zetaRemainderMellin_eq_integral,
  ``integrableOn_zetaRemainder_cpow,
  ``zetaRemainderMellin_eq_of_one_lt_re,
  ``zetaRemainderMellin_pole_removed,
  ``zetaRemainderMellin_eq,
  ``zetaExpRemainder_eq_power,
  ``zetaExpRemainder_of_neg,
  ``norm_zetaExpRemainder_le,
  ``measurable_zetaExpRemainder,
  ``integral_zetaExpRemainder_positive,
  ``integrableOn_zetaExpRemainder_positive,
  ``integrableOn_zetaExpRemainder_negative,
  ``integral_zetaExpRemainder_negative,
  ``integrable_zetaExpRemainder,
  ``integral_zetaExpRemainder,
  ``integral_source_gaussian_phase,
  ``integrable_source_gaussian_double,
  ``integrable_source_gaussian_frequency,
  ``source_gaussian_pairing,
  ``regularized_source_gaussian_identity,
  ``integrable_source_gaussian_zeta,
  ``integrable_source_gaussian_remainder,
  ``integrable_source_gaussian_pole,
  ``integral_source_gaussian_pole,
  ``integrable_source_gaussian_sum,
  ``source_gaussian_identity,
  ``SemanticRegression.continuedActualMellin,
  ``SemanticRegression.actualStripTransform,
  ``SemanticRegression.gaussianPoleAtZeroTwist,
  ``SemanticRegression.bothSourceGaussianIntegrals,
  ``SemanticRegression.exactResidueBearingGaussian,
  ``xi_ne_zero_of_one_le_re,
  ``xi_zero_re_mem_Ioo,
  ``xi_eq_factor_mul_zeta,
  ``analyticAt_xi_zeta_factor,
  ``xi_analyticOrder_eq_zeta,
  ``xi_eq_zero_iff_zeta,
  ``xi_zero_fiber_card,
  ``xiZeroPoint_zero,
  ``xiZeroPoint_re,
  ``xiZeroPoint_zeta_zero,
  ``xiZeroPoint_multiplicity,
  ``xi_analyticOrder_reflect,
  ``xi_divisor_reflect,
  ``xiZeroPoint_reflect,
  ``xiZeroReflect_involutive,
  ``summable_xiZero_norm_inv_sq,
  ``finite_xiZero_norm_le,
  ``summable_xiZero_re_inv,
  ``summable_xiZero_re_resolvent,
  ``xi_logDeriv_reflect,
  ``tsum_xiZero_re_reflected_inv,
  ``re_xi_logDeriv_eq_tsum,
  ``re_xi_logDeriv_eq_tsum_of_one_le_re,
  ``logDeriv_GammaReal,
  ``xi_logDeriv_eq_zeta_gamma,
  ``tsum_xiZero_re_eq_zeta_gamma,
  ``summable_xiZero_inverse_square,
  ``SemanticRegression.xiActualZeros,
  ``SemanticRegression.xiMultiplicityFiber,
  ``SemanticRegression.xiReflectionLabels,
  ``SemanticRegression.xiGenusOneConvergence,
  ``SemanticRegression.xiRealLogDerivative,
  ``SemanticRegression.xiZetaGammaDecomposition,
  ``SemanticRegression.xiRepulsionKernelConvergence
]

private def runAudit : CoreM Unit := do
  let env ← getEnv
  let allowed : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let mut names : Array Name := #[]
  for (name, info) in env.constants.toList do
    if let some idx := env.getModuleIdxFor? name then
      if env.allImportedModuleNames[idx.toNat]!.getRoot == `DongWangWangZhang2026 then
        if info.isTheorem then
          names := names.push name
        if info.isAxiom then
          throwError "Project postulate: {name}"
  if names.isEmpty then throwError "No project theorems discovered"
  for name in publicConsumers do
    if !names.contains name then throwError "Missing public theorem: {name}"
  for name in names.qsort Name.quickLt do
    let axioms ← Lean.collectAxioms name
    let forbidden := axioms.filter fun a => !allowed.contains a
    if !forbidden.isEmpty then throwError "Forbidden dependencies: {name}: {forbidden}"
    logInfo m!"PASS {name}: {axioms}"
  logInfo m!"AUDIT PASS: {names.size} project theorems, including private/generated declarations; {publicConsumers.size} required consumers. Main source theorems remain OPEN."

#eval runAudit

end DongWangWangZhang2026.Audit

#lint in DongWangWangZhang2026
