import Lean.Util.CollectAxioms
import RiemannZeta

open Lean

/-!
# Riemann Zeta dependency audit

This file is executable verification, not a declaration-name classification.
`auditedDeclarations` explicitly lists every source-level theorem exported by the
production modules imported above. `runDependencyAudit` computes each theorem's
transitive axioms with `Lean.collectAxioms` and rejects every dependency except
Lean's standard logical axioms.

The synchronization check also rejects a newly exported project theorem until it
is deliberately added to the explicit list. Compiler-generated equation and proof
theorems are excluded from that public-source check.  A separate named-output
gate prevents a clean subset of the development from being presented as the
completed research agenda while required end theorems are absent.
-/

/-- Standard Lean/Mathlib logical axioms permitted by the project policy. -/
def permittedAxioms : Array Name :=
  #[``propext, ``Classical.choice, ``Quot.sound]

/--
Every public source-level theorem in the imported production modules.

The count is derived from this array rather than maintained as a second literal,
so the reported count cannot drift from the actual audit list.
-/
def auditedDeclarations : Array Name := #[
  -- Foundational zeta and Dirichlet-polynomial modules
  ``RiemannZeta.point_re,
  ``RiemannZeta.point_im,
  ``RiemannZeta.one_sub_point,
  ``RiemannZeta.star_point,
  ``RiemannZeta.completedRiemannZeta_reflection,
  ``RiemannZeta.completedRiemannZeta_zero_reflection_iff,
  ``RiemannZeta.completedRiemannZeta_norm_reflection,
  ``RiemannZeta.completedRiemannZeta_fourfold_zero_orbit,
  ``RiemannZeta.dirichletPoly_conj,
  ``RiemannZeta.dirichletPoly_norm_conj,
  ``RiemannZeta.dirichletNormSquare_conj_line,
  ``RiemannZeta.threshold_conj_line_iff,
  ``RiemannZeta.dirichletPoly_zero_conj,
  ``RiemannZeta.dirichletPoly_zero_conj_iff,
  ``RiemannZeta.crossNormProduct_nonneg,
  ``RiemannZeta.conjCoeff_conjCoeff,
  ``RiemannZeta.crossNormProduct_swap,
  ``RiemannZeta.realPart_abs_le_crossNormProduct,
  ``RiemannZeta.crossNormProduct_eq_zero_of_left,
  ``RiemannZeta.crossNormProduct_eq_zero_of_right,
  ``RiemannZeta.crossNormProduct_eq_zero_iff,
  ``RiemannZeta.criticalLinePoint_re,
  ``RiemannZeta.criticalLinePoint_im,
  ``RiemannZeta.conj_criticalLinePoint,
  ``RiemannZeta.criticalLinePoint_neg_eq_one_sub,
  ``RiemannZeta.completedRiemannZeta_criticalLine_functional_eq,
  ``RiemannZeta.completedRiemannZeta_criticalLine_symm,
  ``RiemannZeta.completedRiemannZeta_norm_criticalLine_neg,
  ``RiemannZeta.hardyZ_norm_eq_riemannZeta_norm,
  ``RiemannZeta.hardyZ_zero_iff_riemannZeta_zero,
  ``RiemannZeta.hardyZ_neg_norm,
  ``RiemannZeta.riemannZeta_ne_zero_of_re_ge_one_of_ne_one,
  ``RiemannZeta.riemannZeta_ne_zero_on_one_line,
  ``RiemannZeta.riemannZeta_ne_zero_totalized,

  -- Guth--Maynard infrastructure and transfer modules
  ``RiemannZeta.GuthMaynard.EpsilonPowerBound.refl,
  ``RiemannZeta.GuthMaynard.EpsilonPowerBound.trans,
  ``RiemannZeta.GuthMaynard.EpsilonPowerBound.add,
  ``RiemannZeta.GuthMaynard.EpsilonPowerBound.congr_left,
  ``RiemannZeta.GuthMaynard.card_pos_of_nonempty,
  ``RiemannZeta.GuthMaynard.isSeparated_translate,
  ``RiemannZeta.GuthMaynard.inBaseInterval_translate,
  ``RiemannZeta.GuthMaynard.translateSet_card,
  ``RiemannZeta.GuthMaynard.dirichletPoly_eq_existing,
  ``RiemannZeta.GuthMaynard.norm_sourceDirichletPoly_conjugateCoeffs,
  ``RiemannZeta.GuthMaynard.publishedSourceDirichletPoly_eq_left_add,
  ``RiemannZeta.GuthMaynard.publishedSourceDirichletPoly_eq_source_of_left_eq_zero,
  ``RiemannZeta.GuthMaynard.norm_conjugateCoeffs,
  ``RiemannZeta.GuthMaynard.dirichletPoly_translate,
  ``RiemannZeta.GuthMaynard.norm_phaseShiftCoeffs,
  ``RiemannZeta.GuthMaynard.norm_normalizedCoeffs_le,
  ``RiemannZeta.GuthMaynard.convolution_support,
  ``RiemannZeta.GuthMaynard.guthMaynardLargeValues_neg,
  ``RiemannZeta.GuthMaynard.guth_maynard_exponent_pos,
  ``RiemannZeta.GuthMaynard.abelZetaKernel_eq_of_one_lt,
  ``RiemannZeta.GuthMaynard.abelZetaKernel_eq_zero_of_le_one,
  ``RiemannZeta.GuthMaynard.norm_abelZetaKernel_le_one,
  ``RiemannZeta.GuthMaynard.measurable_abelZetaKernel,
  ``RiemannZeta.GuthMaynard.locallyIntegrableOn_abelZetaKernel,
  ``RiemannZeta.GuthMaynard.abelZetaKernel_isBigO_atTop,
  ``RiemannZeta.GuthMaynard.abelZetaKernel_isBigO_zero,
  ``RiemannZeta.GuthMaynard.differentiableAt_abelZetaRemainder,
  ``RiemannZeta.GuthMaynard.mellinConvergent_abelZetaKernel,
  ``RiemannZeta.GuthMaynard.abelZetaRemainder_eq_integral,
  ``RiemannZeta.GuthMaynard.integrableOn_abelZetaRemainder_integrand,
  ``RiemannZeta.GuthMaynard.differentiableAt_regularizedRiemannZeta,
  ``RiemannZeta.GuthMaynard.differentiableAt_regularizedAbelZeta,
  ``RiemannZeta.GuthMaynard.sum_one_Icc,
  ``RiemannZeta.GuthMaynard.sum_one_Icc_isBigO,
  ``RiemannZeta.GuthMaynard.natFloor_cast_complex,
  ``RiemannZeta.GuthMaynard.integral_Ioi_cpow_neg,
  ``RiemannZeta.GuthMaynard.riemannZeta_eq_abel_of_one_lt_re,
  ``RiemannZeta.GuthMaynard.regularized_zeta_eq_abel_of_one_lt_re,
  ``RiemannZeta.GuthMaynard.regularized_zeta_eq_abel,
  ``RiemannZeta.GuthMaynard.riemannZeta_eq_abel,
  ``RiemannZeta.GuthMaynard.norm_abelZetaRemainder_le,
  ``RiemannZeta.GuthMaynard.norm_riemannZeta_le_five_mul_norm,
  ``ZetaAppendix.proposition_dadaro,
  ``ZetaAppendix.nonstationary_phase_integral_bound,
  ``ZetaAppendix.nonstationary_power_phase_expansion,
  ``ZetaAppendix.cpow_mul_fourier_exp_eq_log_phase,
  ``ZetaAppendix.poisson_partial_zeta_sum,
  ``ZetaAppendix.partial_zeta_fourier_pair_eq_cosine_integral,
  ``RiemannZeta.GuthMaynard.sharpZetaCutoff_isHalfInteger,
  ``RiemannZeta.GuthMaynard.four_mul_lt_sharpZetaCutoff,
  ``RiemannZeta.GuthMaynard.sharpZetaCutoff_le_add,
  ``RiemannZeta.GuthMaynard.sharpZetaCutoff_le_six_mul,
  ``RiemannZeta.GuthMaynard.sharpZetaCutoff_admissible_of_mem,
  ``RiemannZeta.GuthMaynard.pi_mul_sharpZetaTheta_eq,
  ``RiemannZeta.GuthMaynard.sharpZetaPhase_mem_Icc_of_mem,
  ``RiemannZeta.GuthMaynard.one_sixteenth_le_sin_of_mem_Icc,
  ``RiemannZeta.GuthMaynard.sharpZetaBoundaryCoeff_le_fourteen,
  ``RiemannZeta.GuthMaynard.sharpZetaErrorCoeff_le_129,
  ``RiemannZeta.GuthMaynard.riemannZeta_sharp_halfInteger_truncation,
  ``RiemannZeta.GuthMaynard.zeta_zero_sharp_halfInteger_truncation,
  ``RiemannZeta.GuthMaynard.norm_zeta_zero_sharp_sum_le,
  ``RiemannZeta.GuthMaynard.norm_zeta_zero_sharp_cutoff_sum_le,
  ``RiemannZeta.GuthMaynard.integrableOn_abelZetaTail_integrand,
  ``RiemannZeta.GuthMaynard.abelZetaRemainder_eq_finite_add_tail,
  ``RiemannZeta.GuthMaynard.sum_cpow_neg_eq_boundary_add_floor_integral,
  ``RiemannZeta.GuthMaynard.integral_Ioc_cpow_neg,
  ``RiemannZeta.GuthMaynard.floor_cpow_integral_eq_sub_fract,
  ``RiemannZeta.GuthMaynard.riemannZeta_truncation,
  ``RiemannZeta.GuthMaynard.zeta_zero_truncation,
  ``RiemannZeta.GuthMaynard.norm_zeta_zero_truncation_error_le,
  ``RiemannZeta.GuthMaynard.norm_abelZetaTail_le,
  ``RiemannZeta.GuthMaynard.mem_ZeroRectangle,
  ``RiemannZeta.GuthMaynard.ZeroRectangle_subset,
  ``RiemannZeta.GuthMaynard.isCompact_ZeroRectangle,
  ``RiemannZeta.GuthMaynard.finset_analyticVanishingOrder_le_finsum_divisor,
  ``RiemannZeta.GuthMaynard.riemannZeta_finite_zeros_in_rect,
  ``RiemannZeta.GuthMaynard.zeroCountRect_nonneg,
  ``RiemannZeta.GuthMaynard.zerosInRect_subset_of_rect_subset,
  ``RiemannZeta.GuthMaynard.zeroCountRect_mono,
  ``RiemannZeta.GuthMaynard.zerosInRect_subset,
  ``RiemannZeta.GuthMaynard.zeroCountRect_split,
  ``RiemannZeta.GuthMaynard.riemannZeta_conj,
  ``RiemannZeta.GuthMaynard.iteratedDeriv_conj_conj,
  ``RiemannZeta.GuthMaynard.analyticOrderAt_conj_conj,
  ``RiemannZeta.GuthMaynard.analyticVanishingOrder_conj,
  ``RiemannZeta.GuthMaynard.zeroCountRect_neg_eq_pos,
  ``RiemannZeta.GuthMaynard.zeroCountRect_zero_two_pow_le,
  ``RiemannZeta.GuthMaynard.zeta_two_norm_lt_five_thirds,
  ``RiemannZeta.GuthMaynard.zeta_right_half_plane_bound,
  ``RiemannZeta.GuthMaynard.zeta_jensen_sphere_bound,
  ``RiemannZeta.GuthMaynard.zeta_jensen_rhs_nonneg,
  ``RiemannZeta.GuthMaynard.zeta_growth_bound_native,
  ``RiemannZeta.GuthMaynard.moebius_coeff_norm_le_one,
  ``RiemannZeta.GuthMaynard.moebius_LSeries_norm_lt_five_thirds,
  ``RiemannZeta.GuthMaynard.euler_product_lower_bound_2,
  ``RiemannZeta.GuthMaynard.euler_product_rhs_nonneg,
  ``RiemannZeta.GuthMaynard.zeta_lower_bound_native,
  ``RiemannZeta.GuthMaynard.mem_detectorDivisors,
  ``RiemannZeta.GuthMaynard.detectorDivisors_subset_range,
  ``RiemannZeta.GuthMaynard.detectorDivisors_subset_divisors,
  ``RiemannZeta.GuthMaynard.detectorDivisors_card_le_cutoff,
  ``RiemannZeta.GuthMaynard.norm_moebius_cast_le_one,
  ``RiemannZeta.GuthMaynard.norm_mobius_sum_le_cutoff,
  ``RiemannZeta.GuthMaynard.norm_mobius_sum_le_divisors_card,
  ``RiemannZeta.GuthMaynard.detectorCoeff_eq_zero_iff,
  ``RiemannZeta.GuthMaynard.exp_smoothing_bound,
  ``RiemannZeta.GuthMaynard.norm_detectorCoeff_le_cutoff,
  ``RiemannZeta.GuthMaynard.norm_detectorCoeff_le_divisors_card,
  ``RiemannZeta.GuthMaynard.detectorCoeff_bound,
  ``RiemannZeta.GuthMaynard.uniformDetectorCoeffBound_of_divisorCount,
  ``RiemannZeta.GuthMaynard.detectPoly_eval,
  ``RiemannZeta.GuthMaynard.admissibleDyadicScale_index_lt,
  ``RiemannZeta.GuthMaynard.mem_admissibleDyadicIndices,
  ``RiemannZeta.GuthMaynard.admissibleDyadicIndices_card_le,
  ``RiemannZeta.GuthMaynard.detectorScaleUpper_le_rpow,
  ``RiemannZeta.GuthMaynard.dyadicScaleIndexCount_le_log,
  ``RiemannZeta.GuthMaynard.typeII_exponent_pos,
  ``RiemannZeta.GuthMaynard.denom_pos,
  ``RiemannZeta.GuthMaynard.k_selection,
  ``RiemannZeta.GuthMaynard.eventually_detectorScaleUpper_sq_le,
  ``RiemannZeta.GuthMaynard.central_denominators_pos,
  ``RiemannZeta.GuthMaynard.alpha_pos,
  ``RiemannZeta.GuthMaynard.final_exponent_nonneg,
  ``RiemannZeta.GuthMaynard.first_term_exponent_identity,
  ``RiemannZeta.GuthMaynard.second_term_exponent_identity,
  ``RiemannZeta.GuthMaynard.third_term_exponent_identity,
  ``RiemannZeta.GuthMaynard.mean_value_exponent_le,
  ``RiemannZeta.GuthMaynard.large_values_first_term_le,
  ``RiemannZeta.GuthMaynard.large_values_second_term_le,
  ``RiemannZeta.GuthMaynard.large_values_third_term_le,
  ``RiemannZeta.GuthMaynard.mean_value_height_term_le,
  ``RiemannZeta.GuthMaynard.large_values_terms_le,
  ``RiemannZeta.GuthMaynard.mean_value_terms_le,
  ``RiemannZeta.GuthMaynard.residual_exponent_le_final,
  ``RiemannZeta.GuthMaynard.huxley_exponent_le_final,
  ``RiemannZeta.GuthMaynard.pow_coeff_rhs_nonneg,
  ``RiemannZeta.GuthMaynard.pow_coeff_subset,
  ``RiemannZeta.GuthMaynard.powCoeff_bound_of_uniform_detector_and_factorization,
  ``RiemannZeta.GuthMaynard.powCoeff_bound_of_divisor_and_factorization,
  ``RiemannZeta.GuthMaynard.exponent_succ_le_const_mul_two_rpow,
  ``RiemannZeta.GuthMaynard.exponent_succ_le_large_prime_rpow,
  ``RiemannZeta.GuthMaynard.divisorCountBound_native,
  ``RiemannZeta.GuthMaynard.factorizationCountBound_native,
  ``RiemannZeta.GuthMaynard.powCoeffBound_native,
  ``RiemannZeta.GuthMaynard.powPoly_eval,
  ``RiemannZeta.GuthMaynard.prod_natCast_cpow_eq,
  ``RiemannZeta.GuthMaynard.powCoeff_product_mem_support,
  ``RiemannZeta.GuthMaynard.polynomial_power_identity,
  ``RiemannZeta.GuthMaynard.powCoeff_lower_endpoint_eq_zero,
  ``RiemannZeta.GuthMaynard.polynomial_power_identity_Ioc,
  ``RiemannZeta.GuthMaynard.wideDirichletPoly_eq_sum_blocks,
  ``RiemannZeta.GuthMaynard.exists_large_dyadic_block,
  ``RiemannZeta.GuthMaynard.wideDirichletPoly_poweredLineCoeffs,
  ``RiemannZeta.GuthMaynard.wideDirichletPoly_poweredLineCoeffs_translate,
  ``RiemannZeta.GuthMaynard.norm_poweredLineCoeffs_le,
  ``RiemannZeta.GuthMaynard.norm_phaseShift_normalizedPoweredCoeffs_le_one,
  ``RiemannZeta.GuthMaynard.wideDirichletPoly_normalizedPoweredCoeffs_translate,
  ``RiemannZeta.GuthMaynard.exists_dyadic_block_and_subset,
  ``RiemannZeta.GuthMaynard.normalized_powered_wide_lower,
  ``RiemannZeta.GuthMaynard.mean_value_pos,
  ``RiemannZeta.GuthMaynard.l2_norm_sq_nonneg,
  ``RiemannZeta.GuthMaynard.l2_norm_sq_zero_iff,
  ``RiemannZeta.GuthMaynard.montgomery_mean_value_rhs_nonneg,
  ``RiemannZeta.GuthMaynard.integral_cexp_int,
  ``RiemannZeta.GuthMaynard.integral_conj_fourier_term_mul_fourier_term,
  ``RiemannZeta.GuthMaynard.integral_conj_trigPoly_mul_trigPoly,
  ``RiemannZeta.GuthMaynard.integral_norm_sq_trigPoly,
  ``RiemannZeta.GuthMaynard.continuous_trigPoly,
  ``RiemannZeta.GuthMaynard.integral_sawtooth_cexp,
  ``RiemannZeta.GuthMaynard.integral_sawtooth_cexp_all,
  ``RiemannZeta.GuthMaynard.hilbertForm_norm_le,
  ``RiemannZeta.GuthMaynard.nat_hilbertForm_norm_le,
  ``RiemannZeta.GuthMaynard.integral_sawtooth_conj_fourier_mul_fourier,
  ``RiemannZeta.GuthMaynard.integral_sawtooth_conj_trigPoly_mul_trigPoly,
  ``RiemannZeta.GuthMaynard.norm_sawtooth_conj_trigPoly_mul_trigPoly_le,
  ``RiemannZeta.GuthMaynard.abs_inv_log_sub_sub_div_le_one,
  ``RiemannZeta.GuthMaynard.norm_complex_log_kernel_error_le_one,
  ``RiemannZeta.GuthMaynard.logHilbertQuad_eq_main_add_error,
  ``RiemannZeta.GuthMaynard.logKernelErrorQuad_norm_le,
  ``RiemannZeta.GuthMaynard.natMainQuad_eq_scaled_hilbert,
  ``RiemannZeta.GuthMaynard.natScaledCoeff_l2_le,
  ``RiemannZeta.GuthMaynard.natMainQuad_norm_le,
  ``RiemannZeta.GuthMaynard.logHilbertQuad_norm_le,
  ``RiemannZeta.GuthMaynard.norm_endpointTwist,
  ``RiemannZeta.GuthMaynard.integral_conj_dirichlet_term_mul_dirichlet_term,
  ``RiemannZeta.GuthMaynard.integral_conj_dirichletTime_mul_dirichletTime,
  ``RiemannZeta.GuthMaynard.continuous_dirichletTime,
  ``RiemannZeta.GuthMaynard.ofReal_integral_norm_sq_dirichletTime,
  ``RiemannZeta.GuthMaynard.integral_norm_sq_dirichletTime_le,
  ``RiemannZeta.GuthMaynard.local_sample_le_energy,
  ``RiemannZeta.GuthMaynard.sum_local_intervalIntegrals_le,
  ``RiemannZeta.GuthMaynard.centeredDirichletTime_eq,
  ``RiemannZeta.GuthMaynard.norm_centeredDirichletTime,
  ``RiemannZeta.GuthMaynard.hasDerivAt_centeredDirichletTime,
  ``RiemannZeta.GuthMaynard.differentiable_centeredDirichletTime,
  ``RiemannZeta.GuthMaynard.deriv_centeredDirichletTime,
  ``RiemannZeta.GuthMaynard.continuous_deriv_centeredDirichletTime,
  ``RiemannZeta.GuthMaynard.abs_log_ratio_le_one,
  ``RiemannZeta.GuthMaynard.centeredDerivCoeff_l2_le,
  ``RiemannZeta.GuthMaynard.nat_cpow_neg_mul_I_eq,
  ``RiemannZeta.GuthMaynard.montgomery_mean_value_estimate,
  ``RiemannZeta.GuthMaynard.montgomery_mean_value_native,
  ``RiemannZeta.GuthMaynard.sum_sq_le_card_mul_sum_sq,
  ``RiemannZeta.GuthMaynard.complex_sum_sq_le_card_mul_sum_sq,
  ``RiemannZeta.GuthMaynard.pigeonhole_real_sum,
  ``RiemannZeta.GuthMaynard.separated_selection,
  ``RiemannZeta.GuthMaynard.weighted_separated_selection,
  ``RiemannZeta.GuthMaynard.typeI_add_residual_eq_total,
  ``RiemannZeta.GuthMaynard.chosenTypeIScale_spec,
  ``RiemannZeta.GuthMaynard.chosenTypeIScale_mem,
  ``RiemannZeta.GuthMaynard.sum_shiftedMultiplicity,
  ``RiemannZeta.GuthMaynard.shifted_bin_weight_le_of_unit_bin_weight,
  ``RiemannZeta.GuthMaynard.weighted_finite_pigeonhole,
  ``RiemannZeta.GuthMaynard.finite_weighted_extract_separated,
  ``RiemannZeta.GuthMaynard.detectPoly_eq_dirichletPoly,
  ``RiemannZeta.GuthMaynard.detectPoly_translate,
  ``RiemannZeta.GuthMaynard.norm_translatedDetectorCoeffs,
  ``RiemannZeta.GuthMaynard.typeI_unit_bin_sum_le_jensen,
  ``RiemannZeta.GuthMaynard.localZeroMultiplicityBound_native,
  ``RiemannZeta.GuthMaynard.rpow_mul_log_sq_le_epsilon,
  ``RiemannZeta.GuthMaynard.rawExtractSeparated_of_beta_shift_and_local_multiplicity,
  ``RiemannZeta.GuthMaynard.extractSeparated_of_beta_shift_and_local_multiplicity,
  ``RiemannZeta.GuthMaynard.extractSeparated_of_beta_shift,
  ``RiemannZeta.GuthMaynard.norm_detectPoly_le_detectorMass,
  ``RiemannZeta.GuthMaynard.differentiable_detectPoly_add,
  ``RiemannZeta.GuthMaynard.localizer_norm_le_one,
  ``RiemannZeta.GuthMaynard.localizedDetector_le_detectorMass,
  ``RiemannZeta.GuthMaynard.localizedDetector_halfPlane_bound,
  ``RiemannZeta.GuthMaynard.localizer_norm_boundary_le,
  ``RiemannZeta.GuthMaynard.exists_nearby_large_value,
  ``RiemannZeta.GuthMaynard.detectorCutoff_le_three_mul,
  ``RiemannZeta.GuthMaynard.detectorMass_le_pow_seven,
  ``RiemannZeta.GuthMaynard.localizer_factor_gt_three_fourths,
  ``RiemannZeta.GuthMaynard.detectorMass_mul_localizer_lt,
  ``RiemannZeta.GuthMaynard.beta_dependence_removal,
  ``RiemannZeta.GuthMaynard.extractSeparated_native,
  ``RiemannZeta.GuthMaynard.monotonic_density_reduction,
  ``RiemannZeta.GuthMaynard.dyadicHeightIndex_spec,
  ``RiemannZeta.GuthMaynard.dyadicToGlobalZeroCount,
  ``RiemannZeta.GuthMaynard.uniform_powCoeff_bound_up_to_101,
  ``RiemannZeta.GuthMaynard.dirichletPoly_restrictToDyadicBlock,
  ``RiemannZeta.GuthMaynard.norm_restrictToDyadicBlock_le_one,
  ``RiemannZeta.GuthMaynard.dyadic_block_subset_powered_support,
  ``RiemannZeta.GuthMaynard.selected_block_coefficients,
  ``RiemannZeta.GuthMaynard.inverse_normalized_threshold_sq,
  ``RiemannZeta.GuthMaynard.inverse_normalized_threshold_fourth,
  ``RiemannZeta.GuthMaynard.section13_threshold_identity,
  ``RiemannZeta.GuthMaynard.eventually_log_pow_le_rpow,
  ``RiemannZeta.GuthMaynard.eventually_section13Loss_fourth_bound,
  ``RiemannZeta.GuthMaynard.selected_block_large_value_terms_le,
  ``RiemannZeta.GuthMaynard.selected_block_mean_value_terms_le,
  ``RiemannZeta.GuthMaynard.typeIPositiveSlabBound_of_section13_inputs,
  ``RiemannZeta.GuthMaynard.central_positive_slab_of_typeI_and_residual,
  ``RiemannZeta.GuthMaynard.high_sigma_of_huxley,
  ``RiemannZeta.GuthMaynard.conditionalZeroDensityTransfer,
  ``RiemannZeta.GuthMaynard.huxley_zero_density_at_three_quarters_of_ingham,
  ``RiemannZeta.GuthMaynard.ingham_zeta_polynomial_range_empty,
    ``RiemannZeta.GuthMaynard.huxley_zeta_polynomial_range_empty,
    ``RiemannZeta.GuthMaynard.huxley_zeta_polynomial_range_below_weyl,
    ``RiemannZeta.GuthMaynard.classical_density_exponents_eq_at_three_quarters,
    ``RiemannZeta.GuthMaynard.EndpointScaleCertificate.tau0_pos,
    ``RiemannZeta.GuthMaynard.EndpointScaleCertificate.density_base_le_tau0,
    ``RiemannZeta.GuthMaynard.EndpointScaleCertificate.mhh_window,
    ``RiemannZeta.GuthMaynard.EndpointScaleCertificate.subdivision_window,
    ``RiemannZeta.GuthMaynard.EndpointScaleCertificate.raised_scale_window,
    ``RiemannZeta.GuthMaynard.EndpointScaleCertificate.zeta_window,
    ``RiemannZeta.GuthMaynard.exists_two_or_three_scale_reduction,
    ``RiemannZeta.GuthMaynard.exists_two_or_three_power_scale_reduction,
    ``RiemannZeta.GuthMaynard.classicalMHHExponent_le_montgomery_of_tau_le_one,
    ``RiemannZeta.GuthMaynard.classicalMHHExponent_le_montgomery_of_tau_le_four_sigma_sub_two,
    ``RiemannZeta.GuthMaynard.corollary1110Envelope_le_target,
    ``RiemannZeta.GuthMaynard.rpow_corollary1110Envelope_le_target,
  ``RiemannZeta.GuthMaynard.ingham_endpoint_scale_certificate,
  ``RiemannZeta.GuthMaynard.huxley_endpoint_scale_certificate,
  ``RiemannZeta.GuthMaynard.classical_finite_scale_exponent_assembly_native,
  ``RiemannZeta.GuthMaynard.EpsilonPowerBound_mono,
  ``RiemannZeta.GuthMaynard.combined_zero_density_transfer_native,

  -- Classical density foundations and proved endpoint boundary cases
  ``RiemannZeta.GuthMaynard.mollifiedZetaCoeff_eq_ite,
  ``RiemannZeta.GuthMaynard.mollifiedZetaCoeff_eq_zero,
  ``RiemannZeta.GuthMaynard.truncatedMoebius_apply,
  ``RiemannZeta.GuthMaynard.truncatedMoebius_hasFiniteSupport,
  ``RiemannZeta.GuthMaynard.truncatedMoebius_LSeriesSummable,
  ``RiemannZeta.GuthMaynard.zetaMollifier_eq_LSeries,
  ``RiemannZeta.GuthMaynard.zeta_mul_truncatedMoebius_apply,
  ``RiemannZeta.GuthMaynard.riemannZeta_mul_zetaMollifier_eq_LSeries,
  ``RiemannZeta.GuthMaynard.mollifiedZetaErrorCoeff_eq_zero,
  ``RiemannZeta.GuthMaynard.LSeriesSummable_delta,
  ``RiemannZeta.GuthMaynard.mollifiedZetaCoeff_LSeriesSummable,
  ``RiemannZeta.GuthMaynard.mollifiedZetaError_eq_LSeries,
  ``RiemannZeta.GuthMaynard.inghamZeroDetector_eq_one_sub_sq,
  ``RiemannZeta.GuthMaynard.regularizedInghamZeroDetector_of_ne,
  ``RiemannZeta.GuthMaynard.analyticAt_zetaMollifier,
  ``RiemannZeta.GuthMaynard.analytic_regularizedInghamZeroDetector,
  ``RiemannZeta.GuthMaynard.tendsto_natCast_cpow_neg_ofReal_atTop,
  ``RiemannZeta.GuthMaynard.tendsto_zetaMollifier_ofReal_atTop,
  ``RiemannZeta.GuthMaynard.exists_zetaMollifier_ofReal_ne_zero,
  ``RiemannZeta.GuthMaynard.zetaMollifier_analyticOrderAt_ne_top,
  ``RiemannZeta.GuthMaynard.analyticAt_mollifiedZetaError,
  ``RiemannZeta.GuthMaynard.analyticAt_inghamZeroDetector,
  ``RiemannZeta.GuthMaynard.riemannZeta_analyticOrderAt_ne_top,
  ``RiemannZeta.GuthMaynard.inghamZeroDetector_eq_zero_of_zeta_eq_zero,
  ``RiemannZeta.GuthMaynard.analyticVanishingOrder_zeta_le_inghamZeroDetector,
  ``RiemannZeta.GuthMaynard.analyticVanishingOrder_regularizedInghamZeroDetector_eq,
  ``RiemannZeta.GuthMaynard.analyticVanishingOrder_zeta_le_regularizedInghamZeroDetector,
  ``RiemannZeta.GuthMaynard.sum_zeta_multiplicity_le_regularizedInghamZeroDetector,
  ``RiemannZeta.GuthMaynard.sum_zeta_multiplicity_le_of_regularizedInghamZeroDetector_bound,
  ``RiemannZeta.GuthMaynard.zerosInRect_one_eq_empty,
  ``RiemannZeta.GuthMaynard.N_one,
  ``RiemannZeta.GuthMaynard.epsilonPowerBound_zero,
  ``RiemannZeta.GuthMaynard.ingham_zero_density_at_one_native,
  ``RiemannZeta.GuthMaynard.huxley_zero_density_at_one_native,
  ``RiemannZeta.GuthMaynard.zeroUnitBin_multiplicity_le_jensen,
  ``RiemannZeta.GuthMaynard.zeroCountRect_dyadic_le_jensen,
  ``RiemannZeta.GuthMaynard.dyadic_zero_count_epsilon_one,
  ``RiemannZeta.GuthMaynard.global_zero_count_epsilon_one,
  ``RiemannZeta.GuthMaynard.ingham_zero_density_at_half_native,
  ``RiemannZeta.GuthMaynard.truncatedZeta_apply,
  ``RiemannZeta.GuthMaynard.truncatedZeta_hasFiniteSupport,
  ``RiemannZeta.GuthMaynard.truncatedZeta_LSeriesSummable,
  ``RiemannZeta.GuthMaynard.zetaPartialSum_eq_LSeries,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_eq_ite,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_eq_zero,
  ``RiemannZeta.GuthMaynard.zetaPartialSum_mul_zetaMollifier_eq_LSeries,
  ``RiemannZeta.GuthMaynard.norm_sharpZetaTail_ge,
  ``RiemannZeta.GuthMaynard.logHilbertQuadUpTo_eq_main_add_error,
  ``RiemannZeta.GuthMaynard.logKernelErrorQuadUpTo_norm_le,
  ``RiemannZeta.GuthMaynard.natMainQuadUpTo_eq_scaled_hilbert,
  ``RiemannZeta.GuthMaynard.natScaledCoeffUpTo_l2_le,
  ``RiemannZeta.GuthMaynard.natMainQuadUpTo_norm_le,
  ``RiemannZeta.GuthMaynard.logHilbertQuadUpTo_norm_le,
  ``RiemannZeta.GuthMaynard.integral_conj_dirichletTimeUpTo_mul_dirichletTimeUpTo,
  ``RiemannZeta.GuthMaynard.continuous_dirichletTimeUpTo,
  ``RiemannZeta.GuthMaynard.ofReal_integral_norm_sq_dirichletTimeUpTo,
  ``RiemannZeta.GuthMaynard.integral_norm_sq_dirichletTimeUpTo_le,
  ``RiemannZeta.GuthMaynard.zetaMollifier_criticalLine_eq_dirichletTimeUpTo,
  ``RiemannZeta.GuthMaynard.norm_mollifierCriticalCoeff_sq_le_inv,
  ``RiemannZeta.GuthMaynard.mollifierCriticalCoeff_l2_le_harmonic,
  ``RiemannZeta.GuthMaynard.integral_norm_sq_zetaMollifier_criticalLine_le,
  ``RiemannZeta.GuthMaynard.norm_riemannZeta_le_twenty_mul_abs_im_on_classical_strip,
  ``RiemannZeta.GuthMaynard.analytic_rectangle_logDeriv_integral_eq_order_sum,
  ``RiemannZeta.GuthMaynard.regularizedInghamZeroDetector_rectangle_argumentPrinciple,

  -- Vendored PNT+ rectangle and argument-principle infrastructure
  ``MeromorphicOn.exists_nonzero_seq_divisor_support_diff_zero,
  ``mem_Rect,
  ``mapsTo_rectangle_left_re,
  ``mapsTo_rectangleBorder_right_re,
  ``Square_apply,
  ``ContinuousOn.rectangleBorderNoPIntegrable,
  ``Set.ne_left_of_mem_uIoo,
  ``square_subset_square,
  ``RectanglePullToNhdOfPole'',
  ``ResidueTheoremAtOrigin',
  ``Rectangle.symm,
  ``logDeriv_hasSimplePolesOn_of_meromorphicOrderAt_ne_top,
  ``HolomorphicOn.rectangleBorderIntegrable,
  ``segment_reProdIm_segment_eq_convexHull,
  ``RectangleIntegralHSplit',
  ``RectangleIntegral_congr,
  ``integral_const_div_sq_add_sq,
  ``HIntegral_symm,
  ``residue_eq_of_tendsto,
  ``mapsTo_rectangle_left_im_NoP,
  ``RectangleBorderIntegrable.add,
  ``RectangleIntegral.const_smul,
  ``rectangle_argumentChange_eq_two_pi_sum_meromorphicOrderAt,
  ``mapsTo_rectangleBorder_right_im,
  ``rectangle_subset_punctured_rect,
  ``ResidueTheoremAtOrigin_aux1c',
  ``ResidueTheoremAtOrigin_aux2c',
  ``rectangleBorder_subset_rectangle,
  ``simplePole_sub_residue_isBigO_one,
  ``sumResiduesIn_inter_eq_of_set_eq,
  ``RectSubRect',
  ``verticalPath_not_eventuallyConst,
  ``RectangleIntegral'_congr,
  ``mapsTo_rectangleBorder_left_im,
  ``residue_eq_zero_of_not_pole_of_meromorphicAt,
  ``rectangle_mem_nhds_iff,
  ``ContinuousOn.rectangleBorder_integrable,
  ``integral_const_div_self_add_im,
  ``Complex.inv_re_add_im,
  ``RectanglePullToNhdOfPole,
  ``RectangleIntegralVSplit,
  ``continuous_self_div_sq_add_sq,
  ``HolomorphicOn.rectangleBorderIntegrable',
  ``MeromorphicOn.divisor_support_inter_compact_finite,
  ``ContinuousLinearEquiv.coe_toLinearEquiv_symm,
  ``existsDifferentiableOn_of_bddAbove,
  ``SmallSquareInRectangle,
  ``verticalIntegral_split_three,
  ``rectangle_disjoint_singleton,
  ``ResidueTheoremAtOrigin,
  ``rectangleIntegral_symm,
  ``rectangleIntegral_symm_re,
  ``mapsTo_rectangleBorder_left_re,
  ``RectangleIntegralVSplit',
  ``MeromorphicOn.exists_ball_inter_divisor_support_eq_singleton,
  ``square_neg,
  ``MeromorphicOn.divisor_support_discrete,
  ``VIntegral_symm,
  ``MeromorphicOn.exists_seq_eq_range_divisor_support,
  ``divisor_support_rectangle_finite,
  ``logDeriv_sub_principal_isBigO_one_of_meromorphicOrderAt,
  ``preimage_equivRealProdCLM_reProdIm,
  ``left_mem_rect,
  ``HasSimplePolesOn.mono,
  ``logDeriv_poles_eq_divisor_support,
  ``mapsTo_rectangle_left_im,
  ``ResidueTheoremAtOrigin_aux2c,
  ``RectangleIntegralHSplit,
  ``RectangleIntegral.translate',
  ``rect_subset_iff,
  ``residue_analyticAt_eq_zero,
  ``Set.ne_right_of_mem_uIoo,
  ``Complex.nhds_hasBasis_square,
  ``right_mem_rect,
  ``integral_const_div_re_add_self,
  ``rectangleBorder_disjoint_singleton,
  ``Set.left_not_mem_uIoo,
  ``RectanglePullToNhdOfPole',
  ``square_mem_nhds,
  ``RectSubRect,
  ``mapsTo_rectangle_right_re,
  ``ContinuousOn.rectangleBorderIntegrable,
  ``IsBigO_to_BddAbove,
  ``RectangleIntegral'_eq_sumResiduesIn,
  ``ResidueTheoremOnRectangleWithSimplePole',
  ``logDeriv_residue_eq_meromorphicOrderAt,
  ``rectangleIntegral_logDeriv_eq_sum_meromorphicOrderAt,
  ``rectangle_in_convex,
  ``RectangleIntegral.translate,
  ``not_mem_rectangleBorder_of_rectangle_mem_nhds,
  ``mapsTo_rectangle_right_im_NoP,
  ``mapsTo_rectangle_left_re_NoP,
  ``ResidueTheoremOnRectangleWithSimplePole,
  ``HolomorphicOn.vanishesOnRectangle,
  ``RectangleIntegral.const_mul',
  ``rectangleBorder_subset_punctured_rect,
  ``MeromorphicOn.divisor_support_countable,
  ``ResidueTheoremAtOrigin_aux1c,
  ``ResidueTheoremInRectangle,
  ``DiffVertRect_eq_UpperLowerUs,
  ``Rectangle.symm_re,
  ``mapsTo_rectangle_right_re_NoP,
  ``Set.right_not_mem_uIoo,
  ``mapsTo_rectangle_right_im,
  ``sq_add_sq_ne_zero,
  ``BddAbove_on_rectangle_of_bdd_near,
  ``integral_self_div_sq_add_sq,

  -- Production modules formerly omitted from the root import graph
  ``RiemannZeta.GuthMaynard.halasz_montgomery_rhs_nonneg,
  ``RiemannZeta.GuthMaynard.discrete_duality_cauchy_schwarz,
  ``RiemannZeta.GuthMaynard.halasz_montgomery_lemma_of_mean_value,
  ``RiemannZeta.GuthMaynard.halasz_montgomery_lemma_native,
  ``RiemannZeta.GuthMaynard.weightedResidualCount_le_weightedCount_of_cover,
  ``RiemannZeta.GuthMaynard.residual_epsilonPowerBound_of_cover,
  ``RiemannZeta.GuthMaynard.EpsilonPowerBound.mul_left_rpow,
  ``RiemannZeta.GuthMaynard.scaled_twistedZetaFourthMoment_bound,
  ``RiemannZeta.GuthMaynard.residual_zero_bound_of_cover_reduction_and_fourth_moment,
  ``RiemannZeta.GuthMaynard.finiteTypeICover_of_typeIContourTypeII,
  ``RiemannZeta.GuthMaynard.weightedResidualCount_dyadicZetaZeros_eq,
  ``RiemannZeta.GuthMaynard.residualZeroBound_of_contourTypeII_reduction_and_fourthMoment,
  -- Shitlist #18: convergence, scaled extraction, coverage algebra, and M-squared specialization
  ``RiemannZeta.GuthMaynard.Gamma_add_nat_eq_prod_mul,
  ``RiemannZeta.GuthMaynard.abs_im_pow_le_norm_prod_horizontal,
  ``RiemannZeta.GuthMaynard.typeII_Gamma_vertical_decay,
  ``RiemannZeta.GuthMaynard.typeII_Gamma_norm_le_inv_pow,
  ``RiemannZeta.GuthMaynard.typeII_Gamma_norm_le_fourteen,
  ``RiemannZeta.GuthMaynard.appendixC_Gamma_vertical_decay,
  ``RiemannZeta.GuthMaynard.appendixC_Gamma_norm_le_inv_pow,
  ``RiemannZeta.GuthMaynard.continuous_typeII_Gamma_horizontal,
  ``RiemannZeta.GuthMaynard.integrable_typeII_Gamma_horizontal,
  ``RiemannZeta.GuthMaynard.integrable_one_add_abs_mul_typeII_Gamma_horizontal,
  ``RiemannZeta.GuthMaynard.scaled_weighted_separated_selection,
  ``RiemannZeta.GuthMaynard.separated_window_card_le_one,
  ``RiemannZeta.GuthMaynard.norm_riemannZeta_criticalLine_le,
  ``RiemannZeta.GuthMaynard.norm_riemannZeta_shifted_criticalLine_le,
  ``RiemannZeta.GuthMaynard.continuous_const_cpow_of_ne_zero,
  ``RiemannZeta.GuthMaynard.continuous_shortMobiusPolynomial_vertical,
  ``RiemannZeta.GuthMaynard.norm_shortMobiusPolynomial_criticalLine_le,
  ``RiemannZeta.GuthMaynard.rho_add_typeIIContourShift,
  ``RiemannZeta.GuthMaynard.integrable_typeIIContourIntegrand,
  ``RiemannZeta.GuthMaynard.contourTypeII_weight_sum_eq,
  ``RiemannZeta.GuthMaynard.contourTypeII_weight_sum_eq_weightedCount,
  ``RiemannZeta.GuthMaynard.zeroUnitJensenCeil_le_log,
  ``RiemannZeta.GuthMaynard.contourTypeII_unit_bin_weight_le,
  ``RiemannZeta.GuthMaynard.exists_separated_contourTypeII_ordinates,
  ``RiemannZeta.GuthMaynard.contourTypeII_scaled_bin_weight_le,
  ``RiemannZeta.GuthMaynard.exists_scaled_separated_contourTypeII_ordinates,
  ``RiemannZeta.GuthMaynard.contourTypeIIRepresentative_spec,
  ``RiemannZeta.GuthMaynard.criticalTwistedNorm_pow_four,
  ``RiemannZeta.GuthMaynard.detectorCutoff_le_three_mul_height,
  ``RiemannZeta.GuthMaynard.criticalTwistedNorm_shifted_le,
  ``RiemannZeta.GuthMaynard.continuous_criticalTwistedNorm,
  ``RiemannZeta.GuthMaynard.criticalTwistedNorm_representative_le,
  ``RiemannZeta.GuthMaynard.integral_abs_rpow_compl_Icc,
  ``RiemannZeta.GuthMaynard.integrableOn_abs_rpow_compl_Icc,
  ``RiemannZeta.GuthMaynard.integral_norm_typeII_Gamma_le_thirty,
  ``RiemannZeta.GuthMaynard.setIntegral_comp_add_Icc,
  ``RiemannZeta.GuthMaynard.norm_typeIIContourIntegrand_eq,
  ``RiemannZeta.GuthMaynard.integrable_gamma_mul_criticalTwistedNorm,
  ``RiemannZeta.GuthMaynard.representative_typeII_gamma_tail_le,
  ``RiemannZeta.GuthMaynard.eventually_representative_typeII_gamma_tail_small,
  ``RiemannZeta.GuthMaynard.norm_typeIIContourIntegral_le,
  ``RiemannZeta.GuthMaynard.one_le_typeII_gamma_convolution,
  ``RiemannZeta.GuthMaynard.one_le_representative_gamma_window,
  ``RiemannZeta.GuthMaynard.integral_mul_fourth_holder,
  ``RiemannZeta.GuthMaynard.representative_gamma_window_holder,
  ``RiemannZeta.GuthMaynard.representative_gamma_window_fourth_le,
  ``RiemannZeta.GuthMaynard.separated_windows_fourthMoment_le,
  ``RiemannZeta.GuthMaynard.separated_typeII_card_le_fourthMoment,
  ``RiemannZeta.GuthMaynard.typeIIFourthMomentReduction_native,
  ``RiemannZeta.GuthMaynard.detectorDivisors_eq_divisors_of_le,
  ``RiemannZeta.GuthMaynard.mobius_sum_eq_ite_of_le,
  ``RiemannZeta.GuthMaynard.mobius_sum_eq_ite_of_lt_detectorCutoff,
  ``RiemannZeta.GuthMaynard.detectorCoeff_one,
  ``RiemannZeta.GuthMaynard.detectorCoeff_eq_zero_of_lt_cutoff,
  ``RiemannZeta.GuthMaynard.typeIContourTypeIICoverOn_native,
  ``RiemannZeta.GuthMaynard.typeIContourTypeIICover_native,
  ``RiemannZeta.GuthMaynard.shortMobiusSquare_tuple_mem_support,
  ``RiemannZeta.GuthMaynard.shortMobiusPolynomial_sq_eq,
  ``RiemannZeta.GuthMaynard.shortMobiusSquareCoeff_eq_zero_of_not_mem,
  ``RiemannZeta.GuthMaynard.eventually_detectorCutoff_sq_le_rpow,
  ``RiemannZeta.GuthMaynard.shortMobiusSquare_fiber_card_le_divisors,
  ``RiemannZeta.GuthMaynard.norm_shortMobiusSquareCoeff_le_divisors,
  ``RiemannZeta.GuthMaynard.shortMobiusSquareCoeff_bound,
  ``RiemannZeta.GuthMaynard.twistedZetaMomentIntegrand_eq_zeta_four_mul_mobius_sq,
  ``RiemannZeta.GuthMaynard.twistedZetaFourthMoment_eq,
  ``RiemannZeta.GuthMaynard.twistedFourthMomentPhase_eq_one_of_diagonal,
  ``RiemannZeta.GuthMaynard.integral_twistedFourthMomentPhase_of_diagonal,
  ``RiemannZeta.GuthMaynard.finiteTwistedFourthMomentDiagonal_eq,
  ``RiemannZeta.GuthMaynard.norm_finiteTwistedFourthMomentDiagonal_le,
  ``RiemannZeta.GuthMaynard.logQuad_symmetric_difference_le,
  ``RiemannZeta.GuthMaynard.norm_GammaSeq_vertical,
  ``RiemannZeta.GuthMaynard.gammaDenom_symmetric_ratio_le,
  ``RiemannZeta.GuthMaynard.norm_GammaSeq_symmetric_le,
  ``RiemannZeta.GuthMaynard.norm_Gamma_symmetric_le,
  ``RiemannZeta.GuthMaynard.norm_GammaR_critical_symmetric_le,
  ``RiemannZeta.GuthMaynard.arithmeticZeta_mul_self_eq_sigma_zero,
  ``RiemannZeta.GuthMaynard.riemannZeta_sq_eq_divisorLSeries,
  ``RiemannZeta.GuthMaynard.completedXiNumerator_eq_neg_two_mul_riemannXi,
  ``RiemannZeta.GuthMaynard.exists_completedXiNumerator_order_three_halves_bound,
  ``RiemannZeta.GuthMaynard.tendsto_exp_const_sub_sq_add_three_halves,
  ``RiemannZeta.GuthMaynard.completedXiNumerator_one_sub,
  ``RiemannZeta.GuthMaynard.differentiable_completedXiNumerator,
  ``RiemannZeta.GuthMaynard.completedXiNumerator_eq,
  ``RiemannZeta.GuthMaynard.one_sub_afeCriticalPoint,
  ``RiemannZeta.GuthMaynard.afeCriticalPoint_ne_zero,
  ``RiemannZeta.GuthMaynard.afeCriticalPoint_ne_one,
  ``RiemannZeta.GuthMaynard.afePoleNormalization_ne_zero,
  ``RiemannZeta.GuthMaynard.smoothZetaSqContourNumerator_zero,
  ``RiemannZeta.GuthMaynard.differentiable_smoothZetaSqContourNumerator,
  ``RiemannZeta.GuthMaynard.smoothZetaSqContourNumerator_neg,
  ``RiemannZeta.GuthMaynard.smoothZetaSqContourIntegrand_neg,
  ``RiemannZeta.GuthMaynard.hIntegral_smoothZetaSq_bottom,
  ``RiemannZeta.GuthMaynard.vIntegral_smoothZetaSq_left,
  ``RiemannZeta.GuthMaynard.smoothZetaSq_finiteRectangle,
  ``RiemannZeta.GuthMaynard.smoothZetaSqAFE_truncated_native,
  ``RiemannZeta.GuthMaynard.one_add_norm_afeCriticalPoint_add_horizontal_le,
  ``RiemannZeta.GuthMaynard.exists_smoothZetaSqContourIntegrand_horizontal_bound,
  ``RiemannZeta.GuthMaynard.tendsto_hIntegral_smoothZetaSq_top_zero,
  ``RiemannZeta.GuthMaynard.tendsto_hIntegral'_smoothZetaSq_top_zero,
  ``RiemannZeta.GuthMaynard.smoothZetaSqAFE_vertical_limit_native,
  ``RiemannZeta.GuthMaynard.smoothZetaSqAFE_native,
  ``RiemannZeta.GuthMaynard.completedRiemannZeta_eq_zeta_mul_GammaR,
  ``RiemannZeta.GuthMaynard.afeGammaNormalization_ne_zero,
  ``RiemannZeta.GuthMaynard.norm_hughesYoungPolynomialRatio_le,
  ``RiemannZeta.GuthMaynard.norm_hughesYoungGammaRatio_le,
  ``RiemannZeta.GuthMaynard.norm_hughesYoungArchimedeanWeight_le,
  ``RiemannZeta.GuthMaynard.norm_hughesYoungArchimedeanWeight_le_gaussian,
  ``RiemannZeta.GuthMaynard.integrable_hughesYoungWeightEnvelope,
  ``RiemannZeta.GuthMaynard.smoothZetaSqDivisorContourIntegrand_zeroLine_eq_weight,
  ``RiemannZeta.GuthMaynard.smoothZetaSqAFE_zeta_vertical_limit_native,
  ``RiemannZeta.GuthMaynard.smoothZetaSqContourIntegrand_eq_divisorContour,
  ``RiemannZeta.GuthMaynard.smoothZetaSqAFE_divisor_vertical_limit_native,
  ``RiemannZeta.GuthMaynard.twistedFourthMomentDiagonal_native,
  ``RiemannZeta.GuthMaynard.smoothTwistedDiagonalFiber_le,
  ``RiemannZeta.GuthMaynard.smoothTwistedDiagonalMajorant_le,
  ``RiemannZeta.GuthMaynard.norm_smoothTwistedWeightedDiagonal_le_mul,
  ``RiemannZeta.GuthMaynard.norm_smoothTwistedWeightedDiagonal_le,
  ``RiemannZeta.GuthMaynard.norm_integral_hughesYoungArchimedeanWeight_le,
  ``RiemannZeta.GuthMaynard.norm_hughesYoungWeightedDiagonalSlice_le,
  ``RiemannZeta.GuthMaynard.quadraticDivisorShift_eq_zero_iff,
  ``RiemannZeta.GuthMaynard.quadraticDivisorShift_mem_interval,
  ``RiemannZeta.GuthMaynard.finiteQuadraticDivisorOffDiagonal_eq_sum_shifts,
  ``RiemannZeta.GuthMaynard.kloostermanSum_eq_kloostermanSumZMod,
  ``RiemannZeta.GuthMaynard.kloostermanSum_zero_right,
  ``RiemannZeta.GuthMaynard.kloostermanSum_comm,
  ``RiemannZeta.GuthMaynard.zmod_dft_parseval,
  ``RiemannZeta.GuthMaynard.kloostermanSumZMod_mean_square,
  ``RiemannZeta.GuthMaynard.norm_kloostermanSum_le_totient,
  ``RiemannZeta.GuthMaynard.norm_ramanujanSum_le_totient,
  ``RiemannZeta.GuthMaynard.norm_finiteQuadraticDivisorSum_le,
  ``RiemannZeta.GuthMaynard.exists_gmSmoothCutoff,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.nonneg,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.bounded,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.equals_one,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.support,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.mk.injEq,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.mk.inj,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.smooth,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.mk.sizeOf_spec,
  ``RiemannZeta.GuthMaynard.GMSmoothCutoff.exists_iteratedFDeriv_bound,
  ``RiemannZeta.GuthMaynard.approximateAdditiveQuadruples_mono,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_mono,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_eq_zero_of_neg,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_nonneg,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_le_card_pow_four,
  ``RiemannZeta.GuthMaynard.card_sq_le_approxAddEnergy,
  ``RiemannZeta.GuthMaynard.gmR_one,
  ``RiemannZeta.GuthMaynard.norm_gmR_le_card,
  ``RiemannZeta.GuthMaynard.gmR_reciprocal,
  ``RiemannZeta.GuthMaynard.norm_gmR_reciprocal,
  ``RiemannZeta.GuthMaynard.mapAdditiveQuadruple_translate_mem,
  ``RiemannZeta.GuthMaynard.mapAdditiveQuadruple_untranslate_mem,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_translate,
  ``RiemannZeta.GuthMaynard.mapAdditiveQuadruple_scale_mem,
  ``RiemannZeta.GuthMaynard.mapAdditiveQuadruple_unscale_mem,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_scale,
  ``RiemannZeta.GuthMaynard.gmAffineImage_eq_translate_scale,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_affine,
  ``RiemannZeta.GuthMaynard.floorAdditiveDefect_mem_Icc,
  ``RiemannZeta.GuthMaynard.approxAddEnergy_one_eq_sum_floorEnergy,
  ``RiemannZeta.GuthMaynard.floor_injective_on_of_separated,
  ``RiemannZeta.GuthMaynard.approxFloorEnergy_zero_le_addEnergy,
  ``RiemannZeta.GuthMaynard.gmMatrix_mulVec_apply,
  ``RiemannZeta.GuthMaynard.gmSmoothDirichletPoly_restricted_eq_sum,
  ``RiemannZeta.GuthMaynard.gmSourcePieces_partition,
  ``RiemannZeta.GuthMaynard.gmSourceLeftPiece_mem_dyadic,
  ``RiemannZeta.GuthMaynard.gmSourceMiddlePiece_mem_dyadic,
  ``RiemannZeta.GuthMaynard.gmSourceRightPiece_mem_dyadic,
  ``RiemannZeta.GuthMaynard.gmSourceLeftPiece_mem_core,
  ``RiemannZeta.GuthMaynard.gmSourceMiddlePiece_mem_core,
  ``RiemannZeta.GuthMaynard.gmSourceRightPiece_mem_core,
  ``RiemannZeta.GuthMaynard.sourceDirichletPoly_eq_three_gmSmooth,
  ``RiemannZeta.GuthMaynard.exists_large_gmSmooth_of_source_large,
  ``RiemannZeta.GuthMaynard.source_large_values_localize_to_matrix,
  ``RiemannZeta.GuthMaynard.gmMatrix_sample_energy_lower,
  ``RiemannZeta.GuthMaynard.gmCoefficient_energy_le,
  ``RiemannZeta.GuthMaynard.gmMatrix_energy_le_operatorNorm,
  ``RiemannZeta.GuthMaynard.gm_largeValues_card_le_operatorNorm,
  ``RiemannZeta.GuthMaynard.gmMatrix_mul_conjTranspose_apply,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_apply_eq_phase_sum,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_isHermitian,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_posSemidef,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_eigenvalue_nonneg,
  ``RiemannZeta.GuthMaynard.gmMatrixSingularValue_nonneg,
  ``RiemannZeta.GuthMaynard.gmMatrixSingularValue_sq,
  ``RiemannZeta.GuthMaynard.gmMatrixSingularValue_sixth,
  ``RiemannZeta.GuthMaynard.Matrix.IsHermitian.l2_opNorm_le_eigenvalue,
  ``RiemannZeta.GuthMaynard.exists_gmMatrixOperatorNorm_le_singularValue,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_trace_expand,
  ``RiemannZeta.GuthMaynard.matrix_trace_cube_expand,
  ``RiemannZeta.GuthMaynard.Matrix.IsHermitian.trace_cube_eq_sum_eigenvalues_cube,
  ``RiemannZeta.GuthMaynard.sixthMoment_dispersion_nonneg,
  ``RiemannZeta.GuthMaynard.sixthMoment_tail_lower,
  ``RiemannZeta.GuthMaynard.coordinate_sixth_le_trace_dispersion_max,
  ``RiemannZeta.GuthMaynard.sixthRoot_dispersion_bound,
  ``RiemannZeta.GuthMaynard.sixthRoot_cubic_bound,
  ``RiemannZeta.GuthMaynard.coordinate_le_trace_dispersion,
  ``RiemannZeta.GuthMaynard.gmMatrix_singularValue_sixth_le_dispersion_max,
  ``RiemannZeta.GuthMaynard.gmMatrix_singularValue_le_trace_dispersion,
  ``RiemannZeta.GuthMaynard.gmMatrix_operatorNorm_le_trace_dispersion,
  ``RiemannZeta.GuthMaynard.gmSmoothCutoff_eq_zero_of_lt_one,
  ``RiemannZeta.GuthMaynard.gmSmoothCutoff_eq_zero_at_one,
  ``RiemannZeta.GuthMaynard.gmSmoothCutoff_eq_zero_at_two,
  ``RiemannZeta.GuthMaynard.gmSmoothCutoff_eq_zero_of_le_one,
  ``RiemannZeta.GuthMaynard.gmSmoothCutoff_eq_zero_of_two_le,
  ``RiemannZeta.GuthMaynard.contDiff_gmTraceKernel,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_gmTraceKernel,
  ``RiemannZeta.GuthMaynard.gmTraceKernelSchwartz_apply,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_fixed_t_decay,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_eq_mellin,
  ``RiemannZeta.GuthMaynard.mellinConvergent_gmCutoffSq_one,
  ``RiemannZeta.GuthMaynard.contDiff_gmMellinKernel,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_gmMellinKernel,
  ``RiemannZeta.GuthMaynard.gmMellinKernelSchwartz_apply,
  ``RiemannZeta.GuthMaynard.verticalIntegrable_mellin_gmCutoffSq_one,
  ``RiemannZeta.GuthMaynard.gmCutoffSq_mellinInversion,
  ``RiemannZeta.GuthMaynard.gmTraceKernel_mellinInversion,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_eq_mellinKernel_fourier,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_uniform_decay,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_uniform_decay_source,
  ``RiemannZeta.GuthMaynard.contDiff_gmScaledTraceKernel,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_gmScaledTraceKernel,
  ``RiemannZeta.GuthMaynard.gmScaledTraceKernelSchwartz_apply,
  ``RiemannZeta.GuthMaynard.gmScaledTraceKernel_fourier,
  ``RiemannZeta.GuthMaynard.gmScaledTraceKernel_poisson,
  ``RiemannZeta.GuthMaynard.gmTraceKernel_poisson,
  ``RiemannZeta.GuthMaynard.gmTraceKernel_tsum_eq_intBlock,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_zero_eq_cutoffL2Sq,
  ``RiemannZeta.GuthMaynard.gmTraceKernel_zero_tsum_eq_column_sum,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_trace_eq_cutoff_sum,
  ``RiemannZeta.GuthMaynard.gmScaledTraceFourier_summable,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_nonzero_pointwise_bound,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_zero_nonzero_tail_bound,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_trace_poisson_expand,
  ``RiemannZeta.GuthMaynard.gmMatrix_hilbertSchmidt_trace_estimate,
  ``RiemannZeta.GuthMaynard.gmMatrix_hilbertSchmidt_trace_estimate_hundred,
  ``RiemannZeta.GuthMaynard.gmCpowDerivativeCoeff_zero,
  ``RiemannZeta.GuthMaynard.gmCpowDerivativeCoeff_succ,
  ``RiemannZeta.GuthMaynard.iteratedDeriv_ofReal_cpow,
  ``RiemannZeta.GuthMaynard.norm_gmCpowDerivativeCoeff_le,
  ``RiemannZeta.GuthMaynard.norm_iteratedDeriv_ofReal_cpow_mul_I_le,
  ``RiemannZeta.GuthMaynard.gmTraceKernel_uniform_iteratedFDeriv,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_uniform_decay,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_far_frequency_decay,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_neg_eq_conj,
  ``RiemannZeta.GuthMaynard.gmCutoffSq_eq_verticalMellinIntegral,
  ``RiemannZeta.GuthMaynard.gmRescaledCutoffIntegral_eq_mellinReflection,
  ``RiemannZeta.GuthMaynard.hasDerivAt_gmReflectionPrimitive,
  ``RiemannZeta.GuthMaynard.hasDerivAt_gmReflectionRatio,
  ``RiemannZeta.GuthMaynard.hasDerivAt_gmReflectionRatioReal,
  ``RiemannZeta.GuthMaynard.gmReflectionRatio_mul_primitiveDeriv,
  ``RiemannZeta.GuthMaynard.gmReflectionIntegral_eq_parts,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionPrimitive,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionRatio,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegrand,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_le_endpoint_variation,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_le_left,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_le_right,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_le_length_div,
  ``RiemannZeta.GuthMaynard.intervalIntegrable_gmReflectionIntegrand,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_le_ten_div_sqrt,
  ``RiemannZeta.GuthMaynard.norm_weighted_gmReflectionIntegral_le,
  ``RiemannZeta.GuthMaynard.hasDerivAt_gmReflectionPowerWeight,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionPowerWeight,
  ``RiemannZeta.GuthMaynard.norm_powerWeighted_gmReflectionIntegral_le,
  ``RiemannZeta.GuthMaynard.star_gmReflectionPowerWeight,
  ``RiemannZeta.GuthMaynard.norm_conj_powerWeighted_gmReflectionIntegral_le,
  ``RiemannZeta.GuthMaynard.gmCutoffMellin_eq_fourier,
  ``RiemannZeta.GuthMaynard.continuous_gmCutoffMellin,
  ``RiemannZeta.GuthMaynard.gmCutoffMellin_polynomial_decay,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_eq_interval,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_rescale,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_eq_mellinReflection,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_eq_reflectedMode,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_neg_eq_mellinReflection,
  ``RiemannZeta.GuthMaynard.gmSmoothReflection_native,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_eq_integral_dualMode,
  ``RiemannZeta.GuthMaynard.norm_gmPositiveDualDirichletPoly_le,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_pos_core_le,
  ``RiemannZeta.GuthMaynard.norm_gmReflectionIntegral_neg_core_le,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_sum_eq_integral_dualPoly,
  ``RiemannZeta.GuthMaynard.sum_gmPositiveDualModeIntegrand_eq,
  ``RiemannZeta.GuthMaynard.norm_gmTraceFourier_pos_sum_le_dualPoly,
  ``RiemannZeta.GuthMaynard.norm_gmTraceFourier_neg_sum_le_dualPoly,
  ``RiemannZeta.GuthMaynard.norm_gmTraceFourier_signed_sum_le_dualPoly,
  ``RiemannZeta.GuthMaynard.gmTraceFourier_pos_sum_eq_mellinReflection,
  ``RiemannZeta.GuthMaynard.norm_gmTraceFourier_pos_le_mellinReflection,
  ``RiemannZeta.GuthMaynard.norm_gmSmoothReflection_native_le,
  ``RiemannZeta.GuthMaynard.gmScaledTraceMode_summable,
  ``RiemannZeta.GuthMaynard.gmScaledTraceMode_tsum_decompose,
  ``RiemannZeta.GuthMaynard.gmTraceNonzeroTailAt_bound,
  ``RiemannZeta.GuthMaynard.gmTraceZeroMode_bound,
  ``RiemannZeta.GuthMaynard.gmTraceZeroMode_separated_bound,
  ``RiemannZeta.GuthMaynard.gmTraceKernel_tsum_eq_column_sum,
  ``RiemannZeta.GuthMaynard.gmMatrix_gram_apply_eq_phase_mul_fourier_tsum,
  ``RiemannZeta.GuthMaynard.gmTraceZeroMode_zero,
  ``RiemannZeta.GuthMaynard.gmCubicZeroMode_eq_main_add_remainder,
  ``RiemannZeta.GuthMaynard.gmMatrix_cubic_trace_poisson_expand,
  ``RiemannZeta.GuthMaynard.gmMatrix_cubic_trace_split,
  ``RiemannZeta.GuthMaynard.gmSeparated_card_le_two_height,
  ``RiemannZeta.GuthMaynard.gmCubicS1_quantitative,
  ``RiemannZeta.GuthMaynard.gmCubicS1_power_decay,
  ``RiemannZeta.GuthMaynard.gmCubicS1_estimate,
  ``RiemannZeta.GuthMaynard.gmCubicZeroRemainder_quantitative,
  ``RiemannZeta.GuthMaynard.gmCubicZeroMode_main_term,

  -- Shitlist #15: logarithmic phase and finite Weyl-differencing foundation
  ``RiemannZeta.GuthMaynard.norm_unitaryPhase,
  ``RiemannZeta.GuthMaynard.unitaryPhase_add,
  ``RiemannZeta.GuthMaynard.unitaryPhase_sub,
  ``RiemannZeta.GuthMaynard.unitaryPhase_logarithmicPhase_eq_cpow,
  ``RiemannZeta.GuthMaynard.logarithmicSum_eq_cpow,
  ``RiemannZeta.GuthMaynard.norm_phaseSum_le_card,
  ``RiemannZeta.GuthMaynard.norm_logarithmicSum_le_length,
  ``RiemannZeta.GuthMaynard.hasDerivAt_logarithmicPhase,
  ``RiemannZeta.GuthMaynard.hasDerivAt_logarithmicPhase_deriv,
  ``RiemannZeta.GuthMaynard.hasDerivAt_logarithmicPhase_secondDeriv,
  ``RiemannZeta.GuthMaynard.phaseResolvent_eq,
  ``RiemannZeta.GuthMaynard.hasDerivAt_real_cot,
  ``RiemannZeta.GuthMaynard.strictAntiOn_real_cot,
  ``RiemannZeta.GuthMaynard.sin_half_lower,
  ``RiemannZeta.GuthMaynard.norm_phaseResolvent_le,
  ``RiemannZeta.GuthMaynard.norm_phaseResolvent_sub_eq,
  ``RiemannZeta.GuthMaynard.phaseResolvent_variation,
  ``RiemannZeta.GuthMaynard.abs_cot_half_le_norm_phaseResolvent,
  ``RiemannZeta.GuthMaynard.unitaryPhase_resolvent_step,
  ``RiemannZeta.GuthMaynard.finite_resolvent_telescoping,
  ``RiemannZeta.GuthMaynard.norm_sum_le_resolvent_variation,
  ``RiemannZeta.GuthMaynard.kusminLandau_one_period,
  ``RiemannZeta.GuthMaynard.unitaryPhase_int_mul_two_pi,
  ``RiemannZeta.GuthMaynard.unitaryPhase_sub_int_mul_two_pi,
  ``RiemannZeta.GuthMaynard.kusminLandau_one_period_decreasing,
  ``RiemannZeta.GuthMaynard.kusminLandau_interval,
  ``RiemannZeta.GuthMaynard.norm_sum_sq_le_card_mul_sum_norm_sq,
  ``RiemannZeta.GuthMaynard.finite_weyl_differencing,
  ``RiemannZeta.GuthMaynard.sum_paddedShift_eq,
  ``RiemannZeta.GuthMaynard.sum_norm_sq_paddedShift_eq,
  ``RiemannZeta.GuthMaynard.interval_weyl_differencing,

  -- Shitlist #15: multi-period B-process and second-order bridge
  ``RiemannZeta.GuthMaynard.discrete_growth_lower,
  ``RiemannZeta.GuthMaynard.monotone_of_step,
  ``RiemannZeta.GuthMaynard.filter_card_bound,
  ``RiemannZeta.GuthMaynard.sum_Icc_eq_shifted_range,
  ``RiemannZeta.GuthMaynard.kusminLandau_good_fiber,
  ``RiemannZeta.GuthMaynard.periodIndex_bounds,
  ``RiemannZeta.GuthMaynard.periodIndex_mono,
  ``RiemannZeta.GuthMaynard.period_count_bound,
  ``RiemannZeta.GuthMaynard.discrete_growth_upper,
  ``RiemannZeta.GuthMaynard.norm_phase_sum_finset_le_card,
  ``RiemannZeta.GuthMaynard.vanDerCorput_second_derivative,
  ``RiemannZeta.GuthMaynard.vanDerCorput_B_process,
  ``RiemannZeta.GuthMaynard.second_order_mean_value,

  -- Shitlist #15: logarithmic A-after-B and explicit Weyl exponent
  ``RiemannZeta.GuthMaynard.interval_weyl_differencing_complex,
  ``RiemannZeta.GuthMaynard.hasDerivAt_logarithmicDifferencePhase,
  ``RiemannZeta.GuthMaynard.hasDerivAt_logarithmicDifferencePhase_deriv,
  ``RiemannZeta.GuthMaynard.logarithmicDifferencePhase_secondDifference,
  ``RiemannZeta.GuthMaynard.logarithmicDifferenceCurvature_bounds,
  ``RiemannZeta.GuthMaynard.logarithmicDifference_secondDifference_bounds,
  ``RiemannZeta.GuthMaynard.logarithmicDifference_B_process,
  ``RiemannZeta.GuthMaynard.norm_integerLogarithmicTerm,
  ``RiemannZeta.GuthMaynard.padded_logarithmic_correlation_eq,
  ``RiemannZeta.GuthMaynard.logarithmicCorrelationBound_nonneg,
  ``RiemannZeta.GuthMaynard.padded_logarithmic_correlation_norm_le_of_lt,
  ``RiemannZeta.GuthMaynard.padded_logarithmic_correlation_norm_le,
  ``RiemannZeta.GuthMaynard.logarithmic_weyl_AB_process,
  ``RiemannZeta.GuthMaynard.weylShiftLength_le,
  ``RiemannZeta.GuthMaynard.integerLogarithmicSum_eq,
  ``RiemannZeta.GuthMaynard.logarithmic_weyl_optimized,
  ``RiemannZeta.GuthMaynard.norm_logarithmicSum_le_weylBound,
  ``RiemannZeta.GuthMaynard.vdc_product_bound,
  ``RiemannZeta.GuthMaynard.logarithmicCorrelationBound_le_simple,
  ``RiemannZeta.GuthMaynard.logarithmicCorrelationBound_le_uniform,
  ``RiemannZeta.GuthMaynard.logarithmic_weyl_AB_process_simple,
  ``RiemannZeta.GuthMaynard.simpleLogarithmicCorrelationBound_le_four_hundred,
  ``RiemannZeta.GuthMaynard.logarithmic_weyl_exponent_pair_with_shift,
  ``RiemannZeta.GuthMaynard.classicalWeylShiftLength_spec,
  ``RiemannZeta.GuthMaynard.logarithmic_weyl_exponent_pair,
  ``RiemannZeta.GuthMaynard.logarithmic_weyl_exponent_pair_prefix,

  -- Shitlist #15: critical-line weighted block
  ``RiemannZeta.GuthMaynard.norm_weighted_sum_le_of_antitone,
  ``RiemannZeta.GuthMaynard.logarithmicSum_eq_sum_range,
  ``RiemannZeta.GuthMaynard.criticalLineTerm_eq_cpow,
  ``RiemannZeta.GuthMaynard.criticalLineWeylBlock_eq_cpow,
  ``RiemannZeta.GuthMaynard.norm_criticalLineWeylBlock_le,

  -- Shitlist #15 Package C: finite Montgomery--Halasz--Huxley large values
  ``RiemannZeta.GuthMaynard.dyadicInterval_eq_Ico_succ,
  ``RiemannZeta.GuthMaynard.logarithmicKernel_eq_logarithmicSum,
  ``RiemannZeta.GuthMaynard.logarithmicKernel_eq_shifted_phaseSum,
  ``RiemannZeta.GuthMaynard.logarithmicKernel_zero,
  ``RiemannZeta.GuthMaynard.norm_logarithmicKernel_zero,
  ``RiemannZeta.GuthMaynard.logarithmicKernel_neg,
  ``RiemannZeta.GuthMaynard.norm_logarithmicKernel_abs,
  ``RiemannZeta.GuthMaynard.norm_logarithmicKernel_le_div,
  ``RiemannZeta.GuthMaynard.logarithmicPhase_secondDifference_bounds,
  ``RiemannZeta.GuthMaynard.norm_logarithmicKernel_le_sqrt,
  ``RiemannZeta.GuthMaynard.norm_phaseAlign_le_one,
  ``RiemannZeta.GuthMaynard.phaseAlign_mul,
  ``RiemannZeta.GuthMaynard.norm_sum_mul_sq_le,
  ``RiemannZeta.GuthMaynard.sum_norm_sq_sum_le_gram,
  ``RiemannZeta.GuthMaynard.logarithmicPhase_gram_eq_kernel,
  ``RiemannZeta.GuthMaynard.halasz_montgomery_duality,
  ``RiemannZeta.GuthMaynard.separated_annulus_card_le_two,
  ``RiemannZeta.GuthMaynard.sum_inv_distance_near_le_harmonic,
  ``RiemannZeta.GuthMaynard.logarithmicKernel_row_sum_le,
  ``RiemannZeta.GuthMaynard.local_classical_large_values,
  ``RiemannZeta.GuthMaynard.classical_large_values_of_local_scale,
  ``RiemannZeta.GuthMaynard.dyadic_energy_le_length,
  ``RiemannZeta.GuthMaynard.threshold_sq_le_length_mul_energy,
  ``RiemannZeta.GuthMaynard.classical_large_values_sixth_branch,
  ``RiemannZeta.GuthMaynard.classical_large_values_second_branch,
  ``RiemannZeta.GuthMaynard.classical_large_values_with_harmonic,
  ``RiemannZeta.GuthMaynard.classical_montgomery_halasz_huxley_native,
  ``harmonic_eq_sum_Icc0_aux,
  ``ZetaSum_aux1_5d,
  ``DerivUpperBnd_aux7_integral_eq,
  ``deriv_eqOn_of_eqOn_punctured,
  ``integrableOn_of_Zeta0_fun,
  ``ZetaSum_aux1,
  ``xpos_of_uIcc,
  ``ZetaSum_aux1_5,
  ``DerivUpperBnd_aux7_3',
  ``norm_complex_log_ofNat,
  ``Complex.cpow_inv_tendsto,
  ``ZetaBnd_aux2,
  ``derivative_const_plus_product,
  ``DerivUpperBnd_aux4,
  ``Ioi_union_Iio_mem_cocompact,
  ``ZetaLowerBound1_aux1,
  ``ZetaBnd_aux1a,
  ``dlog_riemannZeta_bdd_on_vertical_lines_generalized,
  ``DerivZeta0EqDerivZeta,
  ``DerivUpperBnd_aux7_3,
  ``ZetaDerivUpperBnd',
  ``HasDerivAtZeta0,
  ``Zeta0EqZeta,
  ``deriv_inv_sub,
  ``ResidueMult,
  ``one_div_cpow_eq_cpow_neg,
  ``ZetaLowerBound3_aux2,
  ``ZetaInvBound1,
  ``measurable_floor_add_half_sub,
  ``logt_gt_one,
  ``logDerivResidue',
  ``finsetSum_tendsto_tsum,
  ``Nat.self_div_floor_bound,
  ``deriv_f_minus_A_inv_sub_clean,
  ``Finset.Icc_eq_Ico,
  ``ZetaSum_aux1_1',
  ``Finset.Ioc_eq_Icc,
  ``Tendsto_nhdsWithin_punctured_map_add,
  ``ZetaUpperBnd',
  ``ZetaInvBound2,
  ``ZetaInvBnd_aux',
  ``ZetaLowerBound3,
  ``Tendsto_nhdsWithin_punctured_add,
  ``isOpen_aux,
  ``UpperBnd_aux2,
  ``logDerivResidue'',
  ``ZetaDerivUpperBnd,
  ``triv_bound_zeta,
  ``DerivUpperBnd_aux2,
  ``hasDerivAt_Zeta0Integral,
  ``norm_add₅_le,
  ``div_rpow_eq_rpow_div_neg,
  ``DerivUpperBnd_aux1,
  ``ZetaBnd_aux1b,
  ``ZetaSum_aux1φderiv,
  ``ZetaCont,
  ``ZetaLowerBound3_aux3,
  ``riemannZeta0_zero_aux,
  ``ZetaLowerBound3_aux1,
  ``ZetaLowerBound2,
  ``ZetaSum_aux1_4,
  ``ZetaBnd_aux1p,
  ``HasDerivAt_cpow_over_var,
  ``DerivUpperBnd_aux5,
  ``analyticAt_riemannZeta,
  ``HasDerivAt_neg_cpow_over2,
  ``lt_trans₄,
  ``ZetaSum_aux1_5b,
  ``DerivUpperBnd_aux7_5,
  ``nonZeroOfBddAbove,
  ``DerivUpperBnd_aux3,
  ``Real.log_natCast_monotone,
  ``UpperBnd_aux3,
  ``norm_zeta_product_ge_one,
  ``ZetaSum_aux1_5c,
  ``riemannZetaLogDerivResidueBigO,
  ``ZetaNoZerosInBox,
  ``lt_abs_mem_cocompact,
  ``harmonic_eq_sum_Icc0,
  ``div_rpow_neg_eq_rpow_div,
  ``DerivUpperBnd_aux7_2,
  ``ZetaLowerBound3_aux4,
  ``div_cpow_eq_cpow_neg,
  ``sum_eq_int_deriv,
  ``Finset.Ioc_eq_Ico,
  ``LogDerivZetaHoloOn,
  ``isPathConnected_aux,
  ``ZetaBnd_aux1,
  ``mul_le_mul₃,
  ``UpperBnd_aux5,
  ``ZetaInvBnd_aux,
  ``Zeta_diff_Bnd,
  ``ZetaSum_aux1_1,
  ``norm_add₆_le,
  ``ZetaSum_aux1_3,
  ``HolomorphicOn_riemannZeta0,
  ``LogDerivZetaHolcLargeT,
  ``deriv_fun_re,
  ``analytic_deriv_bounded_near_point,
  ``ZetaSum_aux1₁,
  ``ZetaUpperBnd,
  ``ZetaLowerBound3_aux5,
  ``Zeta_eq_int_derivZeta,
  ``ZetaSum_aux2,
  ``differentiableAt_deriv_riemannZeta,
  ``Complex.cpow_tendsto,
  ``ZetaSum_aux1_4',
  ``DerivUpperBnd_aux7,
  ``ZetaNoZerosOn1Line,
  ``Real.differentiableAt_cpow_const_of_ne,
  ``ZetaLowerBnd,
  ``UpperBnd_aux6,
  ``riemannZetaLogDerivResidue,
  ``ResidueOfTendsTo,
  ``riemannZetaResidue,
  ``LogDerivZetaBndUnif,
  ``ZetaSum_aux1_2,
  ``ZetaSum_aux1_5a,
  ``LogDerivZetaHolcSmallT,
  ``ZetaInvBnd_aux2,
  ``DerivUpperBnd_aux7_4,
  ``le_trans₄,
  ``HolomorphicOn_riemannZeta,
  ``DerivUpperBnd_aux7_nonneg,
  ``ZetaNear1BndFilter,
  ``riemannZeta_isBigO_near_one_horizontal,
  ``ZetaZeroFree,
  ``integrableOn_of_Zeta0_fun_log,
  ``ZetaNear1BndExact,
  ``ZetaLowerBound1,
  ``LogDerivZetaBnd,
  ``UpperBnd_aux,
  ``ZetaSum_aux1φDiff,
  ``DerivUpperBnd_aux6,
  ``DerivUpperBnd_aux7_tendsto,
  ``Complex.one_div_cpow_eq,
  ``ZetaInvBnd,
  ``integrable_log_over_pow,
  ``riemannZeta0_apply,
  ``div_rpow_eq_rpow_neg,
  ``ZetaSum_aux1derivφCont,
  ``BddAbove_to_IsBigO,
  ``logDerivResidue,
  ``Finset.Icc0_eq,
  ``summable_complex_then_summable_real_part,
  ``DerivUpperBnd_aux7_1,
  ``ZetaSum_aux2a,
  ``ZetaSum_aux3,

  -- Classical finite zero-density transfer and powering
  ``RiemannZeta.GuthMaynard.classical_large_values_second_branch_unrestricted,
  ``RiemannZeta.GuthMaynard.classical_large_values_with_harmonic_unrestricted,
  ``RiemannZeta.GuthMaynard.truncatedMoebius_one,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_one,
  ``RiemannZeta.GuthMaynard.norm_sharpMollifiedCoeff_one_le_one,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_eq_zero_of_mul_lt,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_hasFiniteSupport,
  ``RiemannZeta.GuthMaynard.norm_sharpMollifiedCoeff_le_divisors_card,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_bound,
  ``RiemannZeta.GuthMaynard.sharpMollifiedCoeff_LSeries_eq_sum,
  ``RiemannZeta.GuthMaynard.zetaPartialSum_mul_zetaMollifier_eq_one_add_tail,
  ``RiemannZeta.GuthMaynard.norm_zetaMollifier_le_sum_rpow,
  ``RiemannZeta.GuthMaynard.norm_sharpMollifiedTail_ge,
  ``RiemannZeta.GuthMaynard.norm_finiteDirichletSeries_le_mass,
  ``RiemannZeta.GuthMaynard.differentiable_finiteDirichletSeries_add,
  ``RiemannZeta.GuthMaynard.localizedFiniteDirichlet_le_mass,
  ``RiemannZeta.GuthMaynard.localizedFiniteDirichlet_halfPlane_bound,
  ``RiemannZeta.GuthMaynard.exists_nearby_large_value_finiteDirichlet,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_apply,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTailSupport_pos,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_mass_le_sq,
  ``RiemannZeta.GuthMaynard.norm_sharpMollifiedTail_finiteSeries_ge,
  ``RiemannZeta.GuthMaynard.rpow_mass_mul_localizer_lt_three_eighths,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_beta_removal,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_mass_le_pow_six,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_beta_removal_of_error,
  ``RiemannZeta.GuthMaynard.sum_rpow_neg_le_sqrt_mul_sqrt_harmonic,
  ``RiemannZeta.GuthMaynard.sharpMollified_error_le_majorant,
  ``RiemannZeta.GuthMaynard.tendsto_sharpMollified_error_majorant,
  ``RiemannZeta.GuthMaynard.eventually_sharpMollified_error_majorant_le_half,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_beta_removal_native,
  ``RiemannZeta.GuthMaynard.sharpMollifiedLineCoeff_term,
  ``RiemannZeta.GuthMaynard.sharpMollifiedTail_eq_wideDirichletPoly,
  ``RiemannZeta.GuthMaynard.exists_sharpMollified_large_dyadic_block,
  ``RiemannZeta.GuthMaynard.finite_shifted_dyadic_witness_extraction,
  ``RiemannZeta.GuthMaynard.zeroUnitBin_multiplicity_le_cap,
  ``RiemannZeta.GuthMaynard.extract_sharpMollified_dyadic_witness_native,
  ``RiemannZeta.GuthMaynard.norm_normalizedSharpMollifiedLineCoeff_le_one,
  ``RiemannZeta.GuthMaynard.dirichletPoly_normalizedSharpMollifiedLineCoeff,
  ``RiemannZeta.GuthMaynard.extracted_sharpMollified_block_card_bound,
  ``RiemannZeta.GuthMaynard.classicalZetaLongTail_eq_finiteDirichletSeries,
  ``RiemannZeta.GuthMaynard.classicalZetaLongTailSupport_pos,
  ``RiemannZeta.GuthMaynard.classicalZetaLongTail_mass_le,
  ``RiemannZeta.GuthMaynard.classicalZetaLongLineCoeff_term,
  ``RiemannZeta.GuthMaynard.classicalZetaLongTail_eq_wideDirichletPoly,
  ``RiemannZeta.GuthMaynard.exists_classicalZetaLong_large_dyadic_block,
  ``RiemannZeta.GuthMaynard.classicalZetaPartialSum_eq_short_add_long,
  ``RiemannZeta.GuthMaynard.classical_typeI_or_typeII_of_full_sum_small,
  ``RiemannZeta.GuthMaynard.classical_typeI_of_short_sum_large,
  ``RiemannZeta.GuthMaynard.classical_typeII_of_short_sum_small,
  ``RiemannZeta.GuthMaynard.classical_typeI_or_typeII_quantitative,
  ``RiemannZeta.GuthMaynard.norm_zetaMollifier_le_length,
  ``RiemannZeta.GuthMaynard.zeta_zero_classical_typeI_or_typeII,
  ``RiemannZeta.GuthMaynard.sum_filter_add_sum_filter_not_eq_sum,
  ``RiemannZeta.GuthMaynard.exists_multiplicity_dominant_binary_branch,
  ``RiemannZeta.GuthMaynard.rpow_mass_mul_localizer_lt_three_fourths_mul_rpow,
  ``RiemannZeta.GuthMaynard.finiteDirichlet_beta_removal_power_threshold,
  ``RiemannZeta.GuthMaynard.finite_common_scale_binary_branch_extraction,
  ``RiemannZeta.GuthMaynard.extract_classical_dichotomy_of_scale_bounds,
  ``RiemannZeta.GuthMaynard.eventually_classical_dichotomy_cutoffs,
  ``RiemannZeta.GuthMaynard.classical_dichotomy_mass_and_threshold_bounds,
  ``RiemannZeta.GuthMaynard.eventually_classical_short_product_le_quarter,
  ``RiemannZeta.GuthMaynard.sharp_full_error_le_power_majorant,
  ``RiemannZeta.GuthMaynard.eventually_sharp_full_error_le_split_threshold,
  ``RiemannZeta.GuthMaynard.classical_typeI_typeII_dichotomy_native,
  ``RiemannZeta.GuthMaynard.finite_polynomial_power_identity,
  ``RiemannZeta.GuthMaynard.finitePowCoeff_lower_endpoint_eq_zero,
  ``RiemannZeta.GuthMaynard.finite_polynomial_power_identity_Ioc,
  ``RiemannZeta.GuthMaynard.finitePowCoeff_bound,
  ``RiemannZeta.GuthMaynard.wideDirichletPoly_finitePoweredLineCoeffs,
  ``RiemannZeta.GuthMaynard.norm_finitePoweredLineCoeffs_le,
  ``RiemannZeta.GuthMaynard.norm_normalizedFinitePoweredCoeffs_le_one,
  ``RiemannZeta.GuthMaynard.wideDirichletPoly_normalizedFinitePoweredCoeffs,
  ``RiemannZeta.GuthMaynard.normalized_finite_powered_wide_lower,
  ``RiemannZeta.GuthMaynard.extract_normalized_finite_powered_block,
  ``RiemannZeta.GuthMaynard.dirichletPoly_sharpMollifiedLineCoeff_eq,
  ``RiemannZeta.GuthMaynard.powered_unit_block_large_values_bound,
  ``RiemannZeta.GuthMaynard.powered_actual_sharpMollified_block_large_values_bound,
  ``RiemannZeta.GuthMaynard.actual_typeII_powered_mhh_native,
  ``RiemannZeta.GuthMaynard.powered_sharp_block_large_values_bound,
  ``RiemannZeta.GuthMaynard.partial_zeta_block_poisson,
  ``RiemannZeta.GuthMaynard.partial_zeta_block_cosine_limit,
  ``RiemannZeta.GuthMaynard.hasDerivAt_reflectionPhase,
  ``RiemannZeta.GuthMaynard.deriv_reflectionPhase,
  ``RiemannZeta.GuthMaynard.hasDerivAt_deriv_reflectionPhase,
  ``RiemannZeta.GuthMaynard.secondDeriv_reflectionPhase,
  ``RiemannZeta.GuthMaynard.reflectionStationaryPoint_pos,
  ``RiemannZeta.GuthMaynard.deriv_reflectionPhase_stationary,
  ``RiemannZeta.GuthMaynard.deriv_reflectionPhase_neg_of_lt_stationary,
  ``RiemannZeta.GuthMaynard.deriv_reflectionPhase_pos_of_stationary_lt,
  ``RiemannZeta.GuthMaynard.deriv_reflectionPhase_neg_frequency_neg,
  ``RiemannZeta.GuthMaynard.secondDeriv_reflectionPhase_pos,
  ``RiemannZeta.GuthMaynard.reflectionPhase_stationary_value,
  ``RiemannZeta.GuthMaynard.reflectionPhase_stationary_rescale,
  ``RiemannZeta.GuthMaynard.reflectionOscillatoryIntegral_stationary_rescale,
  ``RiemannZeta.GuthMaynard.hasDerivAt_stationaryNormalPhase,
  ``RiemannZeta.GuthMaynard.hasDerivAt_deriv_stationaryNormalPhase,
  ``RiemannZeta.GuthMaynard.stationaryNormalPhase_nonneg,
  ``RiemannZeta.GuthMaynard.stationaryNormalPhase_le_sq_div,
  ``RiemannZeta.GuthMaynard.stationaryNormalPhase_le_two_mul_sq,
  ``RiemannZeta.GuthMaynard.stationaryNormalPhase_sq_div_eight_le,
  ``RiemannZeta.GuthMaynard.stationaryNormalPhase_eq_zero_iff,
  ``RiemannZeta.GuthMaynard.secondDeriv_reflectionPhase_stationary,
  ``RiemannZeta.GuthMaynard.cpow_mul_fourier_exp_eq_reflectionPhase,
  ``RiemannZeta.GuthMaynard.reflectionStationaryPoint_mem_Icc_iff,
  ``RiemannZeta.GuthMaynard.reflectionStationaryPoint_mem_dyadic_iff,
  ``RiemannZeta.GuthMaynard.secondDeriv_reflectionPhase_dyadic_bounds,
  ``RiemannZeta.GuthMaynard.norm_logarithmicPhase_prefix_le_div,
  ``RiemannZeta.GuthMaynard.norm_terminalWeightedBlock_le,
  ``RiemannZeta.GuthMaynard.dirichletPoly_classicalZetaLongLineCoeff_eq_terminal,
  ``RiemannZeta.GuthMaynard.norm_terminal_classicalZetaLongLineCoeff_le,
  ``RiemannZeta.GuthMaynard.typeI_scale_lt_height_of_large,
  ``RiemannZeta.GuthMaynard.logarithmic_B_process_majorant_le,
  ``RiemannZeta.GuthMaynard.norm_classicalZetaLongLineCoeff_le_one,
  ``RiemannZeta.GuthMaynard.typeIFourierDeweight_native,
  ``RiemannZeta.GuthMaynard.typeISmoothScaleSplit_native,
  ``RiemannZeta.GuthMaynard.norm_logarithmicPhase_prefix_le_sqrt,
  ``RiemannZeta.GuthMaynard.norm_mediumWeightedBlock_le,
  ``RiemannZeta.GuthMaynard.mediumTypeIBProcess_native,
  ``RiemannZeta.GuthMaynard.mediumTypeILargeValue_false,
  ``RiemannZeta.GuthMaynard.typeIClassicalLargeValues_native,
  ``RiemannZeta.GuthMaynard.typeIEndpointScaleDispatch_native,
  ``RiemannZeta.GuthMaynard.rpow_typeILogarithmicScale_eq,
  ``RiemannZeta.GuthMaynard.endpoint_mhh_at_physical_typeI_scale,
  ``RiemannZeta.GuthMaynard.norm_normalizedClassicalTypeICoeff_le_one,
  ``RiemannZeta.GuthMaynard.dirichletPoly_normalizedClassicalTypeICoeff,
  ``RiemannZeta.GuthMaynard.normalizedClassicalTypeICoeff_large,
  ``RiemannZeta.GuthMaynard.typeI_finite_window_resolution_native,
  ``RiemannZeta.GuthMaynard.typeI_dichotomy_witness_mhh_bound_native,
  ``RiemannZeta.GuthMaynard.actual_typeI_dichotomy_witness_mhh_native,
  ``RiemannZeta.GuthMaynard.actual_typeI_dichotomy_witness_mhh_absorbed_native,
  ``RiemannZeta.GuthMaynard.powered_actual_typeI_block_large_values_bound,
  ``RiemannZeta.GuthMaynard.actual_typeI_absorbed_mhh_native,
  ``RiemannZeta.GuthMaynard.actual_typeI_powered_route_native,
  ``RiemannZeta.GuthMaynard.actual_typeI_weyl_route_native,
  ``RiemannZeta.GuthMaynard.actual_typeI_branch_resolution_native,
  ``RiemannZeta.GuthMaynard.ingham_typeI_finite_window_resolution_native,
  ``RiemannZeta.GuthMaynard.huxley_typeI_finite_window_resolution_native,
  ``RiemannZeta.GuthMaynard.contDiff_typeIDyadicCutoff,
  ``RiemannZeta.GuthMaynard.typeISmoothStep_eq_one,
  ``RiemannZeta.GuthMaynard.typeISmoothStep_eq_zero,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoff_nonneg,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoff_le_one,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoff_eq_zero_of_le_half,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoff_eq_zero_of_two_le,
  ``RiemannZeta.GuthMaynard.contDiff_typeITailBoundary,
  ``RiemannZeta.GuthMaynard.typeITailBoundary_natCast,
  ``RiemannZeta.GuthMaynard.contDiff_typeISourceSmoothWeight,
  ``RiemannZeta.GuthMaynard.sum_typeIDyadicCutoff_eq,
  ``RiemannZeta.GuthMaynard.sum_typeIDyadicCutoff_eq_one,
  ``RiemannZeta.GuthMaynard.classicalZetaLongTail_eq_sum_smoothBlocks,
  ``RiemannZeta.GuthMaynard.typeISourceSmoothBlock_eq_restricted,
  ``RiemannZeta.GuthMaynard.classicalZetaLongTail_eq_sum_sourceSmoothBlocks,
  ``RiemannZeta.GuthMaynard.exists_typeISmoothBlock_large,
  ``RiemannZeta.GuthMaynard.exists_common_typeISmoothBlock_large,
  ``RiemannZeta.GuthMaynard.mellinConvergent_typeIDyadicCutoff_one,
  ``RiemannZeta.GuthMaynard.contDiff_typeIDyadicMellinKernel,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_typeIDyadicMellinKernel,
  ``RiemannZeta.GuthMaynard.typeIDyadicMellinSchwartz_apply,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoffMellin_eq_fourier,
  ``RiemannZeta.GuthMaynard.continuous_typeIDyadicCutoffMellin,
  ``RiemannZeta.GuthMaynard.verticalIntegrable_typeIDyadicCutoffMellin,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoff_mellinInversion,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoff_eq_verticalMellinIntegral,
  ``RiemannZeta.GuthMaynard.typeIDyadicCutoffPhase_eq_mellinIntegral,
  ``RiemannZeta.GuthMaynard.typeIMellinReflectionIntegrand_eq_factored,
  ``RiemannZeta.GuthMaynard.integrable_typeIMellinReflectionIntegrand,
  ``RiemannZeta.GuthMaynard.norm_typeIPowerReflectionIntegral_le,
  ``RiemannZeta.GuthMaynard.typeIDyadicRescaledIntegral_eq_mellinReflection,
  ``RiemannZeta.GuthMaynard.typeIDyadicPhysicalIntegral_rescale,
  ``RiemannZeta.GuthMaynard.typeIDyadicPhysicalIntegral_eq_mellinReflection,
  ``RiemannZeta.GuthMaynard.integral_typeIDyadicPhysicalIntegrand_eq_interval,
  ``RiemannZeta.GuthMaynard.typeIDyadicPhysicalIntegral_eq_common_mellinReflection,
  ``RiemannZeta.GuthMaynard.intervalIntegral_typeIMellinReflectionIntegrand_eq_commonMode,
  ``RiemannZeta.GuthMaynard.integrable_typeICommonMellinMode,
  ``RiemannZeta.GuthMaynard.sum_typeIDyadicPhysicalIntegral_eq_reflectedMellinPolynomial,
  ``RiemannZeta.GuthMaynard.contDiff_typeIReflectionKernel,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_typeIReflectionKernel,
  ``RiemannZeta.GuthMaynard.typeIReflectionSchwartz_apply,
  ``RiemannZeta.GuthMaynard.typeIReflection_poisson,
  ``RiemannZeta.GuthMaynard.typeIReflectionFourier_fixed_decay,
  ``RiemannZeta.GuthMaynard.typeIReflectionFourier_summable,
  ``RiemannZeta.GuthMaynard.typeIReflectionKernel_natCast,
  ``RiemannZeta.GuthMaynard.typeIReflectionFourier_neg_eq_stationaryIntegral,
  ``RiemannZeta.GuthMaynard.typeIReflection_stationary_window,
  ``RiemannZeta.GuthMaynard.typeISourceSmoothWeight_eq_dyadic_of_interior,
  ``RiemannZeta.GuthMaynard.typeIReflectionKernel_eq_dyadicPhysical_of_interior,
  ``RiemannZeta.GuthMaynard.typeINormalizedKernelSchwartz_apply,
  ``RiemannZeta.GuthMaynard.typeINormalizedKernel_uniform_iteratedFDeriv,
  ``RiemannZeta.GuthMaynard.typeINormalizedFourier_uniform_decay,
  ``RiemannZeta.GuthMaynard.typeINormalizedFourier_far_frequency_decay,
  ``RiemannZeta.GuthMaynard.typeINormalizedFarTail_bound,
  ``RiemannZeta.GuthMaynard.typeINormalizedScaledKernelSchwartz_apply,
  ``RiemannZeta.GuthMaynard.typeINormalizedScaledKernel_fourier,
  ``RiemannZeta.GuthMaynard.typeINormalizedKernel_poisson,
  ``RiemannZeta.GuthMaynard.typeINormalizedPoisson_split,
  ``RiemannZeta.GuthMaynard.mediumTypeIExactBProcess_native,
  ``RiemannZeta.GuthMaynard.fourierDeweightFiniteBlock_native,
  ``RiemannZeta.GuthMaynard.contDiff_typeILogWeight,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_typeILogWeight,
  ``RiemannZeta.GuthMaynard.typeILogWeightSchwartz_apply,
  ``RiemannZeta.GuthMaynard.typeILogWeight_log_nat,
  ``RiemannZeta.GuthMaynard.typeISourceSmoothBlock_fourierDeweight,
  ``RiemannZeta.GuthMaynard.contDiff_typeIReflectedLogWeight,
  ``RiemannZeta.GuthMaynard.hasCompactSupport_typeIReflectedLogWeight,
  ``RiemannZeta.GuthMaynard.typeIReflectedLogWeightSchwartz_apply,
  ``RiemannZeta.GuthMaynard.typeIReflectedLogWeight_log_nat,
  ``RiemannZeta.GuthMaynard.typeIReflectedBlock_fourierDeweight,
  ``RiemannZeta.GuthMaynard.weightedWeylBlock_eq_cpow,
  ``RiemannZeta.GuthMaynard.norm_weightedWeylBlock_le,
]

/-- The number printed by the audit, derived directly from its explicit list. -/
def auditedDeclarationCount : Nat := auditedDeclarations.size

/-- Named end theorems required before the human-facing runner may describe
the research agenda as complete.  Names are checked dynamically so this audit
continues to elaborate while an output is still under construction. -/
def requiredResearchOutputs : Array (Nat × Name) := #[
  (15, `RiemannZeta.GuthMaynard.ingham_zero_density_native),
  (15, `RiemannZeta.GuthMaynard.huxley_zero_density_native),
  (18, `RiemannZeta.GuthMaynard.typeIContourTypeIICoverOn_native),
  (18, `RiemannZeta.GuthMaynard.typeIIFourthMomentReduction_native),
  (18, `RiemannZeta.GuthMaynard.twistedZetaFourthMoment_native),
  (18, `RiemannZeta.GuthMaynard.guthMaynardZeroDensity_of_largeValues_native),
  (19, `RiemannZeta.GuthMaynard.guthMaynardLargeValues_native),
  (19, `RiemannZeta.GuthMaynard.guthMaynardZeroDensity_native),
  (19, `RiemannZeta.GuthMaynard.combined_zero_density_native)
]

private def isCompilerGeneratedTheorem (name : Name) : Bool :=
  let text := name.toString
  text.contains "._proof_" || text.contains ".eq_" || text.contains "._simp_" ||
    text.contains "._abel_" || text.contains ".congr_simp"

/-- Vendored PNT+ modules are production proof infrastructure even though the
upstream declarations intentionally extend root namespaces. -/
private def auditedExternalModules : Array Name := #[
  `RiemannZeta.External.PNT.Rectangle,
  `RiemannZeta.External.PNT.DivisorSupport,
  `RiemannZeta.External.PNT.ResidueCalcOnRectangles,
  `RiemannZeta.External.PNT.RectangleArgumentPrinciple,
  `RiemannZeta.External.PNT.ZetaBoundsUpstream,
  `RiemannZeta.External.PNT.ZetaAppendix
]

private def isFromAuditedExternalModule (env : Environment) (name : Name) : Bool :=
  match env.getModuleIdxFor? name with
  | none => false
  | some moduleIdx =>
      auditedExternalModules.contains env.header.modules[moduleIdx.toNat]!.module

private def exportedProjectTheorems (env : Environment) : Array Name := Id.run do
  let mut names := #[]
  for (name, info) in env.constants.toList do
    if (name.getRoot == `RiemannZeta || isFromAuditedExternalModule env name) &&
        info.isTheorem && !isPrivateName name && !isCompilerGeneratedTheorem name then
      names := names.push name
  return names.qsort Name.quickLt

/-- Execute the synchronized, transitive dependency audit. -/
def runDependencyAudit : CoreM Unit := do
  let env ← getEnv
  let discovered := exportedProjectTheorems env
  let mut failures : Nat := 0

  logInfo m!"=== RIEMANN ZETA TRANSITIVE AXIOM AUDIT ==="
  logInfo m!"Explicit declarations: {auditedDeclarationCount}"
  logInfo m!"Discovered source-level theorems: {discovered.size}"
  logInfo m!"Permitted axioms: {permittedAxioms}"

  for name in discovered do
    if !auditedDeclarations.contains name then
      failures := failures + 1
      logInfo m!"FAIL [unlisted theorem] {name}"

  for name in auditedDeclarations do
    if !discovered.contains name then
      failures := failures + 1
      logInfo m!"FAIL [missing or non-theorem declaration] {name}"

  for i in [:auditedDeclarations.size] do
    let name := auditedDeclarations[i]!
    if (auditedDeclarations.extract 0 i).contains name then
      failures := failures + 1
      logInfo m!"FAIL [duplicate audit entry] {name}"

  for name in auditedDeclarations do
    if discovered.contains name then
      let axioms ← Lean.collectAxioms name
      let forbidden := axioms.filter fun axiomName => !permittedAxioms.contains axiomName
      if forbidden.isEmpty then
        logInfo m!"PASS {name}: {axioms}"
      else
        failures := failures + 1
        logInfo m!"FAIL {name}: forbidden dependencies {forbidden}; all axioms {axioms}"

  logInfo m!"=== RESEARCH AGENDA OUTPUT GATE ==="
  for (item, name) in requiredResearchOutputs do
    if env.contains name then
      match env.find? name with
      | some info =>
          if info.isTheorem then
            logInfo m!"PASS [Shitlist #{item}] {name}"
          else
            failures := failures + 1
            logInfo m!"FAIL [Shitlist #{item}] {name} exists but is not a theorem"
      | none =>
          failures := failures + 1
          logInfo m!"FAIL [Shitlist #{item}] required theorem missing: {name}"
    else
      failures := failures + 1
      logInfo m!"FAIL [Shitlist #{item}] required theorem missing: {name}"

  if failures == 0 then
    logInfo m!"AUDIT PASS: all {auditedDeclarationCount} declarations have permitted dependencies and every required research output exists."
  else
    throwError "AUDIT FAIL: {failures} dependency, synchronization, or required-output failure(s) across {auditedDeclarationCount} explicit declarations"

#eval runDependencyAudit
