import GafniTao.WooleySourceAffine
#check Int.le_natAbs
#check Int.neg_natAbs_le
#check Int.natAbs_ofNat
#check Int.natAbs_of_nonneg
#check Int.ofNat_le
#check Int.neg_le_of_natAbs_le
#check Int.le_of_natAbs_le
#check Finset.single_le_sum
#check Finsupp.embDomain_comapDomain
#check Int.toNat_of_nonneg
#check Int.ofNat_toNat
#check Int.toNat_lt
#check Int.toNat_le
#check Int.toNat_sub_of_le
#check Int.natCast_sub
#check Fin.mk
#check Equiv.addRight
#check Equiv.sum_comp
#check Equiv.sum_apply
#check Fintype.sum_equiv
