#!/usr/bin/env python3
"""Deterministically extract frozen rational data into a Lean module."""

from __future__ import annotations

import argparse
import hashlib
import re
import zipfile
from pathlib import Path


ARCHIVE_SHA256 = "6ab14c1fbafe048abb61e497322cd7bb67868b2d8816fad0ec20183d937bb2f3"
DERIVED_PATH = "expdb-9953003/blueprint/src/python/derived.py"
EXPECTED = [
    (89, 1282, 997, 1282),
    (652397, 9713986, 7599781, 9713986),
    (10769, 351096, 609317, 702192),
    (89, 3478, 15327, 17390),
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def extract_pairs(archive: Path) -> list[tuple[int, int, int, int]]:
    if sha256(archive) != ARCHIVE_SHA256:
        raise SystemExit("paper-time ANTEDB archive SHA-256 mismatch")
    with zipfile.ZipFile(archive) as source:
        text = source.read(DERIVED_PATH).decode("utf-8")
    pattern = re.compile(
        r"^\s*prove_exponent_pair\(frac\((\d+),(\d+)\),\s*"
        r"frac\((\d+),(\d+)\),\s*simplify_deps=False,\s*verbose=True\)",
        re.MULTILINE,
    )
    pairs = [tuple(map(int, match.groups())) for match in pattern.finditer(text)]
    if pairs != EXPECTED:
        raise SystemExit(f"unexpected frozen exponent-pair data: {pairs!r}")
    return pairs


def render(pairs: list[tuple[int, int, int, int]]) -> str:
    entries = "\n".join(
        f"  ({k_num} / {k_den}, {l_num} / {l_den})" +
        ("," if index + 1 < len(pairs) else "")
        for index, (k_num, k_den, l_num, l_den) in enumerate(pairs)
    )
    return f"""-- This file is generated by Tools/generate_certificates.py.
-- Source: ANTEDB commit 9953003a48f46fe8075ccf9534321f98f656032e.
-- Do not edit by hand.

import TaoTrudgianYang2025.ExponentPair

namespace TaoTrudgianYang2025

/-- The four output points extracted from the frozen paper-time driver. -/
def generatedExponentPairCoordinates : List (ℚ × ℚ) := [
{entries}
]

theorem generatedExponentPairCoordinates_count :
    generatedExponentPairCoordinates.length = 4 := by
  rfl

end TaoTrudgianYang2025
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    content = render(extract_pairs(args.archive))
    args.output.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
