import Dubon2026.AdelicPrimitiveSchur
import Dubon2026.UnitaryInvariantProjection
import Dubon2026.ScalarProjectionSubspace

/-! # Irreducibility of the genuine full primitive adelic Hilbert representation -/

namespace Dubon2026

noncomputable section

/-- The original full adelic Hilbert representation generated by a positive-weight primitive cusp form has no nonzero proper closed invariant subspace. -/
theorem adelicPrimitiveHilbert_irreducible {N : ℕ} [NeZero N] {k : ℤ}
    (f : PrimitiveCuspForm N k) (hk : 0 < k)
    (p : Submodule ℂ (AdelicCyclicHilbert f.toCuspForm))
    (hclosed : IsClosed (p : Set (AdelicCyclicHilbert f.toCuspForm)))
    (hp : ∀ g v, v ∈ p → adelicCyclicHilbertRepresentation f.toCuspForm g v ∈ p) :
    p = ⊥ ∨ p = ⊤ := by
  letI : CompleteSpace p := hclosed.isComplete.completeSpace_coe
  let A : AdelicCyclicHilbert f.toCuspForm →L[ℂ] AdelicCyclicHilbert f.toCuspForm :=
    @Submodule.starProjection ℂ (AdelicCyclicHilbert f.toCuspForm)
      inferInstance inferInstance inferInstance p inferInstance
  have hA : ∀ g v, A (adelicCyclicHilbertRepresentation f.toCuspForm g v) =
      adelicCyclicHilbertRepresentation f.toCuspForm g (A v) := by
    intro g v
    exact @unitary_invariant_starProjection RationalAdelicGL2 (AdelicCyclicHilbert f.toCuspForm)
      inferInstance inferInstance inferInstance (adelicCyclicHilbertRepresentation f.toCuspForm)
      (adelicCyclicHilbertRepresentation_inner f.toCuspForm) p inferInstance hp g v
  obtain ⟨c, hc⟩ := adelicPrimitiveIntertwiner_scalar f hk A hA
  exact @scalarProjection_eq_bot_or_eq (AdelicCyclicHilbert f.toCuspForm)
    inferInstance inferInstance p ⊤ inferInstance le_top
    (adelicCyclicHilbertGenerator f.toCuspForm) (Submodule.mem_top)
    (adelicCyclicHilbertGenerator_ne_zero f.toCuspForm (primitiveCuspForm_ne_zero f))
    ⟨c, fun v _ => hc v⟩

end
end Dubon2026
