import Dubon2026.CanonicalAdelicCentralCharacter
import Dubon2026.AdelicUnipotentCuspidality
import Mathlib.RepresentationTheory.Subrepresentation

/-! # The genuine algebraic full adelic representation generated by the original cusp form -/

namespace Dubon2026

noncomputable section
open NumberField Matrix UpperHalfPlane CongruenceSubgroup MeasureTheory
open Matrix.SpecialLinearGroup
open scoped MatrixGroups ModularForm

/-- The actual canonical full rational adelic general-linear group. -/
abbrev RationalAdelicGL2 := GeneralLinearGroup (Fin 2) (AdeleRing ℤ ℚ)

/-- The original full adelic cusp function generates its actual algebraic right-regular subrepresentation. -/
def adelicLiftCyclicRepresentation (N : ℕ) [NeZero N] (k : ℤ) (f : ℍ → ℂ) :
    Subrepresentation (TannakaDuality.FiniteGroup.rightRegular (k := ℂ) (G := RationalAdelicGL2)) where
  toSubmodule := Submodule.span ℂ (Set.range (fun h : RationalAdelicGL2 =>
    TannakaDuality.FiniteGroup.rightRegular h (canonicalAdelicGL2CuspLift N k f)))
  apply_mem_toSubmodule g v hv := by
    induction hv using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨h, rfl⟩ := hx
      apply Submodule.subset_span
      refine ⟨g * h, ?_⟩
      ext t
      simp [TannakaDuality.FiniteGroup.rightRegular_apply, mul_assoc]
    | zero => simp
    | add x y hx hy hix hiy =>
      rw [map_add]
      exact Submodule.add_mem _ hix hiy
    | smul c x hx hix =>
      rw [map_smul]
      exact Submodule.smul_mem _ c hix

/-- The actual original cusp function belongs to its genuine generated full adelic representation. -/
theorem canonicalAdelicGL2CuspLift_mem_cyclic (N : ℕ) [NeZero N] (k : ℤ) (f : ℍ → ℂ) :
    canonicalAdelicGL2CuspLift N k f ∈ (adelicLiftCyclicRepresentation N k f).toSubmodule := by
  apply Submodule.subset_span
  refine ⟨1, ?_⟩
  simp

/-- Every actual cyclic adelic vector is continuous on the canonical full group. -/
theorem adelicLiftCyclic_continuous (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) {v : RationalAdelicGL2 → ℂ}
    (hv : v ∈ (adelicLiftCyclicRepresentation N k f).toSubmodule) : Continuous v := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    exact (canonicalAdelicGL2CuspLift_continuous N f).comp (continuous_id.mul_const h)
  | zero => exact continuous_const
  | add x y hx hy hix hiy => exact hix.add hiy
  | smul c x hx hix => exact hix.const_smul c

/-- Every original cyclic adelic vector is left invariant under the actual rational general-linear group. -/
theorem adelicLiftCyclic_rational_invariant (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) {v : RationalAdelicGL2 → ℂ}
    (hv : v ∈ (adelicLiftCyclicRepresentation N k f).toSubmodule)
    (γ : GeneralLinearGroup (Fin 2) ℚ) (g : RationalAdelicGL2) :
    v (GeneralLinearGroup.map (algebraMap ℚ (AdeleRing ℤ ℚ)) γ * g) = v g := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    simpa only [TannakaDuality.FiniteGroup.rightRegular_apply, mul_assoc] using
      canonicalAdelicGL2CuspLift_rational_invariant N f γ (g * h)
  | zero => rfl
  | add x y hx hy hix hiy => simp only [Pi.add_apply, hix, hiy]
  | smul c x hx hix => simp only [Pi.smul_apply, hix]

/-- Every original cyclic adelic vector has the proved genuine trivial adelic scalar character. -/
theorem adelicLiftCyclic_scalar_invariant (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) {v : RationalAdelicGL2 → ℂ}
    (hv : v ∈ (adelicLiftCyclicRepresentation N k f).toSubmodule)
    (u : (AdeleRing ℤ ℚ)ˣ) (g : RationalAdelicGL2) :
    v (GeneralLinearGroup.scalar (Fin 2) u * g) = v g := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    simpa only [TannakaDuality.FiniteGroup.rightRegular_apply, mul_assoc] using
      canonicalAdelicGL2CuspLift_scalar_mul N f u (g * h)
  | zero => rfl
  | add x y hx hy hix hiy => simp only [Pi.add_apply, hix, hiy]
  | smul c x hx hix => simp only [Pi.smul_apply, hix]

/-- Every genuine algebraic adelic cyclic vector has an actual continuous descended unipotent function with zero Haar integral at every group point. -/
theorem adelicLiftCyclic_unipotent_cuspidal (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) {v : RationalAdelicGL2 → ℂ}
    (hv : v ∈ (adelicLiftCyclicRepresentation N k f).toSubmodule) (g : RationalAdelicGL2) :
    ∃ φ : C(RationalAdelicAdditiveQuotient, ℂ),
      (∀ x : AdeleRing ℤ ℚ, φ (QuotientAddGroup.mk x) =
        v (GeneralLinearGroup.upperRightHom x * g)) ∧
      (∫ z, φ z ∂rationalAdelicAdditiveHaar) = 0 := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    refine ⟨⟨adelicUnipotentQuotientFunction N f (g * h),
      adelicUnipotentQuotientFunction_continuous N f (g * h)⟩, ?_,
      canonicalAdelicGL2CuspLift_unipotent_cuspidal N f (g * h)⟩
    intro x
    simp only [ContinuousMap.coe_mk, adelicUnipotentQuotientFunction_mk,
      TannakaDuality.FiniteGroup.rightRegular_apply, mul_assoc]
  | zero => exact ⟨0, fun _ => rfl, by simp⟩
  | add x y hx hy hix hiy =>
    obtain ⟨φ, hφ, hiφ⟩ := hix
    obtain ⟨ψ, hψ, hiψ⟩ := hiy
    refine ⟨φ + ψ, fun x => by simp only [ContinuousMap.add_apply, Pi.add_apply, hφ, hψ], ?_⟩
    change (∫ z, φ z + ψ z ∂rationalAdelicAdditiveHaar) = 0
    rw [integral_add
      (φ.continuous.integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _))
      (ψ.continuous.integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _)), hiφ, hiψ]
    simp
  | smul c x hx hix =>
    obtain ⟨φ, hφ, hiφ⟩ := hix
    refine ⟨c • φ, fun x => by simp only [ContinuousMap.smul_apply, Pi.smul_apply, hφ], ?_⟩
    change (∫ z, c • φ z ∂rationalAdelicAdditiveHaar) = 0
    rw [integral_smul, hiφ, smul_zero]

end
end Dubon2026
