import Dubon2026.AdelicProjectiveTiling
import Dubon2026.RealCyclicL2

/-! # Actual global bounds and square integrability for the original adelic cyclic representation -/

namespace Dubon2026

noncomputable section
open UpperHalfPlane Matrix.SpecialLinearGroup CongruenceSubgroup MeasureTheory
open scoped MatrixGroups

/-- The original canonical full adelic cusp function inherits its genuine real cusp bound. -/
theorem canonicalAdelicGL2CuspLift_bounded (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ g : RationalAdelicGL2, ‖canonicalAdelicGL2CuspLift N k f g‖ ≤ C := by
  obtain ⟨C, hC0, hC⟩ := realWeightLift_bounded f
  exact ⟨C, hC0, fun _ => hC _⟩

/-- Every vector generated by actual full adelic right translations has a genuine global bound. -/
theorem adelicLiftCyclic_bounded (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) {v : RationalAdelicGL2 → ℂ}
    (hv : v ∈ (adelicLiftCyclicRepresentation N k f).toSubmodule) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ g : RationalAdelicGL2, ‖v g‖ ≤ C := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    obtain ⟨C, hC0, hC⟩ := canonicalAdelicGL2CuspLift_bounded N f
    exact ⟨C, hC0, fun g => hC (g * h)⟩
  | zero => exact ⟨0, le_rfl, fun _ => by simp⟩
  | add x y hx hy hix hiy =>
    obtain ⟨Cx, hx0, hCx⟩ := hix
    obtain ⟨Cy, hy0, hCy⟩ := hiy
    exact ⟨Cx + Cy, add_nonneg hx0 hy0,
      fun g => (norm_add_le (x g) (y g)).trans (add_le_add (hCx g) (hCy g))⟩
  | smul c x hx hix =>
    obtain ⟨C, hC0, hC⟩ := hix
    refine ⟨‖c‖ * C, mul_nonneg (norm_nonneg _) hC0, fun g => ?_⟩
    simpa only [Pi.smul_apply, norm_smul] using mul_le_mul_of_nonneg_left (hC g) (norm_nonneg c)

/-- Faithful projective descent preserves the genuine global bound of every original adelic cyclic vector. -/
theorem adelicCyclicProjectiveFunction_bounded (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k)
    (v : (adelicLiftCyclicRepresentation N k f).toSubmodule) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ p, ‖adelicCyclicProjectiveFunction N f v p‖ ≤ C := by
  obtain ⟨C, hC0, hC⟩ := adelicLiftCyclic_bounded N f v.property
  refine ⟨C, hC0, ?_⟩
  intro p
  obtain ⟨r, hr⟩ := QuotientGroup.mk_surjective p.1
  obtain ⟨a, ha⟩ := Matrix.ProjGenLinGroup.mk_surjective p.2
  have hp : p = (QuotientGroup.mk r, Matrix.ProjGenLinGroup.mk a) := Prod.ext hr.symm ha.symm
  rw [hp, adelicCyclicProjectiveFunction_mk]
  exact hC _

/-- Every actual original adelic cyclic vector is square integrable on the genuine arithmetic fundamental domain. -/
theorem adelicCyclicProjectiveFunction_memLp_two (N : ℕ) [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k)
    (v : (adelicLiftCyclicRepresentation N k f).toSubmodule) :
    MemLp (adelicCyclicProjectiveFunction N f v) 2
      (adelicProjectiveMeasure.restrict (adelicProjectiveGamma0Domain N)) := by
  letI : IsFiniteMeasure (adelicProjectiveMeasure.restrict (adelicProjectiveGamma0Domain N)) := by
    constructor
    simpa only [Measure.restrict_apply_univ] using adelicProjectiveGamma0Domain_volume_lt_top N
  obtain ⟨C, _, hC⟩ := adelicCyclicProjectiveFunction_bounded N f v
  exact MemLp.of_bound (adelicCyclicProjectiveFunction_continuous N f v).aestronglyMeasurable C
    (Filter.Eventually.of_forall hC)

end
end Dubon2026
