import Dubon2026.AdelicEveryLocalFixedLine
import Dubon2026.AdelicLocalCoreIrreducible

/-! # Genuine smooth core irreducibility at every original finite place -/

namespace Dubon2026

noncomputable section
open IsDedekindDomain Matrix

/-- The actual smooth algebraic core generated by the original primitive cusp vector is irreducible at every genuine finite place, with no closedness assumption on its invariant subspaces. -/
theorem adelicEveryLocalCyclicCore_irreducible {N : ℕ} [NeZero N] {k : ℤ} (F : PrimitiveCuspForm N k) (hk : 0 < k) (v : HeightOneSpectrum ℤ)
    (W : Submodule ℂ (AdelicCyclicHilbert F.toCuspForm))
    (hW : W ≤ adelicLocalCyclicCore F.toCuspForm v)
    (hinv : ∀ g x, x ∈ W → adelicCyclicLocalRepresentation F.toCuspForm
      v g x ∈ W) :
    W = ⊥ ∨ W = adelicLocalCyclicCore F.toCuspForm v := by
  by_cases hbot : W = ⊥
  · exact Or.inl hbot
  right
  obtain ⟨w, hw, hwn⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hbot
  have hwclosed : w ∈ adelicLocalCyclicClosedSpan F.toCuspForm v :=
    Submodule.le_topologicalClosure _ (hW hw)
  obtain ⟨g, hg⟩ := adelicLocalCyclic_exists_nonzero_generator_pairing F.toCuspForm _ w hwclosed hwn
  let z := adelicCyclicLocalRepresentation F.toCuspForm v g w
  have hzW : z ∈ W := hinv g w hw
  have hPzW := adelicLocalFixedProjection_mem_invariantCore F.toCuspForm
    v W hW hinv z hzW
  have hPclosed : adelicLocalFixedProjection F.toCuspForm v z ∈
      adelicLocalCyclicClosedSpan F.toCuspForm v :=
    Submodule.le_topologicalClosure _ (hW hPzW)
  obtain ⟨c, hc⟩ := adelicEveryLocalCyclic_fixed_generator_scalar F hk v _ hPclosed
    (adelicLocalFixedProjection_mem F.toCuspForm _ z)
  have hcne : c ≠ 0 := by
    intro hc0
    apply hg
    change inner ℂ z (adelicCyclicHilbertGenerator F.toCuspForm) = 0
    rw [← adelicLocalFixedProjection_inner_generator F.toCuspForm
      v, hc, hc0,
      zero_smul ℂ (adelicCyclicHilbertGenerator F.toCuspForm)]
    exact @inner_zero_left ℂ (AdelicCyclicHilbert F.toCuspForm)
      inferInstance inferInstance inferInstance (adelicCyclicHilbertGenerator F.toCuspForm)
  have hyW : adelicCyclicHilbertGenerator F.toCuspForm ∈ W :=
    (W.smul_mem_iff hcne).mp (hc ▸ hPzW)
  apply le_antisymm hW
  apply Submodule.span_le.mpr
  rintro _ ⟨a, rfl⟩
  exact hinv a _ hyW


end
end Dubon2026
