import Dubon2026.AdelicLocalCoreProjection
import Dubon2026.AdelicLocalCyclicFixedLine

/-! # Actual smooth algebraic local cyclic irreducibility, without a closed-subspace hypothesis -/

namespace Dubon2026

noncomputable section
open IsDedekindDomain Matrix Matrix.SpecialLinearGroup CongruenceSubgroup
open scoped MatrixGroups

/-- Any nonzero vector in the original local cyclic Hilbert space has a genuine local translate pairing nontrivially with the original cusp generator. -/
theorem adelicLocalCyclic_exists_nonzero_generator_pairing {N : ℕ} [NeZero N] {k : ℤ}
    (f : CuspForm ((Gamma0 N).map (mapGL ℝ)) k) (v : HeightOneSpectrum ℤ)
    (x : AdelicCyclicHilbert f) (hx : x ∈ adelicLocalCyclicClosedSpan f v) (hne : x ≠ 0) :
    ∃ g : GeneralLinearGroup (Fin 2) (v.adicCompletion ℚ),
      inner ℂ (adelicCyclicLocalRepresentation f v g x) (adelicCyclicHilbertGenerator f) ≠ 0 := by
  by_contra h
  apply hne
  apply @closedSpan_orthogonal_eq_zero (AdelicCyclicHilbert f)
    (GeneralLinearGroup (Fin 2) (v.adicCompletion ℚ)) inferInstance inferInstance
    (fun g => adelicCyclicLocalRepresentation f v g (adelicCyclicHilbertGenerator f)) x hx
  intro g
  have hz : inner ℂ (adelicCyclicLocalRepresentation f v g⁻¹ x) (adelicCyclicHilbertGenerator f) = 0 :=
    not_ne_iff.mp (fun hh => h ⟨g⁻¹, hh⟩)
  have he := @representation_inner_inverse (GeneralLinearGroup (Fin 2) (v.adicCompletion ℚ))
    (AdelicCyclicHilbert f) inferInstance inferInstance inferInstance
    (adelicCyclicLocalRepresentation f v) (adelicCyclicLocalRepresentation_inner f v)
    g⁻¹ x (adelicCyclicHilbertGenerator f)
  rw [inv_inv] at he
  exact he.symm.trans hz

/-- The actual smooth algebraic core generated by the original primitive cusp vector is irreducible at every genuine good prime, with no closedness assumption on its invariant subspaces. -/
theorem adelicLocalCyclicCore_irreducible {N p : ℕ} [NeZero N] [NeZero p]
    [Fact p.Prime] {k : ℤ} (F : PrimitiveCuspForm N k) (hpN : p.Coprime N)
    (W : Submodule ℂ (AdelicCyclicHilbert F.toCuspForm))
    (hW : W ≤ adelicLocalCyclicCore F.toCuspForm (rationalPrimePlace p (Fact.out : p.Prime)))
    (hinv : ∀ g x, x ∈ W → adelicCyclicLocalRepresentation F.toCuspForm
      (rationalPrimePlace p (Fact.out : p.Prime)) g x ∈ W) :
    W = ⊥ ∨ W = adelicLocalCyclicCore F.toCuspForm (rationalPrimePlace p (Fact.out : p.Prime)) := by
  by_cases hbot : W = ⊥
  · exact Or.inl hbot
  right
  obtain ⟨w, hw, hwn⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hbot
  have hwclosed : w ∈ adelicLocalCyclicClosedSpan F.toCuspForm (rationalPrimePlace p (Fact.out : p.Prime)) :=
    Submodule.le_topologicalClosure _ (hW hw)
  obtain ⟨g, hg⟩ := adelicLocalCyclic_exists_nonzero_generator_pairing F.toCuspForm _ w hwclosed hwn
  let z := adelicCyclicLocalRepresentation F.toCuspForm (rationalPrimePlace p (Fact.out : p.Prime)) g w
  have hzW : z ∈ W := hinv g w hw
  have hPzW := adelicLocalFixedProjection_mem_invariantCore F.toCuspForm
    (rationalPrimePlace p (Fact.out : p.Prime)) W hW hinv z hzW
  have hPclosed : adelicLocalFixedProjection F.toCuspForm (rationalPrimePlace p (Fact.out : p.Prime)) z ∈
      adelicLocalCyclicClosedSpan F.toCuspForm (rationalPrimePlace p (Fact.out : p.Prime)) :=
    Submodule.le_topologicalClosure _ (hW hPzW)
  obtain ⟨c, hc⟩ := adelicLocalCyclic_fixed_generator_scalar F hpN _ hPclosed
    (adelicLocalFixedProjection_mem F.toCuspForm _ z)
  have hcne : c ≠ 0 := by
    intro hc0
    apply hg
    change inner ℂ z (adelicCyclicHilbertGenerator F.toCuspForm) = 0
    rw [← adelicLocalFixedProjection_inner_generator F.toCuspForm
      (rationalPrimePlace p (Fact.out : p.Prime)), hc, hc0,
      zero_smul ℂ (adelicCyclicHilbertGenerator F.toCuspForm)]
    exact @inner_zero_left ℂ (AdelicCyclicHilbert F.toCuspForm)
      inferInstance inferInstance inferInstance (adelicCyclicHilbertGenerator F.toCuspForm)
  have hyW : adelicCyclicHilbertGenerator F.toCuspForm ∈ W :=
    (W.smul_mem_iff hcne).mp (hc ▸ hPzW)
  apply le_antisymm hW
  apply Submodule.span_le.mpr
  rintro _ ⟨a, rfl⟩
  exact hinv a _ hyW

end
end Dubon2026
