import Dubon2026.UnramifiedTensorImages

/-! # The genuine fraction field of the original tensor image and the actual compositum -/

namespace Dubon2026

noncomputable section
open scoped TensorProduct

variable {R A B Ω : Type*} [CommRing R] [CommRing A] [CommRing B] [Field Ω]
  [Algebra R A] [Algebra R B] [Algebra R Ω]

/-- The actual tensor image generates precisely the subfield generated by the two original images. -/
theorem ambientTensorImage_fieldClosure (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :
    Subfield.closure (AmbientTensorImage f g : Set Ω) =
      Subfield.closure (Set.range f ∪ Set.range g) := by
  apply le_antisymm
  · apply Subfield.closure_le.mpr
    rintro _ ⟨t, rfl⟩
    induction t using TensorProduct.induction_on with
    | zero => simpa only [map_zero] using
        (Subfield.closure (Set.range f ∪ Set.range g)).zero_mem
    | tmul a b =>
        change f a * g b ∈ Subfield.closure (Set.range f ∪ Set.range g)
        exact mul_mem (Subfield.subset_closure (Or.inl ⟨a, rfl⟩))
          (Subfield.subset_closure (Or.inr ⟨b, rfl⟩))
    | add x y hx hy => simpa only [map_add] using add_mem hx hy
  · apply Subfield.closure_mono
    rintro _ (⟨a, rfl⟩ | ⟨b, rfl⟩)
    · exact ⟨a ⊗ₜ[R] (1 : B), Algebra.TensorProduct.productMap_left_apply f g a⟩
    · exact ⟨(1 : A) ⊗ₜ[R] b, Algebra.TensorProduct.productMap_right_apply f g b⟩

/-- The original tensor image's actual fraction field embeds in the original ambient field. -/
def ambientTensorFractionEmbedding (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :
    FractionRing (AmbientTensorImage f g) →+* Ω :=
  IsFractionRing.lift (g := (AmbientTensorImage f g).val.toRingHom) Subtype.val_injective

/-- The genuine fraction embedding has exactly the field generated by the two original coefficient images as its actual range. -/
theorem ambientTensorFractionEmbedding_fieldRange
    (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :
    (ambientTensorFractionEmbedding f g).fieldRange =
      Subfield.closure (Set.range f ∪ Set.range g) := by
  rw [ambientTensorFractionEmbedding, IsFractionRing.lift_fieldRange]
  have hr : Set.range (fun x : AmbientTensorImage f g => (x : Ω)) =
      (AmbientTensorImage f g : Set Ω) := Subtype.range_val
  change Subfield.closure (Set.range (fun x : AmbientTensorImage f g => (x : Ω))) = _
  rw [hr, ambientTensorImage_fieldClosure]

/-- If the original coefficient images come from actual fraction-field embeddings, the genuine tensor fraction field maps onto their original compositum inside the ambient field. -/
theorem ambientTensorFractionEmbedding_compositum
    {L M : Type*} [Field L] [Field M]
    [Algebra A L] [IsFractionRing A L] [Algebra B M] [IsFractionRing B M]
    (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) (i : L →+* Ω) (j : M →+* Ω)
    (hi : i.comp (algebraMap A L) = f.toRingHom)
    (hj : j.comp (algebraMap B M) = g.toRingHom) :
    (ambientTensorFractionEmbedding f g).fieldRange = i.fieldRange ⊔ j.fieldRange := by
  have hL := IsFractionRing.ringHom_fieldRange_eq_of_comp_eq hi
  have hM := IsFractionRing.ringHom_fieldRange_eq_of_comp_eq hj
  change i.fieldRange = Subfield.closure (Set.range f) at hL
  change j.fieldRange = Subfield.closure (Set.range g) at hM
  rw [ambientTensorFractionEmbedding_fieldRange, Subfield.closure_union, ← hL, ← hM]

end
end Dubon2026
