import Dubon2026.ArithmeticFramedUniversalRing
import Dubon2026.FixedResidualTraceUniversalRing

/-! # The actual complete local trace coefficient ring of the original arithmetic Galois representation -/

namespace Dubon2026
noncomputable section
open Matrix
open scoped NumberField

variable {ι O : Type} [Fintype ι] [DecidableEq ι]
  [CommRing O] [IsLocalRing O] [IsNoetherianRing O]
  [Finite (IsLocalRing.ResidueField O)] [TopologicalSpace (IsLocalRing.ResidueField O)]
  [DiscreteTopology (IsLocalRing.ResidueField O)]

/-- The literal closed coefficient algebra generated by all traces of the actual whole original arithmetic framed universal representation. -/
abbrev ArithmeticTraceCoefficientRing
    (a : 𝓞 ℚ) (ha : a ≠ 0) (p : ℕ) (hp : p.Prime) (hpa : (p : 𝓞 ℚ) ∣ a)
    (σ : rationalArithmeticGaloisGroup a →* GeneralLinearGroup ι (IsLocalRing.ResidueField O))
    (hσ : Continuous σ) :=
  closedMatrixTraceAlgebra (O := O)
    (arithmeticFramedUniversalRepresentation a ha p hp hpa σ hσ).toMonoidHom

/-- The genuine original arithmetic trace ring is complete local and Noetherian in its own maximal-adic topology, with a constructed continuous retraction from the actual arithmetic framed ring. Its original finite presentation is derived, rather than assumed. -/
theorem arithmeticTraceCoefficientRing_localData
    {L : Type} [Field L] [Algebra (IsLocalRing.ResidueField O) L] [IsAlgClosed L]
    (a : 𝓞 ℚ) (ha : a ≠ 0) (p : ℕ) (hp : p.Prime) (hpa : (p : 𝓞 ℚ) ∣ a)
    (σ : rationalArithmeticGaloisGroup a →* GeneralLinearGroup ι (IsLocalRing.ResidueField O))
    (hσ : Continuous σ)
    [Representation.IsIrreducible (matrixStandardRepresentation
      (matrixCoefficientExtension (L := L) σ))] (i₀ : ι) :
    ∃ hlocal : IsLocalRing (ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ),
      letI := hlocal
      IsNoetherianRing (ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ) ∧
      IsAdic (IsLocalRing.maximalIdeal (ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ)) ∧
      IsAdicComplete (IsLocalRing.maximalIdeal (ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ))
        (ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ) ∧
      ∃ f : ArithmeticFramedUniversalRing a ha p hp hpa σ hσ →ₐ[O]
          ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ,
        (∀ x : ArithmeticTraceCoefficientRing a ha p hp hpa σ hσ, f x = x) ∧
          Continuous f := by
  exact fixedResidualTraceAlgebra_localData (L := L) p (rationalArithmeticGaloisGroup a) σ hσ
    (arithmeticResidualGenerators a ha p hp hpa σ hσ)
    (arithmeticResidualGenerators_surjective a ha p hp hpa σ hσ) i₀

end
end Dubon2026
