import Dubon2026.MatrixRepresentationStrictConjugacy
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Topology.Algebra.Algebra

/-! # The actual closed coefficient algebra generated by traces of a whole representation -/

namespace Dubon2026
noncomputable section
open Matrix

variable {G ι O R : Type*} [Group G] [Fintype ι] [DecidableEq ι]
  [CommRing O] [CommRing R] [Algebra O R]
  [TopologicalSpace R] [IsTopologicalRing R]

/-- The closed original coefficient subalgebra generated by all actual traces of the original whole representation. -/
def closedMatrixTraceAlgebra (ρ : G →* GeneralLinearGroup ι R) : Subalgebra O R :=
  (Algebra.adjoin O (Set.range (fun g : G => Matrix.trace (ρ g).val))).topologicalClosure

/-- Every genuine original trace belongs to the closed trace algebra. -/
theorem trace_mem_closedMatrixTraceAlgebra (ρ : G →* GeneralLinearGroup ι R) (g : G) :
    Matrix.trace (ρ g).val ∈ closedMatrixTraceAlgebra (O := O) ρ :=
  Subalgebra.le_topologicalClosure _ (Algebra.subset_adjoin ⟨g, rfl⟩)

/-- The actual trace coefficient algebra is closed in the original coefficient topology. -/
theorem isClosed_closedMatrixTraceAlgebra (ρ : G →* GeneralLinearGroup ι R) :
    IsClosed (closedMatrixTraceAlgebra (O := O) ρ : Set R) :=
  Subalgebra.isClosed_topologicalClosure _

/-- Equality on genuine original traces forces two continuous original coefficient maps to agree on the whole closed trace algebra. -/
theorem eqOn_closedMatrixTraceAlgebra {B : Type*} [CommRing B] [Algebra O B]
    [TopologicalSpace B] [T2Space B]
    (ρ : G →* GeneralLinearGroup ι R) (f g : R →ₐ[O] B)
    (hf : Continuous f) (hg : Continuous g)
    (htrace : ∀ x : G, f (Matrix.trace (ρ x).val) = g (Matrix.trace (ρ x).val)) :
    Set.EqOn f g (closedMatrixTraceAlgebra (O := O) ρ : Set R) := by
  apply Set.EqOn.closure (s := (Algebra.adjoin O
    (Set.range (fun x : G => Matrix.trace (ρ x).val)) : Set R)) _ hf hg
  apply AlgHom.eqOn_adjoin_iff.mpr
  rintro _ ⟨x, rfl⟩
  exact htrace x

omit [Algebra O R] [TopologicalSpace R] [IsTopologicalRing R] in
/-- Actual strict conjugacy of whole representations preserves every original matrix trace. -/
theorem matrixStrictlyConjugate_trace {K : Type*} [CommRing K]
    (r : R →+* K) (ρ τ : G →* GeneralLinearGroup ι R)
    (h : MatrixStrictlyConjugate r ρ τ) (x : G) :
    Matrix.trace (τ x).val = Matrix.trace (ρ x).val := by
  obtain ⟨U, _, hU⟩ := h
  rw [hU x]
  exact Matrix.trace_units_conj U (ρ x).val

/-- If two original continuous coefficient changes give strictly equivalent whole representations, the coefficient maps agree on the actual closed trace algebra. -/
theorem eqOn_closedMatrixTraceAlgebra_of_strictConjugate {B K : Type*}
    [CommRing B] [Algebra O B] [CommRing K] [TopologicalSpace B] [T2Space B]
    (ρ : G →* GeneralLinearGroup ι R) (f g : R →ₐ[O] B)
    (hf : Continuous f) (hg : Continuous g) (r : B →+* K)
    (h : MatrixStrictlyConjugate r
      ((GeneralLinearGroup.map f.toRingHom).comp ρ)
      ((GeneralLinearGroup.map g.toRingHom).comp ρ)) :
    Set.EqOn f g (closedMatrixTraceAlgebra (O := O) ρ : Set R) := by
  apply eqOn_closedMatrixTraceAlgebra ρ f g hf hg
  intro x
  have ht := matrixStrictlyConjugate_trace r _ _ h x
  change Matrix.trace ((ρ x).val.map g) = Matrix.trace ((ρ x).val.map f) at ht
  rw [← AddMonoidHom.map_trace, ← AddMonoidHom.map_trace] at ht
  exact ht.symm

end
end Dubon2026
