import Dubon2026.MatrixBasisSubalgebraSpan
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.LinearAlgebra.FreeModule.Finite.Basic
import Mathlib.Algebra.Module.Submodule.Equiv

/-! # The actual coefficient algebra generated by the original whole representation matrices -/

namespace Dubon2026
noncomputable section
open Matrix Module

variable {G ι κ O R : Type*} [Group G] [Fintype ι] [DecidableEq ι]
  [Fintype κ] [DecidableEq κ] [CommRing O] [CommRing R] [Algebra O R]

/-- The actual matrix algebra over the original coefficient subalgebra generated by all matrices of the original whole representation. -/
def coefficientRepresentationMatrixAlgebra
    (S : Subalgebra O R) (ρ : G →* GeneralLinearGroup ι R) : Subalgebra S (Matrix ι ι R) :=
  Algebra.adjoin S (Set.range (fun x : G => (ρ x).val))

/-- The genuine generated matrix algebra has exactly the original representation span as its underlying coefficient module, since the entire original representation image is multiplicatively closed. -/
theorem coefficientRepresentationMatrixAlgebra_toSubmodule
    (S : Subalgebra O R) (ρ : G →* GeneralLinearGroup ι R) :
    (coefficientRepresentationMatrixAlgebra S ρ).toSubmodule =
      Submodule.span S (Set.range (fun x : G => (ρ x).val)) := by
  unfold coefficientRepresentationMatrixAlgebra
  rw [Algebra.adjoin_eq_span]
  change Submodule.span S ((Submonoid.closure
    (MonoidHom.mrange ((Units.coeHom (Matrix ι ι R)).comp ρ) : Set (Matrix ι ι R))) :
      Set (Matrix ι ι R)) = _
  rw [Submonoid.closure_eq]
  rfl

/-- A genuine original representation matrix basis whose original coordinates have descended spans exactly the same actual generated matrix algebra over the coefficient subalgebra. -/
theorem coefficientRepresentationMatrixAlgebra_eq_basis_span
    (S : Subalgebra O R) (ρ : G →* GeneralLinearGroup ι R) (a : κ → G)
    (b : Basis κ R (Matrix ι ι R)) (hb : ∀ i, b i = (ρ (a i)).val)
    (hcoord : ∀ x i, b.repr (ρ x).val i ∈ S) :
    (coefficientRepresentationMatrixAlgebra S ρ).toSubmodule =
      Submodule.span S (Set.range b) := by
  rw [coefficientRepresentationMatrixAlgebra_toSubmodule]
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨x, rfl⟩
    exact (matrix_mem_subalgebra_basis_span_iff S b (ρ x).val).mpr (hcoord x)
  · apply Submodule.span_le.mpr
    rintro _ ⟨i, rfl⟩
    exact Submodule.subset_span ⟨a i, (hb i).symm⟩

/-- The same actual original representation basis is a basis of its genuine generated matrix algebra over the original coefficient subalgebra. -/
def coefficientRepresentationMatrixBasis
    (S : Subalgebra O R) (ρ : G →* GeneralLinearGroup ι R) (a : κ → G)
    (b : Basis κ R (Matrix ι ι R)) (hb : ∀ i, b i = (ρ (a i)).val)
    (hcoord : ∀ x i, b.repr (ρ x).val i ∈ S) :
    Basis κ S (coefficientRepresentationMatrixAlgebra S ρ) :=
  (Basis.span (b.linearIndependent.restrict_scalars' S)).map
    (LinearEquiv.ofEq _ _ (coefficientRepresentationMatrixAlgebra_eq_basis_span
      S ρ a b hb hcoord).symm)

omit [DecidableEq κ] in
/-- The original generated matrix algebra is finite and free over the actual coefficient subalgebra once all genuine coordinates in the original finite representation basis have descended. -/
theorem coefficientRepresentationMatrixAlgebra_finite_free
    (S : Subalgebra O R) (ρ : G →* GeneralLinearGroup ι R) (a : κ → G)
    (b : Basis κ R (Matrix ι ι R)) (hb : ∀ i, b i = (ρ (a i)).val)
    (hcoord : ∀ x i, b.repr (ρ x).val i ∈ S) :
    Module.Finite S (coefficientRepresentationMatrixAlgebra S ρ) ∧
      Module.Free S (coefficientRepresentationMatrixAlgebra S ρ) := by
  classical
  let bs := coefficientRepresentationMatrixBasis S ρ a b hb hcoord
  exact ⟨Module.Finite.of_basis bs, Module.Free.of_basis bs⟩

/-- The same actual original generated matrix algebra is closed in the original matrix topology whenever its coefficient subalgebra is closed and its genuine finite-basis coordinates have descended. -/
theorem isClosed_coefficientRepresentationMatrixAlgebra
    [TopologicalSpace R] [IsTopologicalRing R]
    (S : Subalgebra O R) (hS : IsClosed (S : Set R))
    (ρ : G →* GeneralLinearGroup ι R) (a : κ → G)
    (b : Basis κ R (Matrix ι ι R)) (hb : ∀ i, b i = (ρ (a i)).val)
    (hcoord : ∀ x i, b.repr (ρ x).val i ∈ S) :
    IsClosed (coefficientRepresentationMatrixAlgebra S ρ : Set (Matrix ι ι R)) := by
  have hs := coefficientRepresentationMatrixAlgebra_eq_basis_span S ρ a b hb hcoord
  change IsClosed ((coefficientRepresentationMatrixAlgebra S ρ).toSubmodule : Set (Matrix ι ι R))
  rw [hs]
  exact isClosed_matrix_subalgebra_basis_span S hS b

end
end Dubon2026
