import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-! # Actual finite separable subextensions descend through directed field unions -/

namespace Dubon2026

noncomputable section

variable {K Ω : Type*} [Field K] [Field Ω] [Algebra K Ω]

/-- A genuine finite separable intermediate field is generated by an actual element of the original ambient field. -/
theorem finiteIntermediateField_exists_ambient_generator
    (E : IntermediateField K Ω) [FiniteDimensional K E] [Algebra.IsSeparable K E] :
    ∃ x : Ω, IntermediateField.adjoin K {x} = E := by
  obtain ⟨x, hx⟩ := Field.exists_primitive_element K E
  refine ⟨x.val, ?_⟩
  have h := congrArg (fun F : IntermediateField K E => F.map E.val) hx
  simpa only [IntermediateField.adjoin_map, Set.image_singleton,
    ← AlgHom.fieldRange_eq_map, IntermediateField.fieldRange_val] using h

/-- Every actual finite separable subextension of an original directed field union is contained in one original stage. -/
theorem finiteIntermediateField_le_directed_stage
    {ι : Type*} [Nonempty ι] (F : ι → IntermediateField K Ω)
    (hdir : Directed (· ≤ ·) F)
    (E : IntermediateField K Ω) [FiniteDimensional K E] [Algebra.IsSeparable K E]
    (hE : E ≤ ⨆ i, F i) : ∃ i, E ≤ F i := by
  obtain ⟨x, hx⟩ := finiteIntermediateField_exists_ambient_generator E
  have hxE : x ∈ E := hx ▸ IntermediateField.mem_adjoin_simple_self K x
  have hxs : x ∈ ⨆ i, F i := hE hxE
  change x ∈ ((⨆ i, F i : IntermediateField K Ω) : Set Ω) at hxs
  rw [IntermediateField.coe_iSup_of_directed hdir, Set.mem_iUnion] at hxs
  obtain ⟨i, hi⟩ := hxs
  refine ⟨i, ?_⟩
  rw [← hx]
  exact IntermediateField.adjoin_simple_le_iff.mpr hi

end
end Dubon2026
