import Dubon2026.GramFamilyIsometry

/-! # Genuine Gram-preserving maps on a whole original space generated by a family -/

namespace Dubon2026

noncomputable section

variable {ι E F : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
  [NormedAddCommGroup F] [InnerProductSpace ℂ F]

/-- If the original family spans the whole domain, the genuine Gram construction gives a linear isometry on that entire space. -/
def gramSpanningIsometry (u : ι → E) (v : ι → F)
    (h : ∀ i j, inner ℂ (u i) (u j) = inner ℂ (v i) (v j))
    (hu : Submodule.span ℂ (Set.range u) = ⊤) : E →ₗᵢ[ℂ] F :=
  (gramFamilyRangeIsometry u v h).comp {
    toLinearMap := (LinearEquiv.ofTop (Finsupp.linearCombination ℂ u).range
      ((Finsupp.range_linearCombination ℂ (v := u)).trans hu)).symm.toLinearMap
    norm_map' := fun _ => rfl }

/-- The genuine whole-space isometry sends each actual finite combination to its original counterpart. -/
theorem gramSpanningIsometry_linearCombination (u : ι → E) (v : ι → F)
    (h : ∀ i j, inner ℂ (u i) (u j) = inner ℂ (v i) (v j))
    (hu : Submodule.span ℂ (Set.range u) = ⊤) (a : ι →₀ ℂ) :
    gramSpanningIsometry u v h hu (Finsupp.linearCombination ℂ u a) =
      Finsupp.linearCombination ℂ v a := by
  change gramFamilyRangeMap u v h ⟨Finsupp.linearCombination ℂ u a, _⟩ = _
  exact gramFamilyRangeMap_linearCombination u v h a _

/-- Every original generating vector is sent to exactly its prescribed genuine image. -/
theorem gramSpanningIsometry_family (u : ι → E) (v : ι → F)
    (h : ∀ i j, inner ℂ (u i) (u j) = inner ℂ (v i) (v j))
    (hu : Submodule.span ℂ (Set.range u) = ⊤) (i : ι) :
    gramSpanningIsometry u v h hu (u i) = v i := by
  simpa only [Finsupp.linearCombination_single, one_smul] using
    gramSpanningIsometry_linearCombination u v h hu (Finsupp.single i 1)

/-- The genuine isometry's image is exactly the actual algebraic span of the prescribed second family. -/
theorem gramSpanningIsometry_range (u : ι → E) (v : ι → F)
    (h : ∀ i j, inner ℂ (u i) (u j) = inner ℂ (v i) (v j))
    (hu : Submodule.span ℂ (Set.range u) = ⊤) :
    (gramSpanningIsometry u v h hu).toLinearMap.range = Submodule.span ℂ (Set.range v) := by
  have he : (gramSpanningIsometry u v h hu).toLinearMap.comp (Finsupp.linearCombination ℂ u) =
      Finsupp.linearCombination ℂ v := by
    apply LinearMap.ext
    intro a
    exact gramSpanningIsometry_linearCombination u v h hu a
  have hr := congrArg LinearMap.range he
  rw [LinearMap.range_comp, Finsupp.range_linearCombination, hu, Submodule.map_top,
    Finsupp.range_linearCombination] at hr
  exact hr

end
end Dubon2026
