import Dubon2026.EisensteinLatticeKernel
import Mathlib.NumberTheory.ModularForms.JacobiTheta.TwoVariable
import Mathlib.Analysis.Normed.Ring.InfiniteSum

/-! # The actual determinant-one lattice theta kernel -/

namespace Dubon2026

open UpperHalfPlane

noncomputable section

/-- The positive quadratic form of the actual lattice generated by z and 1, divided by its covolume. -/
def latticeQuadratic (z : ℍ) (v : ℤ × ℤ) : ℝ :=
  (((v.1 : ℝ) * z.re + v.2) ^ 2 + (v.1 : ℝ) ^ 2 * z.im ^ 2) / z.im

/-- The Cartesian form is exactly the squared complex lattice length divided by the covolume. -/
theorem latticeQuadratic_eq_norm (z : ℍ) (v : ℤ × ℤ) :
    latticeQuadratic z v = ‖(v.1 : ℂ) * z + v.2‖ ^ 2 / z.im := by
  rw [latticeQuadratic, ← Complex.normSq_eq_norm_sq]
  simp only [Complex.normSq_apply, Complex.add_re, Complex.mul_re, Complex.intCast_re,
    Complex.intCast_im, zero_mul, sub_zero, Complex.add_im, Complex.mul_im, add_zero]
  change _ = (((v.1 : ℝ) * z.re + v.2) * ((v.1 : ℝ) * z.re + v.2) +
    ((v.1 : ℝ) * z.im) * ((v.1 : ℝ) * z.im)) / z.im
  ring

/-- The genuine lattice quadratic form is nonnegative, including the zero row. -/
theorem latticeQuadratic_nonneg (z : ℍ) (v : ℤ × ℤ) :
    0 ≤ latticeQuadratic z v := by
  rw [latticeQuadratic_eq_norm]
  exact div_nonneg (sq_nonneg _) z.im_pos.le

/-- An explicit positive coercivity constant for this actual lattice. -/
def latticeQuadraticLower (z : ℍ) : ℝ := z.im / (1 + 2 * z.re ^ 2 + 2 * z.im ^ 2)

/-- The coercivity constant is strictly positive at every upper-half-plane point. -/
theorem latticeQuadraticLower_pos (z : ℍ) : 0 < latticeQuadraticLower z := by
  unfold latticeQuadraticLower
  exact div_pos z.im_pos (by positivity)

/-- The actual quadratic form dominates the standard Euclidean square norm. -/
theorem latticeQuadratic_lower (z : ℍ) (v : ℤ × ℤ) :
    latticeQuadraticLower z * ((v.1 : ℝ) ^ 2 + (v.2 : ℝ) ^ 2) ≤ latticeQuadratic z v := by
  unfold latticeQuadraticLower latticeQuadratic
  rw [div_mul_eq_mul_div, div_le_div_iff₀ (by positivity) z.im_pos]
  nlinarith [mul_nonneg (by positivity : 0 ≤ 1 + 2 * z.re ^ 2)
    (sq_nonneg ((v.1 : ℝ) * z.re + v.2)),
    mul_nonneg (sq_nonneg z.im) (sq_nonneg (2 * (v.1 : ℝ) * z.re + v.2)),
    mul_nonneg (sq_nonneg (v.1 : ℝ)) (sq_nonneg (z.im ^ 2))]

/-- The literal Gaussian summand of the actual two-dimensional lattice. -/
def latticeThetaTerm (z : ℍ) (t : ℝ) (v : ℤ × ℤ) : ℝ :=
  Real.exp (-Real.pi * t * latticeQuadratic z v)

/-- The actual lattice theta series includes its single zero-row contribution. -/
def latticeTheta (z : ℍ) (t : ℝ) : ℝ := ∑' v : ℤ × ℤ, latticeThetaTerm z t v

/-- Each actual lattice Gaussian is strictly positive. -/
theorem latticeThetaTerm_pos (z : ℍ) (t : ℝ) (v : ℤ × ℤ) :
    0 < latticeThetaTerm z t v := Real.exp_pos _

/-- The zero row contributes exactly one to the actual theta series. -/
theorem latticeThetaTerm_zero (z : ℍ) (t : ℝ) : latticeThetaTerm z t (0, 0) = 1 := by
  simp [latticeThetaTerm, latticeQuadratic]

/-- Pinned Mathlib's Gaussian estimates give the literal one-dimensional lattice majorant. -/
theorem summable_lattice_gaussian {a : ℝ} (ha : 0 < a) :
    Summable (fun n : ℤ => Real.exp (-Real.pi * a * (n : ℝ) ^ 2)) := by
  simpa only [pow_zero, one_mul, mul_zero, zero_mul, sub_zero, mul_assoc] using
    summable_pow_mul_jacobiTheta₂_term_bound 0 ha 0

/-- A product of genuine one-dimensional Gaussians dominates the actual lattice kernel. -/
theorem latticeThetaTerm_le_product (z : ℍ) {t : ℝ} (ht : 0 < t) (v : ℤ × ℤ) :
    latticeThetaTerm z t v ≤
      Real.exp (-Real.pi * (t * latticeQuadraticLower z) * (v.1 : ℝ) ^ 2) *
      Real.exp (-Real.pi * (t * latticeQuadraticLower z) * (v.2 : ℝ) ^ 2) := by
  rw [latticeThetaTerm, ← Real.exp_add, Real.exp_le_exp]
  have h := mul_le_mul_of_nonpos_left (latticeQuadratic_lower z v)
    (mul_nonpos_of_nonpos_of_nonneg (neg_nonpos.mpr Real.pi_pos.le) ht.le)
  nlinarith

/-- The actual two-dimensional lattice theta series is absolutely convergent for positive t. -/
theorem summable_latticeThetaTerm (z : ℍ) {t : ℝ} (ht : 0 < t) :
    Summable (latticeThetaTerm z t) := by
  have h := summable_lattice_gaussian (mul_pos ht (latticeQuadraticLower_pos z))
  exact (h.mul_of_nonneg h (fun _ => (Real.exp_pos _).le)
    (fun _ => (Real.exp_pos _).le)).of_nonneg_of_le
      (fun v => (latticeThetaTerm_pos z t v).le) (latticeThetaTerm_le_product z ht)

/-- The literal theta sum may be evaluated in either lattice coordinate order. -/
theorem latticeTheta_eq_iterated (z : ℍ) {t : ℝ} (ht : 0 < t) :
    latticeTheta z t = ∑' m : ℤ, ∑' n : ℤ, latticeThetaTerm z t (m, n) :=
  (summable_latticeThetaTerm z ht).tsum_prod

end
end Dubon2026
