import Dubon2026.RealHeckeLift
import Mathlib.RepresentationTheory.Subrepresentation

/-! # The actual cyclic real representation generated by the original cusp lift

This is the algebraic cyclic subrepresentation of the genuine right regular representation.
No adelic irreducibility, smooth globalization or higher symmetric functoriality is asserted.
-/

namespace Dubon2026

noncomputable section
open UpperHalfPlane Matrix.SpecialLinearGroup
open scoped MatrixGroups

/-- The actual span of all right translates of the original cusp lift, with stability proved. -/
def realLiftCyclicRepresentation (k : ℤ) (f : ℍ → ℂ) :
    Subrepresentation (TannakaDuality.FiniteGroup.rightRegular
      (k := ℂ) (G := SL(2, ℝ))) where
  toSubmodule := Submodule.span ℂ (Set.range (fun h : SL(2, ℝ) =>
    TannakaDuality.FiniteGroup.rightRegular h (realWeightLift k f)))
  apply_mem_toSubmodule g v hv := by
    induction hv using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨h, rfl⟩ := hx
      apply Submodule.subset_span
      refine ⟨g * h, ?_⟩
      ext t
      simp [TannakaDuality.FiniteGroup.rightRegular_apply, mul_assoc]
    | zero => simp
    | add x y hx hy hix hiy =>
      rw [map_add]
      exact Submodule.add_mem _ hix hiy
    | smul c x hx hix =>
      rw [map_smul]
      exact Submodule.smul_mem _ c hix

/-- The original lift itself belongs to the actual generated real representation. -/
theorem realWeightLift_mem_cyclic (k : ℤ) (f : ℍ → ℂ) :
    realWeightLift k f ∈ (realLiftCyclicRepresentation k f).toSubmodule := by
  apply Submodule.subset_span
  refine ⟨1, ?_⟩
  simp

/-- Every vector in the actual cyclic representation retains the original arithmetic left invariance. -/
theorem realLiftCyclic_left_invariant {Γ : Subgroup (GL (Fin 2) ℝ)} {k : ℤ}
    (f : CuspForm Γ k) {v : SL(2, ℝ) → ℂ}
    (hv : v ∈ (realLiftCyclicRepresentation k f).toSubmodule)
    (γ : SL(2, ℝ)) (hγ : mapGL ℝ γ ∈ Γ) (g : SL(2, ℝ)) : v (γ * g) = v g := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    simpa only [TannakaDuality.FiniteGroup.rightRegular_apply, mul_assoc] using
      realWeightLift_cusp_left_invariant f γ (g * h) hγ
  | zero => rfl
  | add x y hx hy hix hiy => simp only [Pi.add_apply, hix, hiy]
  | smul c x hx hix => simp only [Pi.smul_apply, hix]

/-- The original finite real Hecke correspondence is a genuine complex-linear operator. -/
def realPrimeHeckeLinear (Q p : ℕ) [NeZero p] :
    (SL(2, ℝ) → ℂ) →ₗ[ℂ] (SL(2, ℝ) → ℂ) where
  toFun := realPrimeHecke Q p
  map_add' f g := by
    ext a
    change realPrimeHecke Q p (f + g) a = realPrimeHecke Q p f a + realPrimeHecke Q p g a
    dsimp only [realPrimeHecke, Pi.add_apply]
    by_cases hc : Nat.Coprime p Q
    · rw [if_pos hc, if_pos hc, if_pos hc, Finset.sum_add_distrib]
      ring
    · rw [if_neg hc, if_neg hc, if_neg hc, Finset.sum_add_distrib]
      ring
  map_smul' c f := by
    ext a
    by_cases hc : Nat.Coprime p Q <;>
      simp [realPrimeHecke, hc, ← Finset.mul_sum, smul_eq_mul, mul_add, mul_left_comm]

/-- Every vector of the genuine primitive cyclic representation has the same original normalized prime eigenvalue. -/
theorem primitive_realPrimeHecke_cyclic_eigenvalue {Q p : ℕ} [NeZero Q] [NeZero p] {k : ℤ}
    (f : PrimitiveCuspForm Q k) (hp : Nat.Prime p) {v : SL(2, ℝ) → ℂ}
    (hv : v ∈ (realLiftCyclicRepresentation k f.toCuspForm).toSubmodule) :
    realPrimeHeckeLinear Q p v = normalizedCuspCoefficients f.toCuspForm p • v := by
  induction hv using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨h, rfl⟩ := hx
    ext g
    change realPrimeHecke Q p (fun t => realWeightLift k f.toCuspForm (t * h)) g =
      normalizedCuspCoefficients f.toCuspForm p * realWeightLift k f.toCuspForm (g * h)
    rw [realPrimeHecke_right_translation, primitive_realPrimeHecke_eigenvalue f hp]
  | zero => simp
  | add x y hx hy hix hiy => simp only [map_add, hix, hiy, smul_add]
  | smul c x hx hix =>
    rw [map_smul, hix]
    exact smul_comm c (normalizedCuspCoefficients f.toCuspForm p) x

end
end Dubon2026
