import Dubon2026.LocalCoefficientReduction
import Mathlib.RingTheory.Ideal.Cotangent

/-! # The actual relative maximal-ideal cotangent quotient -/

namespace Dubon2026

noncomputable section

variable (O R : Type*) [CommRing O] [IsLocalRing O]
  [CommRing R] [IsLocalRing R] [Algebra O R]

/-- The genuine relations in the original maximal ideal: its square and the ideal generated by the original coefficient maximal ideal. -/
def relativeMaximalCotangentRelations : Submodule R (IsLocalRing.maximalIdeal R) :=
  Submodule.comap (IsLocalRing.maximalIdeal R).subtype
    ((IsLocalRing.maximalIdeal R) ^ 2 ⊔
      (IsLocalRing.maximalIdeal O).map (algebraMap O R))

/-- The literal quotient of the original maximal ideal by its square and the original coefficient maximal ideal. -/
def RelativeMaximalCotangent : Type _ :=
  IsLocalRing.maximalIdeal R ⧸ relativeMaximalCotangentRelations O R
  deriving AddCommGroup, Module R

/-- The genuine quotient retains scalar multiplication by the original coefficient ring. -/
instance relativeMaximalCotangentCoefficientModule :
    Module O (RelativeMaximalCotangent O R) :=
  inferInstanceAs (Module O
    (IsLocalRing.maximalIdeal R ⧸ relativeMaximalCotangentRelations O R))

/-- The genuine quotient inherits the original coefficient-to-ring scalar tower. -/
instance relativeMaximalCotangentScalarTower :
    IsScalarTower O R (RelativeMaximalCotangent O R) :=
  inferInstanceAs (IsScalarTower O R
    (IsLocalRing.maximalIdeal R ⧸ relativeMaximalCotangentRelations O R))

/-- The actual quotient map on the original maximal ideal. -/
def relativeMaximalCotangentMk :
    IsLocalRing.maximalIdeal R →ₗ[R] RelativeMaximalCotangent O R :=
  (relativeMaximalCotangentRelations O R).mkQ

/-- Actual maximal-ideal elements have the same relative cotangent class exactly modulo the original square and coefficient ideal. -/
theorem relativeMaximalCotangentMk_eq_iff (x y : IsLocalRing.maximalIdeal R) :
    relativeMaximalCotangentMk O R x = relativeMaximalCotangentMk O R y ↔
      (x.val - y.val) ∈ (IsLocalRing.maximalIdeal R) ^ 2 ⊔
        (IsLocalRing.maximalIdeal O).map (algebraMap O R) :=
  Submodule.Quotient.eq (relativeMaximalCotangentRelations O R)

/-- Every actual relative cotangent class has an original maximal-ideal representative. -/
theorem relativeMaximalCotangentMk_surjective :
    Function.Surjective (relativeMaximalCotangentMk O R) :=
  (relativeMaximalCotangentRelations O R).mkQ_surjective

/-- The original maximal ideal acts by zero on its genuine relative cotangent quotient. -/
theorem relativeMaximalCotangent_torsion :
    Module.IsTorsionBySet R (RelativeMaximalCotangent O R) (IsLocalRing.maximalIdeal R) := by
  apply (Module.isTorsionBySet_quotient_iff _ _).mpr
  intro x r hr
  change r * x.val ∈ (IsLocalRing.maximalIdeal R) ^ 2 ⊔
    (IsLocalRing.maximalIdeal O).map (algebraMap O R)
  apply Ideal.mem_sup_left
  rw [pow_two]
  exact Ideal.mul_mem_mul hr x.property

/-- The actual residue-field vector-space structure on the relative maximal-ideal quotient is induced by its original ring action. -/
instance relativeMaximalCotangentResidueModule :
    Module (IsLocalRing.ResidueField R) (RelativeMaximalCotangent O R) :=
  (relativeMaximalCotangent_torsion O R).module

/-- Original ring scalars and their genuine residues act identically on the relative cotangent quotient. -/
theorem relativeMaximalCotangent_residue_smul (r : R) (x : RelativeMaximalCotangent O R) :
    IsLocalRing.residue R r • x = r • x := rfl

/-- The relative cotangent quotient of a Noetherian original local ring is finite-dimensional over its actual residue field. -/
theorem relativeMaximalCotangent_finite [IsNoetherianRing R] :
    Module.Finite (IsLocalRing.ResidueField R) (RelativeMaximalCotangent O R) := by
  letI : Module.Finite R (RelativeMaximalCotangent O R) :=
    Module.Finite.of_surjective (relativeMaximalCotangentMk O R)
      (relativeMaximalCotangentMk_surjective O R)
  letI : IsScalarTower R (IsLocalRing.ResidueField R) (RelativeMaximalCotangent O R) :=
    (relativeMaximalCotangent_torsion O R).isScalarTower
  exact Module.Finite.of_restrictScalars_finite R (IsLocalRing.ResidueField R)
    (RelativeMaximalCotangent O R)

end
end Dubon2026
