import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs

/-! # The actual polynomial relations for matrix representations of the original group -/

namespace Dubon2026

noncomputable section
open Matrix MvPolynomial
open scoped BigOperators

variable (G ι R : Type*) [Group G] [Fintype ι] [DecidableEq ι] [CommRing R]

/-- The original identity relation on one original matrix entry. -/
def representationCoordinateOneRelation (i j : ι) : MvPolynomial (G × ι × ι) R :=
  X (1, i, j) - (1 : Matrix ι ι (MvPolynomial (G × ι × ι) R)) i j

/-- The original multiplication relation on one matrix entry for two original group elements. -/
def representationCoordinateMulRelation (g h : G) (i j : ι) : MvPolynomial (G × ι × ι) R :=
  X (g * h, i, j) - ∑ k, X (g, i, k) * X (h, k, j)

/-- The ideal generated by the literal identity and multiplication equations of the original group. -/
def representationCoordinateIdeal : Ideal (MvPolynomial (G × ι × ι) R) :=
  Ideal.span (Set.range (fun ij : ι × ι => representationCoordinateOneRelation G ι R ij.1 ij.2) ∪
    Set.range (fun t : (G × G) × (ι × ι) =>
      representationCoordinateMulRelation G ι R t.1.1 t.1.2 t.2.1 t.2.2))

/-- The actual coordinate algebra of representations of the original group on the original finite free matrix module. -/
abbrev RepresentationCoordinateAlgebra :=
  MvPolynomial (G × ι × ι) R ⧸ representationCoordinateIdeal G ι R

/-- The original matrix of polynomial coordinate classes at the original group element. -/
def representationCoordinateMatrix (g : G) : Matrix ι ι (RepresentationCoordinateAlgebra G ι R) :=
  fun i j => Ideal.Quotient.mk (representationCoordinateIdeal G ι R) (X (g, i, j))

/-- Each original identity relation vanishes in the actual coordinate algebra. -/
theorem representationCoordinateOneRelation_zero (i j : ι) :
    Ideal.Quotient.mk (representationCoordinateIdeal G ι R)
      (representationCoordinateOneRelation G ι R i j) = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Or.inl ⟨(i, j), rfl⟩)

/-- Each original multiplication relation vanishes in the actual coordinate algebra. -/
theorem representationCoordinateMulRelation_zero (g h : G) (i j : ι) :
    Ideal.Quotient.mk (representationCoordinateIdeal G ι R)
      (representationCoordinateMulRelation G ι R g h i j) = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Or.inr ⟨((g, h), (i, j)), rfl⟩)

/-- The original universal coordinate matrix at the group identity is the actual identity matrix. -/
theorem representationCoordinateMatrix_one :
    representationCoordinateMatrix G ι R 1 = 1 := by
  apply Matrix.ext
  intro i j
  have h := representationCoordinateOneRelation_zero G ι R i j
  unfold representationCoordinateOneRelation at h
  rw [map_sub] at h
  have he := sub_eq_zero.mp h
  change Ideal.Quotient.mk (representationCoordinateIdeal G ι R) (X (1, i, j)) = _
  by_cases hij : i = j <;> simpa [Matrix.one_apply, hij] using he

/-- The original universal coordinate matrices satisfy the actual group multiplication law. -/
theorem representationCoordinateMatrix_mul (g h : G) :
    representationCoordinateMatrix G ι R (g * h) =
      representationCoordinateMatrix G ι R g * representationCoordinateMatrix G ι R h := by
  apply Matrix.ext
  intro i j
  have he := representationCoordinateMulRelation_zero G ι R g h i j
  unfold representationCoordinateMulRelation at he
  rw [map_sub, map_sum] at he
  simp_rw [map_mul] at he
  exact sub_eq_zero.mp he

end
end Dubon2026
