import Mathlib.Algebra.Lie.UniversalEnveloping

/-! # Genuine generation induction for the universal enveloping algebra -/

namespace Dubon2026

/-- Every element of the actual enveloping algebra is generated by the original Lie algebra and scalars under addition and multiplication. -/
theorem universalEnveloping_induction {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
    (P : UniversalEnvelopingAlgebra R L → Prop)
    (hscalar : ∀ r, P (algebraMap R (UniversalEnvelopingAlgebra R L) r))
    (hgenerator : ∀ x, P (UniversalEnvelopingAlgebra.ι R x))
    (hadd : ∀ x y, P x → P y → P (x + y))
    (hmul : ∀ x y, P x → P y → P (x * y)) (z : UniversalEnvelopingAlgebra R L) : P z := by
  obtain ⟨w, hw⟩ := RingQuot.mkAlgHom_surjective R (UniversalEnvelopingAlgebra.Rel R L) z
  change UniversalEnvelopingAlgebra.mkAlgHom R L w = z at hw
  rw [← hw]
  clear hw z
  induction w using TensorAlgebra.induction with
  | algebraMap r => simpa only [AlgHom.commutes] using hscalar r
  | ι x => exact hgenerator x
  | add x y hx hy => simpa only [map_add] using hadd _ _ hx hy
  | mul x y hx hy => simpa only [map_mul] using hmul _ _ hx hy

end Dubon2026
