import Mathlib.RingTheory.Unramified.Dedekind
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.RingTheory.TensorProduct.Maps
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed

/-! # Genuine finite unramified tensor images in the original ambient field -/

namespace Dubon2026

noncomputable section
open scoped TensorProduct

variable {R A B Ω : Type*} [CommRing R] [CommRing A] [CommRing B] [Field Ω]
  [Algebra R A] [Algebra R B] [Algebra R Ω]

/-- The genuine multiplication map of the original two coefficient images into the original field. -/
def ambientTensorMultiplication (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :
    A ⊗[R] B →ₐ[R] Ω :=
  Algebra.TensorProduct.productMap f g

/-- The actual subalgebra generated by sums of products of the original two images. -/
abbrev AmbientTensorImage (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :=
  (ambientTensorMultiplication f g).range

/-- The original tensor image is finite over the original base when both actual source algebras are finite. -/
theorem ambientTensorImage_finite [Module.Finite R A] [Module.Finite R B]
    (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) : Module.Finite R (AmbientTensorImage f g) :=
  Module.Finite.of_surjective (ambientTensorMultiplication f g).rangeRestrict.toLinearMap
    (ambientTensorMultiplication f g).rangeRestrict_surjective

/-- Formal unramifiedness passes through the actual tensor product and its literal image in the original field. -/
theorem ambientTensorImage_formallyUnramified
    [Algebra.FormallyUnramified R A] [Algebra.FormallyUnramified R B]
    (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :
    Algebra.FormallyUnramified R (AmbientTensorImage f g) := by
  letI : Algebra.FormallyUnramified R (A ⊗[R] B) :=
    Algebra.FormallyUnramified.comp R A (A ⊗[R] B)
  exact Algebra.FormallyUnramified.of_surjective
    (ambientTensorMultiplication f g).rangeRestrict
    (ambientTensorMultiplication f g).rangeRestrict_surjective

/-- The original finite unramified tensor image inside the actual ambient field is a Dedekind domain, hence has the integral-closedness needed for the genuine compositum construction. -/
theorem ambientTensorImage_isDedekindDomain [IsDedekindDomain R]
    [Module.Finite R A] [Module.Finite R B]
    [Algebra.FormallyUnramified R A] [Algebra.FormallyUnramified R B]
    (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) : IsDedekindDomain (AmbientTensorImage f g) := by
  letI := ambientTensorImage_finite f g
  letI := ambientTensorImage_formallyUnramified f g
  exact isDedekindDomain.of_formallyUnramified R (AmbientTensorImage f g)

/-- The genuine tensor image is the integral closure of the original base in its actual field of fractions. Identifying that field with the intended compositum is a separate obligation. -/
theorem ambientTensorImage_isIntegralClosure [IsDedekindDomain R]
    [Module.Finite R A] [Module.Finite R B]
    [Algebra.FormallyUnramified R A] [Algebra.FormallyUnramified R B]
    (f : A →ₐ[R] Ω) (g : B →ₐ[R] Ω) :
    IsIntegralClosure (AmbientTensorImage f g) R (FractionRing (AmbientTensorImage f g)) := by
  letI := ambientTensorImage_finite f g
  letI := ambientTensorImage_isDedekindDomain f g
  exact IsIntegralClosure.of_isIntegrallyClosed
    (AmbientTensorImage f g) R (FractionRing (AmbientTensorImage f g))

end
end Dubon2026
