name = "PrimeShellPhaseI"
version = "0.1.0"
defaultTargets = ["PrimeShell"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "Zeta23"
git = "https://github.com/anthropics/formal-math.git"
rev = "3635e74826a4c1fcece7d1cd2b6fa75e43a00510"

[[lean_lib]]
name = "PrimeShell"
