import RiemannZeta.GuthMaynard.ZetaBounds
import RiemannZeta.GuthMaynard.ZeroCount
import RiemannZeta.External.PNT.ZetaAppendix

open Complex Set MeasureTheory

namespace RiemannZeta.GuthMaynard

/-- The normalized ordinate in the sharp Poisson--Euler--Maclaurin truncation. -/
noncomputable def sharpZetaTheta (s : ℂ) (a : ℝ) : ℝ :=
  s.im / (2 * Real.pi * a)

/-- The explicit coefficient of the `a ^ (-s)` boundary correction in the
sharp Poisson--Euler--Maclaurin truncation. -/
noncomputable def sharpZetaBoundaryCoeff (s : ℂ) (a : ℝ) : ℂ :=
  let ϑ := sharpZetaTheta s a
  if ϑ ≠ 0 then
    Complex.I / 2 *
      (1 / Complex.sin (Real.pi * ϑ) - 1 / (Real.pi * ϑ : ℂ))
  else
    0

/-- The explicit coefficient in the order-`a ^ (-Re(s)-1)` remainder of the
sharp Poisson--Euler--Maclaurin truncation. -/
noncomputable def sharpZetaErrorCoeff (s : ℂ) (a : ℝ) : ℝ :=
  let ϑ := sharpZetaTheta s a
  if ϑ ≠ 0 then
    s.re / 2 *
        ((1 / (Complex.sin (Real.pi * ϑ) ^ 2 : ℂ)).re -
          (1 / ((Real.pi * ϑ) ^ 2 : ℂ)).re) +
      |ϑ| / (2 * Real.pi ^ 2) *
        (1 / (1 - |ϑ|) ^ 3 + 2 * (riemannZeta 3).re - 1)
  else
    s.re / 6

/-- A half-integral truncation length comparable to a positive slab height.
The additive `3/2` keeps the cutoff strictly beyond `4T`, which makes the
Poisson parameter uniformly separated from both `0` and `1`. -/
noncomputable def sharpZetaCutoff (T : ℝ) : ℝ :=
  (⌊4 * T⌋ : ℝ) + 3 / 2

theorem sharpZetaCutoff_isHalfInteger (T : ℝ) :
    (sharpZetaCutoff T).IsHalfInteger := by
  refine ⟨⌊4 * T⌋ + 1, ?_⟩
  simp only [sharpZetaCutoff]
  push_cast
  ring

theorem four_mul_lt_sharpZetaCutoff (T : ℝ) :
    4 * T < sharpZetaCutoff T := by
  have h := Int.lt_floor_add_one (4 * T)
  simp only [sharpZetaCutoff]
  linarith

theorem sharpZetaCutoff_le_add (T : ℝ) :
    sharpZetaCutoff T ≤ 4 * T + 3 / 2 := by
  have h := Int.floor_le (4 * T)
  simp only [sharpZetaCutoff]
  linarith

theorem sharpZetaCutoff_le_six_mul {T : ℝ} (hT : 3 / 4 ≤ T) :
    sharpZetaCutoff T ≤ 6 * T := by
  calc
    sharpZetaCutoff T ≤ 4 * T + 3 / 2 := sharpZetaCutoff_le_add T
    _ ≤ 6 * T := by linarith

theorem sharpZetaCutoff_admissible_of_mem {σ T : ℝ} {ρ : ℂ}
    (hT : 3 / 4 ≤ T) (hρ : ρ ∈ zerosInRect σ 1 T (2 * T)) :
    0 < sharpZetaCutoff T ∧
      (sharpZetaCutoff T).IsHalfInteger ∧
        sharpZetaCutoff T > |ρ.im| / (2 * Real.pi) := by
  rw [zerosInRect, Set.Finite.mem_toFinset, Set.mem_inter_iff] at hρ
  rw [mem_ZeroRectangle] at hρ
  have hTpos : 0 < T := by linarith
  have hρimNonneg : 0 ≤ ρ.im := hTpos.le.trans hρ.1.2.2.1
  have hCutPos : 0 < sharpZetaCutoff T :=
    (by linarith : 0 < 4 * T).trans (four_mul_lt_sharpZetaCutoff T)
  refine ⟨hCutPos, sharpZetaCutoff_isHalfInteger T, ?_⟩
  rw [abs_of_nonneg hρimNonneg]
  have hDen : 0 < 2 * Real.pi := by positivity
  calc
    ρ.im / (2 * Real.pi) ≤ (2 * T) / (2 * Real.pi) :=
      div_le_div_of_nonneg_right hρ.1.2.2.2 hDen.le
    _ < 4 * T := by
      rw [div_lt_iff₀ hDen]
      nlinarith [Real.pi_gt_three]
    _ < sharpZetaCutoff T := four_mul_lt_sharpZetaCutoff T

theorem pi_mul_sharpZetaTheta_eq (s : ℂ) {a : ℝ} (ha : a ≠ 0) :
    Real.pi * sharpZetaTheta s a = s.im / (2 * a) := by
  rw [sharpZetaTheta]
  field_simp [ha, Real.pi_ne_zero]

theorem sharpZetaPhase_mem_Icc_of_mem {σ T : ℝ} {ρ : ℂ}
    (hT : 3 / 4 ≤ T) (hρ : ρ ∈ zerosInRect σ 1 T (2 * T)) :
    Real.pi * sharpZetaTheta ρ (sharpZetaCutoff T) ∈
      Set.Icc (1 / 12 : ℝ) (1 / 4 : ℝ) := by
  rw [zerosInRect, Set.Finite.mem_toFinset, Set.mem_inter_iff] at hρ
  rw [mem_ZeroRectangle] at hρ
  have hTpos : 0 < T := by linarith
  have hCutPos : 0 < sharpZetaCutoff T :=
    (by linarith : 0 < 4 * T).trans (four_mul_lt_sharpZetaCutoff T)
  rw [pi_mul_sharpZetaTheta_eq ρ hCutPos.ne']
  constructor
  · rw [le_div_iff₀ (by positivity : 0 < 2 * sharpZetaCutoff T)]
    have hCutUpper := sharpZetaCutoff_le_six_mul hT
    nlinarith [hρ.1.2.2.1]
  · rw [div_le_iff₀ (by positivity : 0 < 2 * sharpZetaCutoff T)]
    nlinarith [hρ.1.2.2.2, four_mul_lt_sharpZetaCutoff T]

/-- A deliberately coarse explicit lower bound for sine on the compact phase
interval generated by `sharpZetaCutoff`. -/
theorem one_sixteenth_le_sin_of_mem_Icc {x : ℝ}
    (hx : x ∈ Set.Icc (1 / 12 : ℝ) (1 / 4 : ℝ)) :
    1 / 16 ≤ Real.sin x := by
  have hx0 : 0 ≤ x := by linarith [hx.1]
  have hxabs : |x| ≤ 1 := by
    rw [abs_of_nonneg hx0]
    linarith [hx.2]
  have hbound := Real.sin_bound hxabs
  have hlow := (abs_le.mp hbound).1
  rw [abs_of_nonneg hx0] at hlow
  have hx2 : x ^ 2 ≤ 1 / 16 := by
    nlinarith [mul_nonneg hx0 (sub_nonneg.mpr hx.2)]
  have hx3 : x ^ 3 ≤ x / 16 := by
    nlinarith [mul_nonneg hx0 (sub_nonneg.mpr hx2)]
  have hx4 : x ^ 4 ≤ x / 64 := by
    have hmul := mul_le_mul_of_nonneg_left hx3 hx0
    nlinarith
  nlinarith [hx.1]
/-- The explicit Poisson boundary coefficient is uniformly bounded on a
positive dyadic zero slab at the canonical sharp cutoff. -/
theorem sharpZetaBoundaryCoeff_le_fourteen {σ T : ℝ} {ρ : ℂ}
    (hT : 3 / 4 ≤ T) (hρ : ρ ∈ zerosInRect σ 1 T (2 * T)) :
    ‖sharpZetaBoundaryCoeff ρ (sharpZetaCutoff T)‖ ≤ 14 := by
  let θ := sharpZetaTheta ρ (sharpZetaCutoff T)
  let x := Real.pi * θ
  have hx : x ∈ Set.Icc (1 / 12 : ℝ) (1 / 4 : ℝ) := by
    simpa [x, θ] using sharpZetaPhase_mem_Icc_of_mem hT hρ
  have hsinLower : 1 / 16 ≤ Real.sin x := one_sixteenth_le_sin_of_mem_Icc hx
  have hsinPos : 0 < Real.sin x := by linarith
  have hxPos : 0 < x := by linarith [hx.1]
  have hθ : θ ≠ 0 := by
    intro h
    have : x = 0 := by simp [x, h]
    linarith
  have hθ' : sharpZetaTheta ρ (sharpZetaCutoff T) ≠ 0 := by
    simpa [θ] using hθ
  have hsinNorm : ‖Complex.sin (x : ℂ)‖ = Real.sin x := by
    have hs : Complex.sin (x : ℂ) = (Real.sin x : ℂ) :=
      (Complex.ofReal_sin x).symm
    rw [hs, norm_real, Real.norm_eq_abs, abs_of_pos hsinPos]
  have hxNorm : ‖(x : ℂ)‖ = x := by simp [abs_of_pos hxPos]
  have hInvSin : ‖(1 : ℂ) / Complex.sin (x : ℂ)‖ ≤ 16 := by
    rw [norm_div, norm_one, hsinNorm]
    rw [div_le_iff₀ hsinPos]
    nlinarith
  have hInvX : ‖(1 : ℂ) / (x : ℂ)‖ ≤ 12 := by
    rw [norm_div, norm_one, hxNorm]
    rw [div_le_iff₀ hxPos]
    nlinarith [hx.1]
  rw [sharpZetaBoundaryCoeff, if_pos hθ']
  have hxComplex :
      (Real.pi : ℂ) * (sharpZetaTheta ρ (sharpZetaCutoff T) : ℂ) = (x : ℂ) := by
    simp [x, θ]
  rw [hxComplex, norm_mul]
  have hI : ‖Complex.I / (2 : ℂ)‖ = (1 / 2 : ℝ) := by norm_num
  rw [hI]
  calc
    (1 / 2 : ℝ) * ‖(1 : ℂ) / Complex.sin (x : ℂ) - 1 / (x : ℂ)‖ ≤
        (1 / 2 : ℝ) *
          (‖(1 : ℂ) / Complex.sin (x : ℂ)‖ + ‖(1 : ℂ) / (x : ℂ)‖) := by
      gcongr
      exact norm_sub_le _ _
    _ ≤ (1 / 2 : ℝ) * (16 + 12) := by gcongr
    _ = 14 := by norm_num


set_option maxHeartbeats 800000 in
/-- The explicit remainder coefficient in Dadaro's sharp truncation is
uniformly bounded on the classical zero strip at the canonical slab cutoff. -/
theorem sharpZetaErrorCoeff_le_129 {σ T : ℝ} {ρ : ℂ} (hT : 3 / 4 ≤ T)
    (hρ : ρ ∈ zerosInRect σ 1 T (2 * T)) (hρre0 : 0 ≤ ρ.re) (hρre1 : ρ.re ≤ 1) :
    sharpZetaErrorCoeff ρ (sharpZetaCutoff T) ≤ 129 := by
  let θ := sharpZetaTheta ρ (sharpZetaCutoff T)
  let x := Real.pi * θ
  have hx : x ∈ Set.Icc (1 / 12 : ℝ) (1 / 4 : ℝ) := by
    simpa [x, θ] using sharpZetaPhase_mem_Icc_of_mem hT hρ
  have hxPos : 0 < x := by linarith [hx.1]
  have hθPos : 0 < θ := by
    have hpi := Real.pi_pos
    dsimp [x] at hxPos
    nlinarith
  have hθUpper : θ ≤ 1 / 4 := by
    have hpi := Real.pi_gt_three
    dsimp [x] at hx
    nlinarith [hx.2]
  have hθAbs : |θ| = θ := abs_of_pos hθPos
  have hsinLower : 1 / 16 ≤ Real.sin x := one_sixteenth_le_sin_of_mem_Icc hx
  have hsinPos : 0 < Real.sin x := by linarith
  have hsComplex :
      Complex.sin ((Real.pi : ℂ) * (θ : ℂ)) = (Real.sin x : ℂ) := by
    rw [← Complex.ofReal_mul, ← Complex.ofReal_sin]
  have hxComplex : (Real.pi : ℂ) * (θ : ℂ) = (x : ℂ) := by simp [x]
  have hsinNorm : ‖Complex.sin ((Real.pi : ℂ) * (θ : ℂ))‖ = Real.sin x := by
    rw [hsComplex, norm_real, Real.norm_eq_abs, abs_of_pos hsinPos]
  have hA :
      (1 / (Complex.sin ((Real.pi : ℂ) * (θ : ℂ)) ^ 2 : ℂ)).re ≤ 256 := by
    calc
      _ ≤ ‖1 / (Complex.sin ((Real.pi : ℂ) * (θ : ℂ)) ^ 2 : ℂ)‖ :=
        Complex.re_le_norm _
      _ = 1 / (Real.sin x) ^ 2 := by
        rw [norm_div, norm_one, norm_pow, hsinNorm]
      _ ≤ 256 := by
        rw [div_le_iff₀ (sq_pos_of_pos hsinPos)]
        nlinarith
  have hB :
      0 ≤ (1 / (((Real.pi : ℂ) * (θ : ℂ)) ^ 2 : ℂ)).re := by
    rw [hxComplex]
    have heq : ((x : ℂ) ^ 2) = ((x ^ 2 : ℝ) : ℂ) := by norm_cast
    rw [heq]
    norm_cast
    positivity
  have hOneMinus : 3 / 4 ≤ 1 - |θ| := by rw [hθAbs]; linarith
  have hOneMinusPos : 0 < 1 - |θ| := by linarith
  have hCube : 1 / (1 - |θ|) ^ 3 ≤ 4 := by
    rw [div_le_iff₀ (pow_pos hOneMinusPos 3)]
    nlinarith [sq_nonneg (1 - |θ|)]
  have hzetaNorm : ‖riemannZeta (3 : ℂ)‖ ≤ 2 := by
    simpa using zeta_right_half_plane_bound 3 0 (by norm_num)
  have hzetaRe : (riemannZeta 3).re ≤ 2 :=
    (Complex.re_le_norm _).trans hzetaNorm
  have hFirst : ρ.re / 2 *
        ((1 / (Complex.sin ((Real.pi : ℂ) * (θ : ℂ)) ^ 2 : ℂ)).re -
          (1 / (((Real.pi : ℂ) * (θ : ℂ)) ^ 2 : ℂ)).re) ≤ 128 := by
    have hhalf : 0 ≤ ρ.re / 2 := by positivity
    calc
      _ ≤ ρ.re / 2 * 256 := by gcongr; linarith
      _ ≤ 128 := by nlinarith
  have hDen : 18 ≤ 2 * Real.pi ^ 2 := by nlinarith [Real.pi_gt_three]
  have hSecond : |θ| / (2 * Real.pi ^ 2) *
        (1 / (1 - |θ|) ^ 3 + 2 * (riemannZeta 3).re - 1) ≤ 1 := by
    have hCoeffNonneg : 0 ≤ |θ| / (2 * Real.pi ^ 2) := by positivity
    have hCoeff : |θ| / (2 * Real.pi ^ 2) ≤ 1 / 72 := by
      rw [div_le_iff₀ (by positivity : 0 < 2 * Real.pi ^ 2)]
      rw [hθAbs]
      nlinarith [hθUpper, hDen]
    have hBracket :
        1 / (1 - |θ|) ^ 3 + 2 * (riemannZeta 3).re - 1 ≤ 7 := by
      linarith
    by_cases hBracketNonneg : 0 ≤
        1 / (1 - |θ|) ^ 3 + 2 * (riemannZeta 3).re - 1
    · calc
        _ ≤ (1 / 72 : ℝ) * 7 :=
          mul_le_mul hCoeff hBracket hBracketNonneg (by norm_num)
        _ ≤ 1 := by norm_num
    · have := mul_nonpos_of_nonneg_of_nonpos hCoeffNonneg (le_of_not_ge hBracketNonneg)
      linarith
  rw [sharpZetaErrorCoeff, if_pos hθPos.ne']
  have hNum : (128 : ℝ) + 1 ≤ 129 := by norm_num
  have hTotal := (add_le_add hFirst hSecond).trans hNum
  simpa only [θ] using hTotal

/-- PNT+'s kernel-checked sharp truncation theorem, exposed through the
project's #15 interface.  Unlike the absolute Abel-tail estimate below, its
remainder has one extra inverse power of the truncation length. -/
theorem riemannZeta_sharp_halfInteger_truncation {s : ℂ}
    (hs1 : s ≠ 1) (hsigma : 0 ≤ s.re) {a : ℝ} (ha : 0 < a)
    (haHalf : a.IsHalfInteger) (haIm : a > |s.im| / (2 * Real.pi)) :
    ∃ E : ℂ,
      riemannZeta s =
          ∑ n ∈ Finset.Icc 1 ⌊a⌋₊, (n : ℂ) ^ (-s) -
            (a ^ (1 - s) : ℂ) / (1 - s) -
            sharpZetaBoundaryCoeff s a * (a ^ (-s) : ℂ) + E ∧
        ‖E‖ ≤ sharpZetaErrorCoeff s a / a ^ (s.re + 1) := by
  simpa [sharpZetaTheta, sharpZetaBoundaryCoeff, sharpZetaErrorCoeff] using
    ZetaAppendix.proposition_dadaro hs1 hsigma ha haHalf haIm

/-- Sharp truncation specialized at a genuine zeta zero. -/
theorem zeta_zero_sharp_halfInteger_truncation {ρ : ℂ}
    (hρre : 0 < ρ.re) (hρim : ρ.im ≠ 0) (hρzero : riemannZeta ρ = 0)
    {a : ℝ} (ha : 0 < a) (haHalf : a.IsHalfInteger)
    (haIm : a > |ρ.im| / (2 * Real.pi)) :
    ∃ E : ℂ,
      (∑ n ∈ Finset.Icc 1 ⌊a⌋₊, (n : ℂ) ^ (-ρ)) =
          (a ^ (1 - ρ) : ℂ) / (1 - ρ) +
            sharpZetaBoundaryCoeff ρ a * (a ^ (-ρ) : ℂ) - E ∧
        ‖E‖ ≤ sharpZetaErrorCoeff ρ a / a ^ (ρ.re + 1) := by
  have hρ1 : ρ ≠ 1 := ne_of_apply_ne im (by simpa using hρim)
  obtain ⟨E, hEq, hE⟩ :=
    riemannZeta_sharp_halfInteger_truncation hρ1 hρre.le ha haHalf haIm
  refine ⟨E, ?_, hE⟩
  rw [hρzero] at hEq
  linear_combination -hEq

/-- Norm form of the sharp zero truncation.  The three terms are respectively
the pole boundary, the bounded Poisson boundary correction, and the
order-`a ^ (-Re(ρ)-1)` remainder. -/
theorem norm_zeta_zero_sharp_sum_le {ρ : ℂ}
    (hρre : 0 < ρ.re) (hρim : ρ.im ≠ 0) (hρzero : riemannZeta ρ = 0)
    {a : ℝ} (ha : 0 < a) (haHalf : a.IsHalfInteger)
    (haIm : a > |ρ.im| / (2 * Real.pi)) :
    ‖∑ n ∈ Finset.Icc 1 ⌊a⌋₊, (n : ℂ) ^ (-ρ)‖ ≤
      ‖(a ^ (1 - ρ) : ℂ) / (1 - ρ)‖ +
        ‖sharpZetaBoundaryCoeff ρ a * (a ^ (-ρ) : ℂ)‖ +
          sharpZetaErrorCoeff ρ a / a ^ (ρ.re + 1) := by
  obtain ⟨E, hEq, hE⟩ :=
    zeta_zero_sharp_halfInteger_truncation hρre hρim hρzero ha haHalf haIm
  rw [hEq]
  calc
    ‖(a ^ (1 - ρ) : ℂ) / (1 - ρ) +
          sharpZetaBoundaryCoeff ρ a * (a ^ (-ρ) : ℂ) - E‖ ≤
        ‖(a ^ (1 - ρ) : ℂ) / (1 - ρ) +
          sharpZetaBoundaryCoeff ρ a * (a ^ (-ρ) : ℂ)‖ + ‖E‖ := norm_sub_le _ _
    _ ≤ (‖(a ^ (1 - ρ) : ℂ) / (1 - ρ)‖ +
          ‖sharpZetaBoundaryCoeff ρ a * (a ^ (-ρ) : ℂ)‖) + ‖E‖ := by
      gcongr
      exact norm_add_le _ _
    _ ≤ ‖(a ^ (1 - ρ) : ℂ) / (1 - ρ)‖ +
        ‖sharpZetaBoundaryCoeff ρ a * (a ^ (-ρ) : ℂ)‖ +
          sharpZetaErrorCoeff ρ a / a ^ (ρ.re + 1) := by
      gcongr

set_option maxHeartbeats 800000 in
/-- Detector-strength sharp truncation on a positive dyadic zero slab. The
cutoff is O(T), while the partial zeta sum is O(a⁻ᴿᵉ⁽ρ⁾) with the explicit
absolute constant 149. -/
theorem norm_zeta_zero_sharp_cutoff_sum_le {σ T : ℝ} {ρ : ℂ} (hT : 3 / 4 ≤ T)
    (hρmem : ρ ∈ zerosInRect σ 1 T (2 * T)) (hσ : 0 < σ) :
    ‖∑ n ∈ Finset.Icc 1 ⌊sharpZetaCutoff T⌋₊, (n : ℂ) ^ (-ρ)‖ ≤
      149 * sharpZetaCutoff T ^ (-ρ.re) := by
  have hρ := hρmem
  rw [zerosInRect, Set.Finite.mem_toFinset, Set.mem_inter_iff] at hρ
  rcases hρ with ⟨hRect, hZero⟩
  rw [mem_ZeroRectangle] at hRect
  have hTpos : 0 < T := by linarith
  have hρrePos : 0 < ρ.re := hσ.trans_le hRect.1
  have hρreOne : ρ.re ≤ 1 := hRect.2.1
  have hρimPos : 0 < ρ.im := hTpos.trans_le hRect.2.2.1
  have hAdmissible := sharpZetaCutoff_admissible_of_mem hT hρmem
  rcases hAdmissible with ⟨hCutPos, hCutHalf, hCutIm⟩
  have hMain := norm_zeta_zero_sharp_sum_le hρrePos hρimPos.ne' hZero
    hCutPos hCutHalf hCutIm
  have hCutUpper := sharpZetaCutoff_le_six_mul hT
  have hDen : T ≤ ‖(1 : ℂ) - ρ‖ := by
    calc
      T ≤ ρ.im := hRect.2.2.1
      _ = |ρ.im| := (abs_of_pos hρimPos).symm
      _ = |((1 : ℂ) - ρ).im| := by simp
      _ ≤ ‖(1 : ℂ) - ρ‖ := abs_im_le_norm _
  have hDenPos : 0 < ‖(1 : ℂ) - ρ‖ := hTpos.trans_le hDen
  have hCutRatio : sharpZetaCutoff T / ‖(1 : ℂ) - ρ‖ ≤ 6 := by
    rw [div_le_iff₀ hDenPos]
    nlinarith
  have hPowSplit :
      sharpZetaCutoff T ^ (1 - ρ.re) =
        sharpZetaCutoff T * sharpZetaCutoff T ^ (-ρ.re) := by
    rw [show 1 - ρ.re = 1 + (-ρ.re) by ring,
      Real.rpow_add hCutPos, Real.rpow_one]
  have hPole : ‖(sharpZetaCutoff T ^ (1 - ρ) : ℂ) / (1 - ρ)‖ ≤
      6 * sharpZetaCutoff T ^ (-ρ.re) := by
    rw [norm_div, norm_cpow_eq_rpow_re_of_pos hCutPos]
    simp only [one_re, sub_re]
    rw [hPowSplit]
    calc
      sharpZetaCutoff T * sharpZetaCutoff T ^ (-ρ.re) /
          ‖(1 : ℂ) - ρ‖ =
          (sharpZetaCutoff T / ‖(1 : ℂ) - ρ‖) *
            sharpZetaCutoff T ^ (-ρ.re) := by ring
      _ ≤ 6 * sharpZetaCutoff T ^ (-ρ.re) :=
        mul_le_mul_of_nonneg_right hCutRatio (Real.rpow_nonneg hCutPos.le _)
  have hBoundary :
      ‖sharpZetaBoundaryCoeff ρ (sharpZetaCutoff T) *
          (sharpZetaCutoff T ^ (-ρ) : ℂ)‖ ≤
        14 * sharpZetaCutoff T ^ (-ρ.re) := by
    rw [norm_mul, norm_cpow_eq_rpow_re_of_pos hCutPos]
    simp only [neg_re]
    exact mul_le_mul_of_nonneg_right
      (sharpZetaBoundaryCoeff_le_fourteen hT hρmem)
      (Real.rpow_nonneg hCutPos.le _)
  have hCutOne : 1 ≤ sharpZetaCutoff T := by
    linarith [four_mul_lt_sharpZetaCutoff T]
  have hError :
      sharpZetaErrorCoeff ρ (sharpZetaCutoff T) /
          sharpZetaCutoff T ^ (ρ.re + 1) ≤
        129 * sharpZetaCutoff T ^ (-ρ.re) := by
    calc
      _ ≤ 129 / sharpZetaCutoff T ^ (ρ.re + 1) := by
        gcongr
        exact sharpZetaErrorCoeff_le_129 hT hρmem hρrePos.le hρreOne
      _ = 129 * sharpZetaCutoff T ^ (-(ρ.re + 1)) := by
        rw [div_eq_mul_inv, ← Real.rpow_neg hCutPos.le]
      _ ≤ 129 * sharpZetaCutoff T ^ (-ρ.re) := by
        gcongr
        linarith
  calc
    ‖∑ n ∈ Finset.Icc 1 ⌊sharpZetaCutoff T⌋₊, (n : ℂ) ^ (-ρ)‖ ≤
        ‖(sharpZetaCutoff T ^ (1 - ρ) : ℂ) / (1 - ρ)‖ +
          ‖sharpZetaBoundaryCoeff ρ (sharpZetaCutoff T) *
            (sharpZetaCutoff T ^ (-ρ) : ℂ)‖ +
            sharpZetaErrorCoeff ρ (sharpZetaCutoff T) /
              sharpZetaCutoff T ^ (ρ.re + 1) := hMain
    _ ≤ 6 * sharpZetaCutoff T ^ (-ρ.re) +
          14 * sharpZetaCutoff T ^ (-ρ.re) +
            129 * sharpZetaCutoff T ^ (-ρ.re) := by gcongr
    _ = 149 * sharpZetaCutoff T ^ (-ρ.re) := by ring

/-- The fractional-part tail in the first-order Euler--Maclaurin formula for zeta,
with a variable positive lower limit. -/
noncomputable def abelZetaTail (b : ℝ) (s : ℂ) : ℂ :=
  ∫ t in Ioi b, ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1))

theorem integrableOn_abelZetaTail_integrand {b : ℝ} (hb : 1 ≤ b) {s : ℂ}
    (hs : 0 < s.re) :
    IntegrableOn
      (fun t : ℝ => ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1)))
      (Ioi b) :=
  (integrableOn_abelZetaRemainder_integrand hs).mono_set (Ioi_subset_Ioi hb)

theorem abelZetaRemainder_eq_finite_add_tail {b : ℝ} (hb : 1 ≤ b) {s : ℂ}
    (hs : 0 < s.re) :
    abelZetaRemainder s =
      (∫ t in Ioc (1 : ℝ) b,
        ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1))) + abelZetaTail b s := by
  have hAll := integrableOn_abelZetaRemainder_integrand hs
  have hLeft : IntegrableOn
      (fun t : ℝ => ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1)))
      (Ioc (1 : ℝ) b) :=
    hAll.mono_set Ioc_subset_Ioi_self
  have hRight := integrableOn_abelZetaTail_integrand hb hs
  rw [abelZetaRemainder_eq_integral hs, ← Ioc_union_Ioi_eq_Ioi hb,
    setIntegral_union Ioc_disjoint_Ioi_same measurableSet_Ioi hLeft hRight,
    abelZetaTail]

theorem sum_cpow_neg_eq_boundary_add_floor_integral {b : ℕ} (hb : 1 ≤ b) {s : ℂ}
    (hs : 0 < s.re) :
    ∑ n ∈ Finset.Icc 1 b, (n : ℂ) ^ (-s) =
      (b : ℂ) ^ (1 - s) + s * ∫ t in Ioc (1 : ℝ) b,
        (⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1)) := by
  let c : ℕ → ℂ := fun n => if n = 0 then 0 else 1
  have hs0 : s ≠ 0 := ne_zero_of_re_pos hs
  have hDiff : ∀ t ∈ Set.Icc ((1 : ℕ) : ℝ) (b : ℝ),
      DifferentiableAt ℝ (fun x : ℝ => (x : ℂ) ^ (-s)) t := by
    intro t ht
    have ht1 : (1 : ℝ) ≤ t := by simpa using ht.1
    exact differentiableAt_id.ofReal_cpow_const (zero_lt_one.trans_le ht1).ne'
      (neg_ne_zero.mpr hs0)
  have hInt : IntegrableOn (deriv (fun x : ℝ => (x : ℂ) ^ (-s)))
      (Set.Icc ((1 : ℕ) : ℝ) (b : ℝ)) := by
    exact (Iff.mpr integrableOn_Ici_iff_integrableOn_Ioi
      (integrableOn_Ioi_deriv_ofReal_cpow (s := -s) zero_lt_one (by simp [hs]))).mono_set
        (by
          intro t ht
          change (1 : ℝ) ≤ t
          simpa using ht.1)
  have hAbel := sum_mul_eq_sub_sub_integral_mul' (f := fun x : ℝ => (x : ℂ) ^ (-s))
    c hb hDiff hInt
  have hSumC (m : ℕ) : ∑ n ∈ Finset.Icc 0 m, c n = (m : ℂ) := by
    rw [Finset.Icc_eq_cons_Ioc (Nat.zero_le m), Finset.sum_cons]
    simp only [c, if_pos, zero_add]
    calc
      (∑ n ∈ Finset.Ioc 0 m, if n = 0 then (0 : ℂ) else 1) =
          ∑ _n ∈ Finset.Ioc 0 m, (1 : ℂ) := by
        apply Finset.sum_congr rfl
        intro n hn
        rw [if_neg (ne_of_gt (Finset.mem_Ioc.mp hn).1)]
      _ = (m : ℂ) := by simp
  have hLhs :
      (∑ n ∈ Finset.Ioc 1 b, (n : ℂ) ^ (-s) * c n) =
        ∑ n ∈ Finset.Ioc 1 b, (n : ℂ) ^ (-s) := by
    apply Finset.sum_congr rfl
    intro n hn
    simp only [c]
    rw [if_neg (ne_of_gt (zero_lt_one.trans (Finset.mem_Ioc.mp hn).1)), mul_one]
  have hDerivIntegral :
      (∫ t in Ioc (1 : ℝ) b,
        deriv (fun x : ℝ => (x : ℂ) ^ (-s)) t * (⌊t⌋₊ : ℂ)) =
        -s * ∫ t in Ioc (1 : ℝ) b,
          (⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1)) := by
    calc
      (∫ t in Ioc (1 : ℝ) b,
          deriv (fun x : ℝ => (x : ℂ) ^ (-s)) t * (⌊t⌋₊ : ℂ)) =
          ∫ t in Ioc (1 : ℝ) b,
            (-s) * ((⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1))) := by
        apply setIntegral_congr_fun measurableSet_Ioc
        intro t ht
        change deriv (fun x : ℝ => (x : ℂ) ^ (-s)) t * (⌊t⌋₊ : ℂ) =
          (-s) * ((⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1)))
        rw [Complex.deriv_ofReal_cpow_const (by linarith [ht.1]) (neg_ne_zero.mpr hs0)]
        rw [show -s - 1 = -(s + 1) by ring]
        ring
      _ = -s * ∫ t in Ioc (1 : ℝ) b,
          (⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1)) := by
        exact integral_const_mul (μ := volume.restrict (Ioc (1 : ℝ) b)) (-s) _
  simp only [Complex.ofReal_natCast] at hAbel
  rw [hLhs] at hAbel
  simp only [hSumC] at hAbel
  have hAbel' :
      (∑ n ∈ Finset.Ioc 1 b, (n : ℂ) ^ (-s)) =
        (b : ℂ) ^ (-s) * b - 1 -
          ∫ t in Ioc (1 : ℝ) b,
            deriv (fun x : ℝ => (x : ℂ) ^ (-s)) t * (⌊t⌋₊ : ℂ) := by
    simpa using hAbel
  rw [Finset.Icc_eq_cons_Ioc hb, Finset.sum_cons]
  simp only [Nat.cast_one, one_cpow]
  rw [hAbel', hDerivIntegral]
  have hb0 : (b : ℂ) ≠ 0 := by exact_mod_cast (Nat.ne_zero_of_lt (zero_lt_one.trans_le hb))
  rw [show (b : ℂ) ^ (1 - s) = (b : ℂ) * (b : ℂ) ^ (-s) by
    rw [sub_eq_add_neg, cpow_add _ _ hb0, cpow_one]]
  ring

theorem integral_Ioc_cpow_neg {b : ℝ} (hb : 1 ≤ b) {s : ℂ} (hs1 : s ≠ 1) :
    (∫ t in Ioc (1 : ℝ) b, (t : ℂ) ^ (-s)) =
      ((b : ℂ) ^ (1 - s) - 1) / (1 - s) := by
  have hnotmem : (0 : ℝ) ∉ Set.uIcc (1 : ℝ) b := by
    apply Set.notMem_uIcc_of_lt <;> positivity
  rw [← intervalIntegral.integral_of_le hb]
  rw [integral_cpow (Or.inr ⟨by grind, hnotmem⟩)]
  simp only [ofReal_one, one_cpow]
  congr 2 <;> ring_nf

theorem floor_cpow_integral_eq_sub_fract {b : ℕ} (hb : 1 ≤ b) {s : ℂ}
    (hs : 0 < s.re) :
    (∫ t in Ioc (1 : ℝ) b, (⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1))) =
      (∫ t in Ioc (1 : ℝ) b, (t : ℂ) ^ (-s)) -
        ∫ t in Ioc (1 : ℝ) b,
          ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1)) := by
  have hnotmem : (0 : ℝ) ∉ Set.uIcc (1 : ℝ) (b : ℝ) := by
    apply Set.notMem_uIcc_of_lt <;> positivity
  have hPower : IntegrableOn (fun t : ℝ => (t : ℂ) ^ (-s)) (Ioc (1 : ℝ) b) :=
    (intervalIntegrable_iff_integrableOn_Ioc_of_le (by exact_mod_cast hb)).mp
      (intervalIntegral.intervalIntegrable_cpow (Or.inr hnotmem))
  have hFract : IntegrableOn
      (fun t : ℝ => ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1)))
      (Ioc (1 : ℝ) b) :=
    (integrableOn_abelZetaRemainder_integrand hs).mono_set Ioc_subset_Ioi_self
  calc
    (∫ t in Ioc (1 : ℝ) b, (⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1))) =
        ∫ t in Ioc (1 : ℝ) b,
          ((t : ℂ) ^ (-s) -
            ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1))) := by
      apply setIntegral_congr_fun measurableSet_Ioc
      intro t ht
      change (⌊t⌋₊ : ℂ) * (t : ℂ) ^ (-(s + 1)) =
        (t : ℂ) ^ (-s) - ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1))
      rw [natFloor_cast_complex t ht.1, sub_mul]
      congr 1
      have ht0 : (t : ℂ) ≠ 0 := ofReal_ne_zero.mpr (ne_of_gt (zero_lt_one.trans ht.1))
      calc
        (t : ℂ) * (t : ℂ) ^ (-(s + 1)) =
            (t : ℂ) ^ (1 : ℂ) * (t : ℂ) ^ (-(s + 1)) := by rw [cpow_one]
        _ = (t : ℂ) ^ ((1 : ℂ) + (-(s + 1))) := (cpow_add _ _ ht0).symm
        _ = (t : ℂ) ^ (-s) := by
          congr 1
          ring
    _ = (∫ t in Ioc (1 : ℝ) b, (t : ℂ) ^ (-s)) -
        ∫ t in Ioc (1 : ℝ) b,
          ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1)) := by
      rw [integral_sub hPower hFract]

/-- Uniform first-order Euler--Maclaurin truncation of the analytically continued
Riemann zeta function on `Re(s) > 0`, away from its pole. -/
theorem riemannZeta_truncation {b : ℕ} (hb : 1 ≤ b) {s : ℂ}
    (hs : 0 < s.re) (hs1 : s ≠ 1) :
    ∑ n ∈ Finset.Icc 1 b, (n : ℂ) ^ (-s) =
      riemannZeta s + (b : ℂ) ^ (1 - s) / (1 - s) + s * abelZetaTail b s := by
  rw [sum_cpow_neg_eq_boundary_add_floor_integral hb hs,
    floor_cpow_integral_eq_sub_fract hb hs,
    integral_Ioc_cpow_neg (by exact_mod_cast hb) hs1,
    riemannZeta_eq_abel hs hs1,
    abelZetaRemainder_eq_finite_add_tail
      (show (1 : ℝ) ≤ (b : ℝ) by exact_mod_cast hb) hs,
    abelZetaTail]
  simp only [Complex.ofReal_natCast]
  have hden : (1 - s) ≠ 0 := sub_ne_zero.mpr hs1.symm
  have hden' : (s - 1) ≠ 0 := sub_ne_zero.mpr hs1
  field_simp [hden, hden']
  ring_nf

/-- Euler--Maclaurin specialized at a zeta zero away from the real axis. -/
theorem zeta_zero_truncation {b : ℕ} (hb : 1 ≤ b) {ρ : ℂ}
    (hρre : 0 < ρ.re) (hρim : ρ.im ≠ 0) (hρzero : riemannZeta ρ = 0) :
    ∑ n ∈ Finset.Icc 1 b, (n : ℂ) ^ (-ρ) =
      (b : ℂ) ^ (1 - ρ) / (1 - ρ) + ρ * abelZetaTail b ρ := by
  have hρ1 : ρ ≠ 1 := ne_of_apply_ne im (by simpa using hρim)
  rw [riemannZeta_truncation hb hρre hρ1, hρzero, zero_add]

/-- Uniform Euler--Maclaurin tail bound.  The factor `1/2` available after centering
the fractional part is deliberately not used here; this form matches the project's
existing Abel continuation and is sufficient for epsilon-power estimates. -/
theorem norm_abelZetaTail_le {b : ℝ} (hb : 1 ≤ b) {s : ℂ} (hs : 0 < s.re) :
    ‖abelZetaTail b s‖ ≤ b ^ (-s.re) / s.re := by
  have hbPos : 0 < b := zero_lt_one.trans_le hb
  have hInt := integrableOn_abelZetaTail_integrand hb hs
  have hPower : IntegrableOn (fun t : ℝ => t ^ (-s.re - 1)) (Ioi b) :=
    integrableOn_Ioi_rpow_of_lt (by linarith) hbPos
  rw [abelZetaTail]
  calc
    ‖∫ t in Ioi b, ((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1))‖ ≤
        ∫ t in Ioi b, ‖((Int.fract t : ℝ) : ℂ) * (t : ℂ) ^ (-(s + 1))‖ :=
      norm_integral_le_integral_norm _
    _ ≤ ∫ t in Ioi b, t ^ (-s.re - 1) := by
      apply setIntegral_mono_on hInt.norm hPower measurableSet_Ioi
      intro t ht
      rw [norm_mul, norm_real, Real.norm_eq_abs, abs_of_nonneg (Int.fract_nonneg t),
        norm_cpow_eq_rpow_re_of_pos (hbPos.trans ht)]
      change Int.fract t * t ^ (-(s.re + 1)) ≤ t ^ (-s.re - 1)
      rw [show -(s.re + 1) = -s.re - 1 by ring]
      have hpow : 0 ≤ t ^ (-s.re - 1) := Real.rpow_nonneg (hbPos.trans ht).le _
      exact mul_le_of_le_one_left hpow (Int.fract_lt_one t).le
    _ = b ^ (-s.re) / s.re := by
      rw [integral_Ioi_rpow_of_lt (by linarith) hbPos]
      rw [show -s.re - 1 + 1 = -s.re by ring, neg_div_neg_eq]

/-- Quantitative zero-specialized truncation error, uniform in the truncation point. -/
theorem norm_zeta_zero_truncation_error_le {b : ℕ} (hb : 1 ≤ b) {ρ : ℂ}
    (hρre : 0 < ρ.re) (hρim : ρ.im ≠ 0) (hρzero : riemannZeta ρ = 0) :
    ‖(∑ n ∈ Finset.Icc 1 b, (n : ℂ) ^ (-ρ)) -
        (b : ℂ) ^ (1 - ρ) / (1 - ρ)‖ ≤
      ‖ρ‖ * (b : ℝ) ^ (-ρ.re) / ρ.re := by
  rw [zeta_zero_truncation hb hρre hρim hρzero]
  ring_nf
  rw [norm_mul]
  calc
    ‖ρ‖ * ‖abelZetaTail (b : ℝ) ρ‖ ≤ ‖ρ‖ * ((b : ℝ) ^ (-ρ.re) / ρ.re) :=
      mul_le_mul_of_nonneg_left
        (norm_abelZetaTail_le (show (1 : ℝ) ≤ (b : ℝ) by exact_mod_cast hb) hρre)
        (norm_nonneg ρ)
    _ = ‖ρ‖ * (b : ℝ) ^ (-ρ.re) / ρ.re := by ring

end RiemannZeta.GuthMaynard
