import Tao2026.ExceptionalCharacterBHM
import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Algebra.Order.Floor.Semifield

/-!
# Finite divisor-sum weights for Tao's fundamental-lemma sieve

Lemma 5.4 supplies coefficients `λ_d` supported on `d ≤ R` and the
nonnegative divisor-sum weight `ν(n) = ∑_{d∣n} λ_d`.  This file formalizes the
finite algebra surrounding that analytic existence theorem: the literal
weight, its value on primes above the level, and its exact total-mass
expansion.  No existence or asymptotic bound for the coefficients is assumed
or claimed here.
-/

namespace Tao2026

open Finset
open scoped BigOperators

noncomputable section

/-- The level-`R` divisor-sum weight generated by coefficients `λ_d`. -/
def taoDivisorSieveWeight (R : ℕ) (lam : ℕ → ℝ) (n : ℕ) : ℝ :=
  ∑ d ∈ Finset.Icc 1 R, if d ∣ n then lam d else 0

/-- Literal nonnegativity property required of the upper-bound sieve weight
in Lemma 5.4. -/
def IsNonnegativeTaoDivisorSieveWeight (R : ℕ) (lam : ℕ → ℝ) : Prop :=
  ∀ n, 0 ≤ taoDivisorSieveWeight R lam n

/-- If `λ₁=1`, the divisor-sum weight is exactly one at every prime above the
sieve level. -/
theorem taoDivisorSieveWeight_prime_eq_one
    {R p : ℕ} {lam : ℕ → ℝ} (hR : 1 ≤ R) (hp : Nat.Prime p)
    (hlevel : R < p) (hlamOne : lam 1 = 1) :
    taoDivisorSieveWeight R lam p = 1 := by
  unfold taoDivisorSieveWeight
  rw [Finset.sum_eq_single 1]
  · simp [hlamOne]
  · intro d hd hdOne
    have hdData := Finset.mem_Icc.mp hd
    have hnotdvd : ¬d ∣ p := by
      intro hdp
      rcases (Nat.dvd_prime hp).mp hdp with hdEq | hdEq
      · exact hdOne hdEq
      · omega
    simp [hnotdvd]
  · intro hnot
    exact (hnot (Finset.mem_Icc.mpr ⟨le_rfl, hR⟩)).elim

/-- In particular, if the sieve level lies below the dyadic prime scale, the
weight is one at every prime tested by `s_Z`. -/
theorem taoDivisorSieveWeight_eq_one_on_dyadicPrimeBand
    {R Z : ℕ} {lam : ℕ → ℝ} (hR : 1 ≤ R) (hRZ : R < Z)
    (hlamOne : lam 1 = 1) :
    ∀ p ∈ taoDyadicPrimeBand Z, taoDivisorSieveWeight R lam p = 1 := by
  intro p hp
  have hpData := mem_taoDyadicPrimeBand.mp hp
  exact taoDivisorSieveWeight_prime_eq_one hR hpData.1
    (hRZ.trans_le hpData.2.1) hlamOne

/-- Exact mass expansion of the divisor-sum weight on the positive interval
`1 ≤ n ≤ X`.  The multiplicity of `d` is exactly `⌊X/d⌋`. -/
theorem sum_taoDivisorSieveWeight_Ioc_eq
    (R X : ℕ) (lam : ℕ → ℝ) :
    (∑ n ∈ Finset.Ioc 0 X, taoDivisorSieveWeight R lam n) =
      ∑ d ∈ Finset.Icc 1 R, (X / d : ℕ) * lam d := by
  unfold taoDivisorSieveWeight
  rw [Finset.sum_comm]
  apply sum_congr rfl
  intro d hd
  calc
    (∑ x ∈ Finset.Ioc 0 X, if d ∣ x then lam d else 0) =
        ∑ x ∈ (Finset.Ioc 0 X).filter (fun x => d ∣ x), lam d := by
      rw [Finset.sum_filter]
    _ = ((Finset.Ioc 0 X).filter (fun x => d ∣ x)).card * lam d := by
      simp
    _ = (X / d : ℕ) * lam d := by
      rw [Nat.Ioc_filter_dvd_card_eq_div]

/-- The coefficient `ℓ¹` mass on the level interval is at most `R` when every
coefficient has modulus at most one. -/
theorem sum_abs_sieveCoefficient_le_level
    (R : ℕ) (lam : ℕ → ℝ)
    (hlam : ∀ d ∈ Finset.Icc 1 R, |lam d| ≤ 1) :
    (∑ d ∈ Finset.Icc 1 R, |lam d|) ≤ R := by
  calc
    (∑ d ∈ Finset.Icc 1 R, |lam d|) ≤
        ∑ _d ∈ Finset.Icc 1 R, (1 : ℝ) := sum_le_sum hlam
    _ = (Finset.Icc 1 R).card := by simp
    _ ≤ R := by
      simp [Nat.card_Icc]

/-- The main coefficient mass appearing in Lemma 5.4. -/
def taoSieveCoefficientMainMass (R : ℕ) (lam : ℕ → ℝ) : ℝ :=
  ∑ d ∈ Finset.Icc 1 R, lam d / d

/-- Natural division differs from real division by at most one. -/
theorem abs_natCast_div_sub_realDiv_le_one
    (X d : ℕ) (_hd : 0 < d) :
    |((X / d : ℕ) : ℝ) - (X : ℝ) / d| ≤ 1 := by
  have hfloor :
      ⌊(X : ℝ) / (d : ℝ)⌋₊ = X / d :=
    Nat.floor_div_eq_div (K := ℝ) X d
  have h := Nat.abs_floor_sub_le
    (a := (X : ℝ) / (d : ℝ))
    (div_nonneg (Nat.cast_nonneg X) (Nat.cast_nonneg d))
  simpa only [hfloor] using h

/-- One floor-weighted coefficient differs from its real main term by at most
the modulus of that coefficient. -/
theorem abs_floorCoefficient_sub_main_le
    (X d : ℕ) (lam : ℕ → ℝ) (hd : 0 < d) :
    |((X / d : ℕ) : ℝ) * lam d - ((X : ℝ) / d) * lam d| ≤
      |lam d| := by
  rw [← sub_mul, abs_mul]
  calc
    |((X / d : ℕ) : ℝ) - (X : ℝ) / d| * |lam d| ≤
        1 * |lam d| := by
      exact mul_le_mul_of_nonneg_right
        (abs_natCast_div_sub_realDiv_le_one X d hd) (abs_nonneg _)
    _ = |lam d| := one_mul _

/-- Exact `O(R)` floor-error estimate for the sieve mass.  Consequently an
`O(1/log R)` bound for `Σ λ_d/d`, together with `X ≫ R²`, gives the mass bound
used on the diagonal in Lemma 5.1. -/
theorem abs_sum_taoDivisorSieveWeight_sub_main_le_level
    (R X : ℕ) (lam : ℕ → ℝ)
    (hlam : ∀ d ∈ Finset.Icc 1 R, |lam d| ≤ 1) :
    |(∑ n ∈ Finset.Ioc 0 X, taoDivisorSieveWeight R lam n) -
        (X : ℝ) * taoSieveCoefficientMainMass R lam| ≤ R := by
  rw [sum_taoDivisorSieveWeight_Ioc_eq]
  unfold taoSieveCoefficientMainMass
  rw [Finset.mul_sum, ← Finset.sum_sub_distrib]
  calc
    |∑ d ∈ Finset.Icc 1 R,
        (((X / d : ℕ) : ℝ) * lam d -
          (X : ℝ) * (lam d / (d : ℝ)))| ≤
        ∑ d ∈ Finset.Icc 1 R,
          |(((X / d : ℕ) : ℝ) * lam d -
            (X : ℝ) * (lam d / (d : ℝ)))| :=
      abs_sum_le_sum_abs _ _
    _ ≤ ∑ d ∈ Finset.Icc 1 R, |lam d| := by
      apply sum_le_sum
      intro d hd
      have hdPos : 0 < d := (Finset.mem_Icc.mp hd).1
      convert abs_floorCoefficient_sub_main_le X d lam hdPos using 1
      ring_nf
    _ ≤ R := sum_abs_sieveCoefficient_le_level R lam hlam

/-- The upper-bound form of the exact floor-error estimate. -/
theorem sum_taoDivisorSieveWeight_Ioc_le_main_add_level
    (R X : ℕ) (lam : ℕ → ℝ)
    (hlam : ∀ d ∈ Finset.Icc 1 R, |lam d| ≤ 1) :
    (∑ n ∈ Finset.Ioc 0 X, taoDivisorSieveWeight R lam n) ≤
      (X : ℝ) * taoSieveCoefficientMainMass R lam + R := by
  have hdiff :=
    abs_sum_taoDivisorSieveWeight_sub_main_le_level R X lam hlam
  have hupper :
      (∑ n ∈ Finset.Ioc 0 X, taoDivisorSieveWeight R lam n) -
          (X : ℝ) * taoSieveCoefficientMainMass R lam ≤ R :=
    (le_abs_self _).trans hdiff
  linarith

/-- Any upper bound for the coefficient main mass transfers to the total
sieve mass, with the exact additive floor error `R`. -/
theorem sum_taoDivisorSieveWeight_Ioc_le_of_mainMass_le
    (R X : ℕ) (lam : ℕ → ℝ) (B : ℝ)
    (hlam : ∀ d ∈ Finset.Icc 1 R, |lam d| ≤ 1)
    (hmain : taoSieveCoefficientMainMass R lam ≤ B) :
    (∑ n ∈ Finset.Ioc 0 X, taoDivisorSieveWeight R lam n) ≤
      (X : ℝ) * B + R := by
  calc
    (∑ n ∈ Finset.Ioc 0 X, taoDivisorSieveWeight R lam n) ≤
        (X : ℝ) * taoSieveCoefficientMainMass R lam + R :=
      sum_taoDivisorSieveWeight_Ioc_le_main_add_level R X lam hlam
    _ ≤ (X : ℝ) * B + R := by
      gcongr

end

end Tao2026
