import Tao2026.SmoothNumberCEPWeights

/-!
# The exact CEP source packet

This file specializes the abstract collision-free packet and smooth-cofactor
recurrence to the source intervals, geometric weights, and integer
multiplicities in the proof of Canfield--Erdős--Pomerance Theorem 3.1.
-/

open scoped BigOperators

namespace Tao2026

noncomputable section

open Finset

/-- The canonical natural smoothness cutoff corresponding to `x^(1/u)`. -/
def cepSourceSmoothCutoff (x u : ℝ) : ℕ := ⌊x ^ (1 / u)⌋₊

/-- The source cofactor cutoff is the floor of the lowest prime-band lower
endpoint.  This is the `w` used in the smooth-cofactor recurrence. -/
def cepSourceCofactorCutoff (x u : ℝ) : ℕ :=
  ⌊cepSourceBandLower x u (cepSourceBandCount u - 1)⌋₊

theorem cast_cepSourceCofactorCutoff_le_lower
    {x u : ℝ} (hx : 0 ≤ x) :
    (cepSourceCofactorCutoff x u : ℝ) ≤
      cepSourceBandLower x u (cepSourceBandCount u - 1) := by
  exact Nat.floor_le (Real.rpow_nonneg hx _)

theorem cepSourceCofactorCutoff_le_smoothCutoff
    {x u : ℝ} (hx : 1 ≤ x) (hu : 1 < u) :
    cepSourceCofactorCutoff x u ≤ cepSourceSmoothCutoff x u := by
  apply Nat.floor_mono
  exact (cepSourceBandLower_le_upper hx hu _).trans
    (cepSourceBandUpper_le_globalCutoff hx hu _)

theorem floor_cepSourceBandUpper_le_smoothCutoff
    {x u : ℝ} (hx : 1 ≤ x) (hu : 1 < u) (t : ℕ) :
    ⌊cepSourceBandUpper x u t⌋₊ ≤ cepSourceSmoothCutoff x u := by
  exact Nat.floor_mono (cepSourceBandUpper_le_globalCutoff hx hu t)

/-- The source family of prime intervals, indexed by `0, ..., k-1`. -/
noncomputable def cepSourcePrimeBands
    (x u : ℝ) (y : ℕ) (j : ℕ) : Finset (TaoBoundedPrime y) :=
  cepSourcePrimeBandAt x u y (cepSourceBandCount u) j

/-- The distinct combined multipliers generated by the exact source packet. -/
noncomputable def cepSourcePacketProducts
    (x u : ℝ) (y : ℕ) : Finset ℕ :=
  cepMultiscalePacketProducts (Finset.range (cepSourceBandCount u))
    (cepSourcePrimeBands x u y) (cepSourceBandMultiplicity u)

theorem disjoint_cepSourcePrimeBands
    {x u : ℝ} {y i j : ℕ} (hx : 1 ≤ x) (hu : 1 < u)
    (hi : i ∈ Finset.range (cepSourceBandCount u))
    (hj : j ∈ Finset.range (cepSourceBandCount u)) (hij : i ≠ j) :
    Disjoint (cepSourcePrimeBands x u y i) (cepSourcePrimeBands x u y j) := by
  exact disjoint_cepSourcePrimeBandAt hx hu hi hj hij

/-- A cutoff below the bottom endpoint of the lowest source band is below
every prime occurring anywhere in the source packet. -/
theorem nat_lt_prime_of_le_lowest_cepSourceBand
    {x u : ℝ} {y w j : ℕ} (hx : 1 ≤ x) (hu : 1 < u)
    (hw : (w : ℝ) ≤
      cepSourceBandLower x u (cepSourceBandCount u - 1))
    {p : TaoBoundedPrime y} (hp : p ∈ cepSourcePrimeBands x u y j) :
    w < (p : ℕ) := by
  apply nat_lt_prime_of_le_cepSourceBandLower
    (t := cepSourceBandCount u - 1 - j) (p := p)
  · exact hw.trans (cepSourceBandLower_anti hx hu (by omega))
  · exact hp

/-- Equation (3.11) for the exact source intervals and multiplicities. -/
theorem cepSource_primePacketProduct_le_sum_inv
    {x u : ℝ} {y : ℕ} (hx : 1 ≤ x) (hu : 1 < u) :
    ∏ j ∈ Finset.range (cepSourceBandCount u),
        (∑ p ∈ cepSourcePrimeBands x u y j,
          (((p : ℕ) : ℝ)⁻¹)) ^ cepSourceBandMultiplicity u j /
            (Nat.factorial (cepSourceBandMultiplicity u j) : ℝ) ≤
      ∑ m ∈ cepSourcePacketProducts x u y, ((m : ℝ)⁻¹) := by
  exact prod_reciprocalPrimeSum_pow_div_factorial_le_of_disjoint
    (Finset.range (cepSourceBandCount u)) (cepSourcePrimeBands x u y)
      (cepSourceBandMultiplicity u)
    (fun i hi j hj hij => disjoint_cepSourcePrimeBands hx hu hi hj hij)

/-- Equations (3.10)--(3.11), fully specialized to the exact CEP source
bands.  The remaining analytic input is the uniform lower density `hD` for
the smaller smooth cutoff. -/
theorem density_mul_X_mul_cepSourcePrimePacketProduct_le_psiNat
    {X w y : ℕ} {x u D : ℝ} (hD0 : 0 ≤ D)
    (hx : 1 ≤ x) (hu : 1 < u) (hwy : w ≤ y)
    (hw : (w : ℝ) ≤
      cepSourceBandLower x u (cepSourceBandCount u - 1))
    (hD : ∀ m ∈ cepSourcePacketProducts x u y,
      D * (X : ℝ) / (m : ℝ) ≤ (psiNat (X / m) w : ℝ)) :
    D * (X : ℝ) *
        ∏ j ∈ Finset.range (cepSourceBandCount u),
          (∑ p ∈ cepSourcePrimeBands x u y j,
            (((p : ℕ) : ℝ)⁻¹)) ^ cepSourceBandMultiplicity u j /
              (Nat.factorial (cepSourceBandMultiplicity u j) : ℝ) ≤
      (psiNat X y : ℝ) := by
  exact density_mul_X_mul_primePacketProduct_le_psiNat hD0 hwy
    (fun i hi j hj hij => disjoint_cepSourcePrimeBands hx hu hi hj hij)
    (fun _j _hj p hp => nat_lt_prime_of_le_lowest_cepSourceBand hx hu hw hp)
    hD

end

end Tao2026
