import Tao2026.SmoothNumberCEPPacket

/-!
# Finite CEP smooth-cofactor recurrence

This file formalizes the counting step in Canfield--Erdős--Pomerance (3.5).
A finite family of high-prime packet multipliers is paired with all smooth
cofactors below the corresponding quotient. Coprimality separates the two
prime ranges, making multiplication injective into the ambient smooth-number
finset.
-/

open scoped BigOperators

namespace Tao2026

noncomputable section

open Finset

/-- Multiplier/cofactor pairs in the finite CEP recurrence. -/
noncomputable def cepSmoothCofactorPairs
    (X w : ℕ) (M : Finset ℕ) : Finset (Σ _m : ℕ, ℕ) :=
  M.sigma fun m => Nat.smoothNumbersUpTo (X / m) (w + 1)

/-- Evaluation of a CEP multiplier/cofactor pair. -/
def cepSmoothCofactorValue (a : Σ _m : ℕ, ℕ) : ℕ := a.1 * a.2

theorem mem_cepSmoothCofactorPairs_iff
    {X w : ℕ} {M : Finset ℕ} {a : Σ _m : ℕ, ℕ} :
    a ∈ cepSmoothCofactorPairs X w M ↔
      a.1 ∈ M ∧ a.2 ≤ X / a.1 ∧ IsSmooth a.2 w := by
  simp [cepSmoothCofactorPairs, mem_smoothNumbersUpTo_source]

/-- The sigma-family has exactly the sum of the smooth-cofactor counts. -/
theorem card_cepSmoothCofactorPairs (X w : ℕ) (M : Finset ℕ) :
    (cepSmoothCofactorPairs X w M).card =
      ∑ m ∈ M, psiNat (X / m) w := by
  rw [cepSmoothCofactorPairs, Finset.card_sigma]
  simp [psiNat]

/-- A convenient source-facing sufficient condition for separating the
multiplier and cofactor ranges. -/
def HasPrimeFactorsAbove (w m : ℕ) : Prop :=
  ∀ q : ℕ, q.Prime → q ∣ m → w < q

theorem coprime_of_primeFactorsAbove_of_isSmooth
    {w m n : ℕ} (hm : HasPrimeFactorsAbove w m) (hn : IsSmooth n w) :
    Nat.Coprime m n := by
  apply Nat.coprime_of_dvd
  intro q hq hqm hqn
  exact (not_lt_of_ge ((isSmooth_iff.mp hn).2 q hq hqn)) (hm q hq hqm)

/-- Multiplication is injective on the CEP pair family when every multiplier
is nonzero and coprime to every allowed smooth cofactor. -/
theorem injOn_cepSmoothCofactorValue
    {X w : ℕ} {M : Finset ℕ}
    (hm0 : ∀ m ∈ M, m ≠ 0)
    (hcop : ∀ m ∈ M, ∀ n : ℕ, IsSmooth n w → Nat.Coprime m n) :
    Set.InjOn cepSmoothCofactorValue (cepSmoothCofactorPairs X w M) := by
  rintro ⟨m, n⟩ hmn ⟨m', n'⟩ hm'n' heq
  have hmn' := mem_cepSmoothCofactorPairs_iff.mp hmn
  have hm'n'' := mem_cepSmoothCofactorPairs_iff.mp hm'n'
  change m * n = m' * n' at heq
  have hmm' : m = m' := by
    apply Nat.dvd_antisymm
    · apply (hcop m hmn'.1 n' hm'n''.2.2).dvd_of_dvd_mul_right
      rw [← heq]
      exact dvd_mul_right _ _
    · apply (hcop m' hm'n''.1 n hmn'.2.2).dvd_of_dvd_mul_right
      rw [heq]
      exact dvd_mul_right _ _
  subst m'
  have hnn' : n = n' := by
    apply mul_left_cancel₀ (hm0 m hmn'.1)
    exact heq
  subst n'
  rfl

/-- The explicit high-prime condition discharges the coprimality hypothesis
in the pair-injectivity theorem. -/
theorem injOn_cepSmoothCofactorValue_of_primeFactorsAbove
    {X w : ℕ} {M : Finset ℕ}
    (hm0 : ∀ m ∈ M, m ≠ 0)
    (hhigh : ∀ m ∈ M, HasPrimeFactorsAbove w m) :
    Set.InjOn cepSmoothCofactorValue (cepSmoothCofactorPairs X w M) :=
  injOn_cepSmoothCofactorValue hm0 fun m hm _n hn =>
    coprime_of_primeFactorsAbove_of_isSmooth (hhigh m hm) hn

/-- The distinct products generated by the CEP smooth-cofactor recurrence. -/
noncomputable def cepSmoothCofactorProducts
    (X w : ℕ) (M : Finset ℕ) : Finset ℕ :=
  (cepSmoothCofactorPairs X w M).image cepSmoothCofactorValue

theorem card_cepSmoothCofactorProducts
    {X w : ℕ} {M : Finset ℕ}
    (hm0 : ∀ m ∈ M, m ≠ 0)
    (hhigh : ∀ m ∈ M, HasPrimeFactorsAbove w m) :
    (cepSmoothCofactorProducts X w M).card =
      ∑ m ∈ M, psiNat (X / m) w := by
  rw [cepSmoothCofactorProducts,
    Finset.card_image_iff.mpr
      (injOn_cepSmoothCofactorValue_of_primeFactorsAbove hm0 hhigh),
    card_cepSmoothCofactorPairs]

/-- Every generated product lies in the ambient `y`-smooth counting finset. -/
theorem cepSmoothCofactorProducts_subset_smoothNumbersUpTo
    {X w y : ℕ} {M : Finset ℕ} (hwy : w ≤ y)
    (hm0 : ∀ m ∈ M, m ≠ 0)
    (hmSmooth : ∀ m ∈ M, IsSmooth m y) :
    cepSmoothCofactorProducts X w M ⊆
      Nat.smoothNumbersUpTo X (y + 1) := by
  intro z hz
  rw [cepSmoothCofactorProducts, Finset.mem_image] at hz
  obtain ⟨⟨m, n⟩, hmn, rfl⟩ := hz
  have hmn' := mem_cepSmoothCofactorPairs_iff.mp hmn
  rw [mem_smoothNumbersUpTo_source]
  refine ⟨?_, ?_⟩
  · simpa only [mul_comm] using
      (Nat.le_div_iff_mul_le (Nat.pos_of_ne_zero (hm0 m hmn'.1))).mp hmn'.2.1
  · apply Nat.mul_mem_smoothNumbers (hmSmooth m hmn'.1)
    exact Nat.smoothNumbers_mono (Nat.add_le_add_right hwy 1) hmn'.2.2

/-- Exact finite CEP (3.5): the smooth-cofactor counts for separated packet
multipliers inject into the ambient smooth-number count. -/
theorem sum_psiNat_div_le_psiNat_of_primeFactorsAbove
    {X w y : ℕ} {M : Finset ℕ} (hwy : w ≤ y)
    (hm0 : ∀ m ∈ M, m ≠ 0)
    (hmSmooth : ∀ m ∈ M, IsSmooth m y)
    (hhigh : ∀ m ∈ M, HasPrimeFactorsAbove w m) :
    ∑ m ∈ M, psiNat (X / m) w ≤ psiNat X y := by
  rw [← card_cepSmoothCofactorProducts hm0 hhigh, psiNat_eq_card]
  exact Finset.card_le_card
    (cepSmoothCofactorProducts_subset_smoothNumbersUpTo hwy hm0 hmSmooth)

/-- If every prime in every band is above `w`, then every prime factor of a
combined packet multiplier is above `w`. -/
theorem hasPrimeFactorsAbove_cepMultiscalePacketProduct
    {ι : Type*} [DecidableEq ι] {w y m : ℕ} {J : Finset ι}
    {P : ι → Finset (TaoBoundedPrime y)} {r : ι → ℕ}
    (hP : ∀ j ∈ J, ∀ p ∈ P j, w < (p : ℕ))
    (hm : m ∈ cepMultiscalePacketProducts J P r) :
    HasPrimeFactorsAbove w m := by
  rw [cepMultiscalePacketProducts, Finset.mem_image] at hm
  obtain ⟨f, hf, rfl⟩ := hm
  intro q hq hqProd
  change q ∣ ∏ j ∈ J.attach, f j.1 j.2 at hqProd
  have hExists : ∃ j ∈ J.attach, q ∣ f j.1 j.2 :=
    (Prime.dvd_finsetProd_iff (S := J.attach) (p := q)
      hq.prime (fun j => f j.1 j.2)).mp hqProd
  obtain ⟨j, hj, hqj⟩ := hExists
  have hfj : f j.1 j.2 ∈ cepPrimePacketProducts (P j.1) (r j.1) :=
    (mem_cepMultiscalePacketChoices_iff.mp hf) j.1 j.2
  obtain ⟨p, hp, hqp⟩ :=
    exists_mem_of_prime_dvd_cepPrimePacketProduct hfj hq hqj
  rw [hqp]
  exact hP j.1 j.2 p hp

/-- CEP (3.5) specialized to the collision-free multiscale packet from
equation (3.11). -/
theorem sum_psiNat_div_multiscalePacketProducts_le_psiNat
    {ι : Type*} [DecidableEq ι] {X w y : ℕ} {J : Finset ι}
    {P : ι → Finset (TaoBoundedPrime y)} {r : ι → ℕ}
    (hwy : w ≤ y)
    (hP : ∀ j ∈ J, ∀ p ∈ P j, w < (p : ℕ)) :
    ∑ m ∈ cepMultiscalePacketProducts J P r, psiNat (X / m) w ≤
      psiNat X y := by
  apply sum_psiNat_div_le_psiNat_of_primeFactorsAbove hwy
  · intro m hm
    exact (isSmooth_iff.mp (mem_cepMultiscalePacketProducts_isSmooth hm)).1
  · intro m hm
    exact mem_cepMultiscalePacketProducts_isSmooth hm
  · intro m hm
    exact hasPrimeFactorsAbove_cepMultiscalePacketProduct hP hm

/-- CEP (3.10): a uniform lower density for every smooth cofactor turns the
counting recurrence into the reciprocal-multiplier sum used by the bootstrap. -/
theorem density_mul_X_mul_sum_inv_le_psiNat
    {X w y : ℕ} {M : Finset ℕ} {D : ℝ} (hwy : w ≤ y)
    (hm0 : ∀ m ∈ M, m ≠ 0)
    (hmSmooth : ∀ m ∈ M, IsSmooth m y)
    (hhigh : ∀ m ∈ M, HasPrimeFactorsAbove w m)
    (hD : ∀ m ∈ M,
      D * (X : ℝ) / (m : ℝ) ≤ (psiNat (X / m) w : ℝ)) :
    D * (X : ℝ) * ∑ m ∈ M, ((m : ℝ)⁻¹) ≤ (psiNat X y : ℝ) := by
  calc
    D * (X : ℝ) * ∑ m ∈ M, ((m : ℝ)⁻¹) =
        ∑ m ∈ M, D * (X : ℝ) / (m : ℝ) := by
      rw [Finset.mul_sum]
      simp only [div_eq_mul_inv]
    _ ≤ ∑ m ∈ M, (psiNat (X / m) w : ℝ) := by
      exact Finset.sum_le_sum fun m hm => hD m hm
    _ ≤ (psiNat X y : ℝ) := by
      exact_mod_cast
        sum_psiNat_div_le_psiNat_of_primeFactorsAbove hwy hm0 hmSmooth hhigh

/-- CEP (3.10) for the multiscale products built in equation (3.11). -/
theorem density_mul_X_mul_multiscaleSum_inv_le_psiNat
    {ι : Type*} [DecidableEq ι] {X w y : ℕ} {J : Finset ι}
    {P : ι → Finset (TaoBoundedPrime y)} {r : ι → ℕ} {D : ℝ}
    (hwy : w ≤ y)
    (hP : ∀ j ∈ J, ∀ p ∈ P j, w < (p : ℕ))
    (hD : ∀ m ∈ cepMultiscalePacketProducts J P r,
      D * (X : ℝ) / (m : ℝ) ≤ (psiNat (X / m) w : ℝ)) :
    D * (X : ℝ) *
        ∑ m ∈ cepMultiscalePacketProducts J P r, ((m : ℝ)⁻¹) ≤
      (psiNat X y : ℝ) := by
  apply density_mul_X_mul_sum_inv_le_psiNat hwy
  · intro m hm
    exact (isSmooth_iff.mp (mem_cepMultiscalePacketProducts_isSmooth hm)).1
  · intro m hm
    exact mem_cepMultiscalePacketProducts_isSmooth hm
  · intro m hm
    exact hasPrimeFactorsAbove_cepMultiscalePacketProduct hP hm
  · exact hD

/-- Combined finite CEP (3.10)--(3.11): the cofactor density times the exact
product of reciprocal-prime multinomial packets is a lower bound for the
ambient smooth-number count. -/
theorem density_mul_X_mul_primePacketProduct_le_psiNat
    {ι : Type*} [DecidableEq ι] {X w y : ℕ} {J : Finset ι}
    {P : ι → Finset (TaoBoundedPrime y)} {r : ι → ℕ} {D : ℝ}
    (hD0 : 0 ≤ D) (hwy : w ≤ y)
    (hdisj : ∀ j ∈ J, ∀ k ∈ J, j ≠ k → Disjoint (P j) (P k))
    (hP : ∀ j ∈ J, ∀ p ∈ P j, w < (p : ℕ))
    (hD : ∀ m ∈ cepMultiscalePacketProducts J P r,
      D * (X : ℝ) / (m : ℝ) ≤ (psiNat (X / m) w : ℝ)) :
    D * (X : ℝ) *
        ∏ j ∈ J,
          (∑ p ∈ P j, (((p : ℕ) : ℝ)⁻¹)) ^ r j /
            (Nat.factorial (r j) : ℝ) ≤
      (psiNat X y : ℝ) := by
  calc
    D * (X : ℝ) *
        ∏ j ∈ J,
          (∑ p ∈ P j, (((p : ℕ) : ℝ)⁻¹)) ^ r j /
            (Nat.factorial (r j) : ℝ) ≤
        D * (X : ℝ) *
          ∑ m ∈ cepMultiscalePacketProducts J P r, ((m : ℝ)⁻¹) := by
      exact mul_le_mul_of_nonneg_left
        (prod_reciprocalPrimeSum_pow_div_factorial_le_of_disjoint J P r hdisj)
        (mul_nonneg hD0 (Nat.cast_nonneg X))
    _ ≤ (psiNat X y : ℝ) :=
      density_mul_X_mul_multiscaleSum_inv_le_psiNat hwy hP hD

end

end Tao2026
