import RiemannZeta.GuthMaynard.HughesYoungCentralArithmeticBridge
import Mathlib.Analysis.Calculus.SmoothSeries

open Complex

noncomputable section

namespace RiemannZeta.GuthMaynard

/-!
# The logarithmic DFI operators on Hughes--Young equation (96)

The logarithms in the two DFI equation-(27) main factors are generated by
the three exponent variables in Hughes--Young equation (96).  This file
records the exact termwise differential identities.  The signs matter:
the `c` variable occurs in the denominator, so `-∂c` supplies `log r`.
-/

/-- The `hughesYoungEquation96LogA` definition used by the source-facing construction in `HughesYoungEquation96Derivatives`. -/
noncomputable def hughesYoungEquation96LogA (h l : ℕ) : ℂ :=
  Complex.log (Nat.gcd h (l + 1) : ℂ) - Complex.log (l + 1 : ℂ)

/-- The `hughesYoungEquation96LogB` definition used by the source-facing construction in `HughesYoungEquation96Derivatives`. -/
noncomputable def hughesYoungEquation96LogB (k l : ℕ) : ℂ :=
  Complex.log (Nat.gcd k (l + 1) : ℂ) - Complex.log (l + 1 : ℂ)

/-- The `hughesYoungEquation96LogR` definition used by the source-facing construction in `HughesYoungEquation96Derivatives`. -/
noncomputable def hughesYoungEquation96LogR (r : ℕ) : ℂ :=
  Complex.log (r + 1 : ℂ)

/-- The `hughesYoungDFILogFactorLeft` definition used by the source-facing construction in `HughesYoungEquation96Derivatives`. -/
noncomputable def hughesYoungDFILogFactorLeft (h r l : ℕ) : ℂ :=
  hughesYoungEquation96LogR r + 2 * Real.eulerMascheroniConstant +
    2 * hughesYoungEquation96LogA h l - Complex.log (h : ℂ)

/-- The `hughesYoungDFILogFactorRight` definition used by the source-facing construction in `HughesYoungEquation96Derivatives`. -/
noncomputable def hughesYoungDFILogFactorRight (k r l : ℕ) : ℂ :=
  hughesYoungEquation96LogR r + 2 * Real.eulerMascheroniConstant +
    2 * hughesYoungEquation96LogB k l - Complex.log (k : ℂ)

theorem hughesYoungEquation96Term_eq_cpow_product
    (h k : ℕ) (a b c : ℂ) (r l : ℕ) :
    hughesYoungEquation96Term h k a b c r l =
      ramanujanSum (l + 1) (r + 1) *
        (Nat.gcd h (l + 1) : ℂ) ^ a *
        (Nat.gcd k (l + 1) : ℂ) ^ b *
        (l + 1 : ℂ) ^ (-a - b) *
        (r + 1 : ℂ) ^ (-c) := by
  unfold hughesYoungEquation96Term
  have hl : ((l + 1 : ℕ) : ℂ) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero l
  have hr : ((r + 1 : ℕ) : ℂ) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero r
  rw [show -a - b = -(a + b) by ring]
  rw [Complex.cpow_neg, Complex.cpow_neg]
  field_simp
  simp only [Nat.cast_add, Nat.cast_one]

theorem hasDerivAt_hughesYoungEquation96Term_a
    (h k : ℕ) (a b c : ℂ) (r l : ℕ) :
    HasDerivAt (fun z => hughesYoungEquation96Term h k z b c r l)
      (hughesYoungEquation96Term h k a b c r l *
        hughesYoungEquation96LogA h l) a := by
  rw [hughesYoungEquation96Term_eq_cpow_product]
  have hg : (Nat.gcd h (l + 1) : ℂ) ≠ 0 := by
    exact_mod_cast (Nat.gcd_pos_of_pos_right h (Nat.succ_pos l)).ne'
  have hl : ((l + 1 : ℕ) : ℂ) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero l
  have hga := (Complex.hasStrictDerivAt_const_cpow
    (x := (Nat.gcd h (l + 1) : ℂ)) (y := a) (Or.inl hg)).hasDerivAt
  have hla0 := (Complex.hasStrictDerivAt_const_cpow
    (x := ((l + 1 : ℕ) : ℂ)) (y := -a - b) (Or.inl hl)).hasDerivAt
  have hla : HasDerivAt
      (fun z : ℂ => ((l + 1 : ℕ) : ℂ) ^ (-z - b))
      (((l + 1 : ℕ) : ℂ) ^ (-a - b) * Complex.log ((l + 1 : ℕ) : ℂ) * (-1)) a := by
    simpa only [Function.comp_apply, id] using
      hla0.comp a ((hasDerivAt_id a).neg.sub_const b)
  have hram : HasDerivAt (fun _ : ℂ => ramanujanSum (l + 1) (r + 1)) 0 a :=
    hasDerivAt_const a _
  have hgk : HasDerivAt (fun _ : ℂ => (Nat.gcd k (l + 1) : ℂ) ^ b) 0 a :=
    hasDerivAt_const a _
  have hrc : HasDerivAt (fun _ : ℂ => ((r + 1 : ℕ) : ℂ) ^ (-c)) 0 a :=
    hasDerivAt_const a _
  have hp := (((hram.mul hga).mul hgk).mul hla).mul hrc
  convert hp using 1
  · funext z
    simp only [Pi.mul_apply, hughesYoungEquation96Term_eq_cpow_product,
      Nat.cast_add, Nat.cast_one]
  · simp only [Pi.mul_apply, hughesYoungEquation96LogA,
      Nat.cast_add, Nat.cast_one, zero_mul, zero_add, mul_zero, add_zero]
    ring

theorem hasDerivAt_hughesYoungEquation96Term_b
    (h k : ℕ) (a b c : ℂ) (r l : ℕ) :
    HasDerivAt (fun z => hughesYoungEquation96Term h k a z c r l)
      (hughesYoungEquation96Term h k a b c r l *
        hughesYoungEquation96LogB k l) b := by
  rw [hughesYoungEquation96Term_eq_cpow_product]
  have hg : (Nat.gcd k (l + 1) : ℂ) ≠ 0 := by
    exact_mod_cast (Nat.gcd_pos_of_pos_right k (Nat.succ_pos l)).ne'
  have hl : ((l + 1 : ℕ) : ℂ) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero l
  have hgb := (Complex.hasStrictDerivAt_const_cpow
    (x := (Nat.gcd k (l + 1) : ℂ)) (y := b) (Or.inl hg)).hasDerivAt
  have hlb0 := (Complex.hasStrictDerivAt_const_cpow
    (x := ((l + 1 : ℕ) : ℂ)) (y := -a - b) (Or.inl hl)).hasDerivAt
  have hlb : HasDerivAt
      (fun z : ℂ => ((l + 1 : ℕ) : ℂ) ^ (-a - z))
      (((l + 1 : ℕ) : ℂ) ^ (-a - b) * Complex.log ((l + 1 : ℕ) : ℂ) * (-1)) b := by
    have hx := hlb0.comp b
      ((hasDerivAt_const b (-a)).sub (hasDerivAt_id b))
    simpa only [Function.comp_apply, id, zero_sub] using hx
  have hram : HasDerivAt (fun _ : ℂ => ramanujanSum (l + 1) (r + 1)) 0 b :=
    hasDerivAt_const b _
  have hha : HasDerivAt (fun _ : ℂ => (Nat.gcd h (l + 1) : ℂ) ^ a) 0 b :=
    hasDerivAt_const b _
  have hrc : HasDerivAt (fun _ : ℂ => ((r + 1 : ℕ) : ℂ) ^ (-c)) 0 b :=
    hasDerivAt_const b _
  have hp := (((hram.mul hha).mul hgb).mul hlb).mul hrc
  convert hp using 1
  · funext z
    simp only [Pi.mul_apply, hughesYoungEquation96Term_eq_cpow_product,
      Nat.cast_add, Nat.cast_one]
  · simp only [Pi.mul_apply, hughesYoungEquation96LogB,
      Nat.cast_add, Nat.cast_one, zero_mul, zero_add, mul_zero, add_zero]
    ring

theorem hasDerivAt_hughesYoungEquation96Term_c
    (h k : ℕ) (a b c : ℂ) (r l : ℕ) :
    HasDerivAt (fun z => hughesYoungEquation96Term h k a b z r l)
      (-(hughesYoungEquation96Term h k a b c r l *
        hughesYoungEquation96LogR r)) c := by
  rw [hughesYoungEquation96Term_eq_cpow_product]
  have hr : ((r + 1 : ℕ) : ℂ) ≠ 0 := by
    exact_mod_cast Nat.succ_ne_zero r
  have hrc0 := (Complex.hasStrictDerivAt_const_cpow
    (x := ((r + 1 : ℕ) : ℂ)) (y := -c) (Or.inl hr)).hasDerivAt
  have hrc : HasDerivAt
      (fun z : ℂ => ((r + 1 : ℕ) : ℂ) ^ (-z))
      (((r + 1 : ℕ) : ℂ) ^ (-c) * Complex.log ((r + 1 : ℕ) : ℂ) * (-1)) c := by
    simpa only [Function.comp_apply, id] using
      hrc0.comp c (hasDerivAt_id c).neg
  have hconst : HasDerivAt (fun _ : ℂ =>
      ramanujanSum (l + 1) (r + 1) *
        (Nat.gcd h (l + 1) : ℂ) ^ a *
        (Nat.gcd k (l + 1) : ℂ) ^ b *
        (l + 1 : ℂ) ^ (-a - b)) 0 c := hasDerivAt_const c _
  have hp := hconst.mul hrc
  convert hp using 1
  · funext z
    simp only [Pi.mul_apply, hughesYoungEquation96Term_eq_cpow_product,
      Nat.cast_add, Nat.cast_one]
  · simp only [hughesYoungEquation96LogR,
      Nat.cast_add, Nat.cast_one, zero_mul, zero_add]
    ring

/-- The first DFI logarithmic factor is exactly the eigenvalue of
`2∂a - ∂c + 2γ - log h` on an equation-(96) summand. -/
theorem hughesYoungDFILogFactorLeft_eq_parameter_operator
    (h r l : ℕ) :
    hughesYoungDFILogFactorLeft h r l =
      2 * hughesYoungEquation96LogA h l +
        hughesYoungEquation96LogR r + 2 * Real.eulerMascheroniConstant -
          Complex.log (h : ℂ) := by
  unfold hughesYoungDFILogFactorLeft
  ring

/-- The second DFI logarithmic factor is exactly the eigenvalue of
`2∂b - ∂c + 2γ - log k` on an equation-(96) summand. -/
theorem hughesYoungDFILogFactorRight_eq_parameter_operator
    (k r l : ℕ) :
    hughesYoungDFILogFactorRight k r l =
      2 * hughesYoungEquation96LogB k l +
        hughesYoungEquation96LogR r + 2 * Real.eulerMascheroniConstant -
          Complex.log (k : ℂ) := by
  unfold hughesYoungDFILogFactorRight
  ring

end RiemannZeta.GuthMaynard
