import TaoTrudgianYang2025.AtkinsonMorseStationary

#print axioms TaoTrudgianYang2025.atkinsonSourceCutoff_frequency_natural
#print axioms TaoTrudgianYang2025.exists_atkinsonPowerIntegral_morse_pair
#print axioms TaoTrudgianYang2025.exists_norm_atkinsonLeadingTerm_sub_stationary_morse_le
#print axioms TaoTrudgianYang2025.exists_norm_atkinsonLeadingFiniteSum_sub_stationary_mass_morse_le
#print axioms TaoTrudgianYang2025.exists_norm_atkinsonLeadingFiniteSum_sub_stationary_morse_le
#print axioms TaoTrudgianYang2025.atkinsonMorse_cutoff_scale_le
#print axioms TaoTrudgianYang2025.exists_atkinsonStationary_finite_full_width_error
#print axioms TaoTrudgianYang2025.exists_atkinsonLeadingSum_sub_stationary_full_width
#print axioms TaoTrudgianYang2025.exists_zetaSquarePhysicalGaussian_stationary_full_width
#print axioms TaoTrudgianYang2025.exists_zetaSquareLocalMean_le_stationary_full_width
#print axioms TaoTrudgianYang2025.exists_zetaSquarePhysicalGaussian_signedMain_full_width
