import TaoTrudgianYang2025.AtkinsonMorseStationary

-- Regression: canonical production proofs, including their actual dependencies.
#print axioms TaoTrudgianYang2025.contDiffAt_atkinsonRootPhase_infty
#print axioms TaoTrudgianYang2025.deriv_deriv_atkinsonRootPhase
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCurvature_contDiffAt
#print axioms TaoTrudgianYang2025.atkinsonRoot_deficit_eq_morseCurvature
#print axioms TaoTrudgianYang2025.one_le_atkinsonRootMorseCurvature
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_normalForm
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_contDiffAt
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_at_saddle
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCurvature_at_saddle
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_hasDerivAt_saddle
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_deriv_of_ne
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_deriv_pos
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_strictMonoOn
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_coordinate
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_pos
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_inverse
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_hasStrictDerivAt
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_hasStrictDerivAt
#print axioms TaoTrudgianYang2025.atkinsonRootMorseRange_isOpen
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_contDiffAt
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_deriv_pos
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_injOn
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_image
#print axioms TaoTrudgianYang2025.atkinsonRoot_integral_eq_morseIntegral
#print axioms TaoTrudgianYang2025.atkinsonPowerIntegral_eq_root_Ioi
#print axioms TaoTrudgianYang2025.atkinsonRootKernel_morseInverse
#print axioms TaoTrudgianYang2025.atkinsonPowerIntegral_eq_morse
#print axioms TaoTrudgianYang2025.zero_mem_atkinsonRootMorseRange
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_zero
#print axioms TaoTrudgianYang2025.atkinsonRootMorseInverse_deriv_zero
#print axioms TaoTrudgianYang2025.atkinsonStationaryMain_eq_morse_main
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCurvature_le
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCurvature_physical_bounds
#print axioms TaoTrudgianYang2025.atkinsonRootMorseCoordinate_physical_deriv_bounds
#print axioms TaoTrudgianYang2025.norm_atkinsonPowerIntegral_sub_stationary_eq_morseRemainder
