import GafniTao.WooleySection10Theorem
import GafniTao.WooleySourceBoxing

#check Polynomial.sub_dvd_eval_sub
#check Polynomial.eval_sub
#check Polynomial.eval_add
#check Polynomial.eval_mul
#check IsCoprime.dvd_of_dvd_mul_left
#check IsCoprime.dvd_of_dvd_mul_right
#check IsCoprime.pow_left
#check IsCoprime.pow_right
#check Int.isCoprime_iff_gcd_eq_one
#check Int.gcd_eq_one_iff_coprime
#check Int.Coprime
#check Nat.Prime.coprime_iff_not_dvd
#check Nat.Prime.coprime_pow_of_not_dvd
#check Nat.Coprime.pow_left
#check Nat.Coprime.pow_right
#check Int.ModEq.cancel_right_of_coprime
#check Int.ModEq.cancel_left_of_coprime
#check ZMod.intCast_eq_intCast_iff
#check Nat.ceilDiv_one
#check Nat.ceilDiv_le_self
#check Real.one_le_rpow
#check Int.modEq_iff_dvd
#check Int.modEq_iff_dvd'
#check Int.ModEq.dvd
#check Polynomial.eval₂_at
#check Polynomial.eval_map
#check Polynomial.eval₂_eq_eval_map
#check ford_pow_mul_conj_pow
#check Complex.ofReal_inv
#check Complex.ofReal_sum
#check Complex.ofReal_normSq
#check Complex.normSq_eq_abs
#check Complex.sq_norm
#check Finset.sum_filter
