import GafniTao.FordLemma65Iteration
import Mathlib.Analysis.Complex.ExponentialBounds
#check one_add_mul_le_pow
#check Real.exp_nat_mul
#check Real.log_pow
#check Real.exp_log
#check Real.exp_le_exp
#check Real.log_le_sub_one_of_pos
#check Real.exp_neg_one_lt_half
#check one_div_le_one_div_of_le
#check Finset.sum_Icc_succ_top
#check Finset.sum_Icc_succ_bot
#check Finset.sum_Icc_eq_sum_range
#check Finset.sum_range_id
#check HasDerivAt.const_mul
#check HasDerivAt.mul_const
#check HasDerivAt.fun_sum
#check HasDerivAt.sum
#check abs_sum_le_sum_abs
#check abs_add_le
#check Fin.sum_univ_eq_sum_range
#check Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
#check Convex.norm_image_sub_le_of_norm_deriv_le
#check Real.norm_exp_I_mul_ofReal_sub_one_le
#check HasDerivAt.cexp
#check HasDerivAt.clog
#check Nat.le_div_iff_mul_le
#check Nat.le_div_iff_mul_le'
#check Nat.div_le_iff_le_mul
#check Nat.mul_div_cancel_left
#check pow_div
