import GafniTao.FordShiftedWeylCore
#check Real.rpow_mul
#check Real.rpow_natCast
#check Real.rpow_add
#check Real.mul_rpow
#check Real.rpow_pos_of_pos
#check Real.rpow_le_rpow
#check Real.rpow_le_rpow_of_exponent_le
#check Real.rpow_neg
#check Real.sqrt_sq_eq_abs
#check pow_left_inj₀
#check Odd.strictMono_pow
#check Odd.strictMono_pow_of_nonneg
#check Real.strictMonoOn_pow_of_odd
