import GafniTao.WooleySourceMean
#check Finsupp.single
#check Finsupp.sum_apply
#check Finsupp.sum_single_index
#check Finsupp.support_single_ne_zero
#check Finset.sum_fiberwise
#check Finset.sum_bij
#check Finset.sum_equiv
#check Finsupp.embDomain
#check Finsupp.mapDomain
#check Finsupp.lsingle
#check Finsupp.single_apply
#check Finset.sum_ite_irrel
#check Finset.sum_ite_eq'
#check Finsupp.equivFunOnFinite
#check Finsupp.equivFunOnFinite_symm_apply_toFun
#check Finsupp.embDomain_apply
#check Finsupp.support_embDomain
