import Tao2026.ErdosSelfridgePowerFree

#check gcd_mul_dvd_mul_gcd
#check Nat.dvd_gcd
#check Nat.gcd_eq_left_iff_dvd
#check Nat.gcd_eq_right_iff_dvd
#check Nat.dvd_sub
#check Nat.dvd_sub'
#check Nat.gcd_dvd_left
#check Nat.gcd_dvd_right
#check Nat.dist_eq
#check Nat.dist_lt_iff
#check Finset.prod_le_prod
#check Finset.prod_le_pow_card
#check Finset.prod_pos
#check Finset.prod_dvd_prod_of_subset
#check Finset.prod_dvd_prod_of_subset_of_dvd
#check Finset.prod_sdiff
#check Finset.prod_sdiff_mul_prod_inter
#check Finset.prod_inter_mul_prod_sdiff
#check Finset.prod_eq_zero_iff
#check Nat.le_of_dvd
#check Nat.pow_le_pow_left
#check Nat.pow_lt_pow_left
#check Nat.pow_le_pow_right
#check Nat.pow_lt_pow_right
#check Prime.dvd_finset_prod_iff
#check Nat.Prime.dvd_finset_prod_iff
#check Prime.dvd_prod_iff
#check Nat.Prime.dvd_mul
#check Nat.Prime.pow_dvd_iff_le_factorization
#check Nat.factorization_pos_of_dvd
#check Nat.factorization_le_iff_dvd
#check pow_le_iff_le_left
#check Nat.pow_le_iff_le_left
#check Nat.lt_of_pow_lt_pow_left
#check Nat.le_of_pow_le_pow_left
#check Nat.one_le_pow
#check pow_le_pow_left'
#check Nat.pow_le_pow_iff_left
#check Nat.mul_sub_left_distrib
#check Nat.pow_sub_pow_factor
#check Nat.sub_pos_of_lt
#check Finset.prod_const
#check Nat.dist_eq_sub_of_le
#check Nat.dist_eq_sub_of_le_left
#check Nat.dist_eq_sub_of_le_right
#check Finset.eq_of_subset_of_card_le
#check Finset.ssubset_iff_subset_ne
#check Finset.exists_of_ssubset
#check Finset.exists_mem_not_mem_of_card_lt_card
#check Finset.not_subset
#check Finset.ext_iff
#check Finset.dvd_prod_of_mem
#check Finset.dvd_prod
#check Finset.mem_of_subset
#check Finset.card_le_card
#check Nat.lt_of_lt_of_le
#check Nat.lt_of_le_of_lt
#check Nat.pow_lt_pow_right
