import Tao2026.ErdosSelfridgePowerFree

#check Prime.dvd_finset_prod_iff
#check Nat.Prime.dvd_finset_prod_iff
#check Nat.Prime.dvd_finset_prod_iff'
#check Finset.dvd_prod_iff
#check Prime.dvd_prod_iff
#check Nat.Prime.dvd_prod_iff
#check Nat.prime_iff_prime
#check Nat.prime_iff
#check Nat.Prime.prime
#check Nat.Prime.irreducible
#check Nat.mul_lt_mul_left
#check mul_lt_mul_left'
#check Nat.le_pow
#check Nat.pow_le_pow_right
#check Nat.Coprime.pow
#check Nat.Coprime.pow_left
#check Nat.Coprime.pow_right
#check Nat.Coprime.dvd_of_dvd_mul_left
#check Nat.Coprime.dvd_of_dvd_mul_right
#check Nat.Coprime.dvd_mul_right
#check Nat.Coprime.dvd_mul_left
#check Nat.dvd_iff_mod_eq_zero
#check Nat.mul_div_cancel'
#check Nat.mul_div_assoc
#check Nat.div_mul_cancel
#check Nat.eq_mul_of_div_eq_right
#check Nat.eq_mul_of_div_eq_left
#check Nat.pow_lt_pow_iff_left
#check Nat.div_pos
#check Nat.mul_right_cancel
#check Nat.mul_left_cancel
#check Nat.pow_sub_one_le_sub_pow
#check Nat.mul_le_mul
#check Nat.coprime_div_gcd_div_gcd
#check Nat.gcd_pos_of_pos_left
#check Nat.gcd_pos_of_pos_right
#check Nat.gcd_dvd_left
#check Nat.gcd_dvd_right
