import Tao2026.LowFrequency
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic

#check Finset.sum_Ico_succ_top
#check intervalIntegral.integral_add_adjacent_intervals
#check intervalIntegral.norm_integral_le_of_norm_le_const
#check MeasureTheory.norm_integral_le_of_norm_le_const
#check intervalIntegral.integral_const
#check intervalIntegral.integral_sub
#check intervalIntegral.integral_const_mul
#check intervalIntegral.integral_mul_const
#check intervalIntegral.intervalIntegrable_iff
#check Continuous.intervalIntegrable
#check Convex.norm_image_sub_le_of_norm_deriv_le
#check Real.hasDerivAt_log
#check HasDerivAt.inv
#check Real.deriv_log
#check intervalIntegral.integral_of_le
#check intervalIntegral.integral_const
