import RiemannZeta.GuthMaynard.HughesYoungEquation84SourceLine
import Mathlib.MeasureTheory.Integral.IntegralEqImproper

open Filter MeasureTheory

#check Summable.tsum_prod'
#check Summable.tsum_prod_uncurry
#check Summable.prod_factor
#check Summable.tsum_comm'
#check Equiv.tsum_eq
#check Summable.prod_symm
#check MeasureTheory.integral_tsum
#print MeasureTheory.integral_tsum
#check MeasureTheory.Integrable.integral_norm
#check MeasureTheory.hasFiniteIntegral_iff_norm
#check MeasureTheory.integrableOn_const
#check MeasureTheory.integrable_const
#check MeasureTheory.lintegral_mono
#check MeasureTheory.lintegral_indicator
#check MeasureTheory.lintegral_const
#check ENNReal.tsum_coe_ne_top_iff_summable_coe
#check ENNReal.coe_tsum
#check ENNReal.summable_coe
#check ENNReal.hasSum_coe
#check ENNReal.tsum_mul_left
#check ENNReal.tsum_mul_right
#check ENNReal.mul_ne_top
#check ne_top_of_le_ne_top
#check ENNReal.tsum_le_tsum
#check NNReal.summable_coe
#check NNReal.hasSum_coe
#check ENNReal.coe_ne_top
#check enorm_le_enorm
#check enorm_le_coe
#check ofReal_norm_eq_enorm
#check measure_Icc_lt_top
#check ENNReal.coe_nnreal_eq
#check ofReal_norm
#check ENNReal.ofReal_mul
#check MeasureTheory.setLIntegral_const
#check MeasureTheory.lintegral_indicator_const
#check MeasureTheory.lintegral_const_mul
#check MeasureTheory.lintegral_mul_const
#check intervalIntegral_tendsto_integral
#check tendsto_neg_atTop_atBot
#check tendsto_id
#check tendsto_nhds_unique
#check ContinuousAt.comp
#check ContinuousAt.comp_of_eq
#check Continuous.continuousAt
#check Tendsto.sub
#check RiemannZeta.GuthMaynard.exists_norm_hughesYoungEquation84PositiveContourSeries_horizontal_le
