import RiemannZeta.GuthMaynard.HughesYoungActiveComplementGlobalBound

#check Real.rpow_le_rpow_of_exponent_le
#check Real.rpow_le_rpow_of_exponent_ge
#check Real.rpow_le_one_of_one_le_of_nonpos
#check Real.rpow_le_one
#check Real.inv_rpow
#check Real.rpow_neg
#check Real.rpow_neg_one
#check Real.rpow_nat_inv_pow_nat
#check Real.rpow_le_rpow
#check Real.one_le_rpow
#check Real.rpow_lt_rpow_of_exponent_lt
#check max_le
#check one_le_max
#check MeasureTheory.norm_integral_le_of_norm_le
#check MeasureTheory.integrable_norm_iff
#check MeasureTheory.Integrable.integral_prod_right
#check MeasureTheory.Integrable.integral_prod_left
#check intervalIntegral.norm_integral_le_of_norm_le
#check RiemannZeta.GuthMaynard.hughesYoungComplementBetaLoss_le_fiveThousand_mul
#check IntervalIntegrable.mono_set
#check intervalIntegral.integral_add_adjacent_intervals
#check intervalIntegral.norm_integral_le_of_norm_le
#check Filter.EventuallyLE.filter_mono
#check Filter.Tendsto.norm
#check Filter.Tendsto.le_const
#check MeasureTheory.IntervalIntegrable.sum
#check IntervalIntegrable.finset_sum
#check IntervalIntegrable.add
#check Finset.sum_induction
#check le_of_tendsto
